import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import * as acorn from './vendor/acorn/acorn.mjs';
import {baseline} from './active-title-tick-baseline.mjs';
const source=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const scriptStart=source.indexOf("'use strict';"),script=source.slice(scriptStart,source.indexOf('</script>',scriptStart));
const sourceAst=acorn.parse(script,{ecmaVersion:'latest'});
const fn=n=>{const f=sourceAst.body.find(f=>f.type==='FunctionDeclaration'&&f.id.name===n);return script.slice(f.start,f.end)+'\n';};
function realm(old=false){const C=vm.createContext({console});const run=s=>vm.runInContext(s,C);
 run(`'use strict';let W={clock:{day:13},notables:[],dynasty:3,houses:[{name:'House Crown',seat:0,sigilHue:0,charge:'lion'},{name:'House North',seat:1,sigilHue:1,charge:'bear'}],settlements:[{name:'Capital'},{name:'Northern Seat'}]},G={},effects=[],draws=[];function day(){return W.clock.day}function ageOf(n){return Math.floor((day()-n.birthDay)/360)}const document={getElementById:()=>null};function sigURL(){throw Error('unused DOM')}function dynastyChanged(...x){effects.push(x)}function nameUse(...x){effects.push(['nameUse',...x])}function deriveTraits(){return ['bold']}let rngState=123;function endow(n){rngState=(Math.imul(rngState,1664525)+1013904223)>>>0;draws.push(rngState);n.g=[rngState];}`);
 const start=source.indexOf('const NOTABLE_INDEXES=');run(source.slice(start,source.indexOf('\nconst TRAITS=',start))+fn('houseOf')+fn('fullTitle')+fn('notableById')+fn('killNotable')+Object.keys(baseline).map(n=>old?baseline[n]:fn(n)).join('\n'));
 run('notableIndexRebuild()');return {run};
}
function pair(dead=0){return [true,false].map(old=>{const r=realm(old);r.run(`for(let i=0;i<${dead};i++)mkNotable({name:'Archive '+i,alive:false,traits:['bold']});mkNotable({name:'Royal',role:'monarch',sex:'m',traits:['bold']});mkNotable({name:'North',house:1,role:'head',sex:'f',traits:['bold']});mkNotable({name:'Court',role:'courtier',sex:'f',traits:['bold']});W.monarch=W.notables[${dead}];`);return r;});}
function canonical(v){if(typeof v==='function')return ['function'];if(v===null||typeof v!=='object')return typeof v==='number'?(Number.isNaN(v)?['NaN']:Object.is(v,-0)?['-0']:v):v;if(v instanceof Map||Object.prototype.toString.call(v)==='[object Map]')return ['map',[...v].map(([k,x])=>[canonical(k),canonical(x)])];if(Object.prototype.toString.call(v)==='[object RegExp]')return ['regexp',v.source,v.flags,v.lastIndex];return [Array.isArray(v)?'array':'object',Reflect.ownKeys(v).map(k=>{const d=Object.getOwnPropertyDescriptor(v,k);return [k,d.enumerable,d.configurable,d.writable,'value'in d?canonical(d.value):['accessor']];})];}
const state=r=>canonical(r.run('({W,G,effects,draws,rngState})'));
function compare(P,expression){const values=P.map(r=>canonical(r.run(expression)));assert.deepEqual(values[1],values[0]);assert.deepEqual(state(P[1]),state(P[0]));}
test('actual title schedule preserves title histories, role changes, seats and RNG',()=>{const P=pair(100);compare(P,'tickTitles()');compare(P,'tickTitles()');compare(P,"W.clock.day=14;W.notables.at(-1).role='head';tickTitles()");compare(P,"W.clock.day=43;tickTitles();W.notables.at(-2).house=0;tickTitles()");compare(P,"W.houses[0].seat=1;W.clock.day=73;W.notables.at(-2)._tk2='';tickTitles()");});
test('actual dynasty and name map preserve only-living changes and duplicate title overwrite order',()=>{const P=pair(100);compare(P,"mkNotable({name:'Court',role:'courtier',traits:['bold']});nameLinker().map.get('Court')");compare(P,'adoptDynasty(1);nameLinker().map.size');compare(P,"W.clock.day=60;nameLinker().map.get('House North')");});
test('existing name cache invalidation remains exact across death, birth, house names and epochs',()=>{const P=pair();compare(P,'nameLinker();G._nl.k');compare(P,"killNotable(W.notables[2],'in testing',true);nameLinker();G._nl.k");compare(P,"mkNotable({name:'Newborn',role:'courtier',traits:['bold']});nameLinker();G._nl.k");compare(P,"W.houses[1].name='House Renamed';nameLinker();G._nl.k");compare(P,"W.clock.day=59;nameLinker();G._nl.k");compare(P,"W.clock.day=60;nameLinker();G._nl.k");});
test('title append callback sees births, deaths and later resurrections in archive order',()=>{const P=pair();compare(P,"let seen=[];W.notables[0].titles=[];W.notables[0].titles.push=function(v){seen.push('Royal');notableSetAlive(W.notables[1],false);W.notables[2].role='head';mkNotable({name:'Append',role:'head',traits:['bold']});return Array.prototype.push.call(this,v)};tickTitles();W.notables.map(n=>n.titles?.length)");compare(P,"notableSetAlive(W.notables[1],true);W.clock.day=43;tickTitles();W.notables.map(n=>n.titles?.length)");});
test('name callbacks retain live archive append/death ordering and exact draws',()=>{const P=pair();compare(P,"const full=fullTitle;let once=true;let named=[];fullTitle=function(n){named.push(n.name);if(once){once=false;notableSetAlive(W.notables[1],false);mkNotable({name:'Name Append',role:'courtier',traits:['bold']})}return full(n)};nameLinker();named.join(',')");});
test('unknown archive replacement/accessor fallback retains original alive read behavior',()=>{const P=pair();for(const r of P)r.run("let aliveReads=0;W.notables=[{id:100,name:'Unknown',role:'head',house:0,sex:'m',get alive(){aliveReads++;return true}}]");compare(P,'tickTitles();nameLinker();adoptDynasty(1);aliveReads');});
for(const dead of [0,10000])test(`all three live-only loops avoid ${dead} dead archive reads`,()=>{const P=pair(dead);for(const r of P)r.run("let reads=0,liveVisits=0;const archive=W.notables;W.notables=new Proxy(archive,{get(t,k,a){if(typeof k==='string'&&/^\\d+$/.test(k))reads++;return Reflect.get(t,k,a)}});NOTABLE_INDEXES.get(W).archive=W.notables;const originalLiving=livingNotables;livingNotables=function*(){for(const n of originalLiving()){liveVisits++;yield n;}};");compare(P,'tickTitles();adoptDynasty(1);nameLinker().map.size');assert.equal(P[0].run('reads'),(dead+3)*3);assert.equal(P[1].run('reads'),0);assert.equal(P[1].run('liveVisits'),9);assert.equal(P[1].run('W.notables.length'),dead+3);});
test('AST contract pins exact live loops, predicates and original name-cache dependency expression',()=>{const program=source.slice(source.indexOf("'use strict';"),source.indexOf('</script>',source.indexOf("'use strict';"))),ast=acorn.parse(program,{ecmaVersion:'latest'});const functions=ast.body.filter(n=>n.type==='FunctionDeclaration');for(const name of Object.keys(baseline)){const f=functions.find(n=>n.id.name===name),loops=[];function walk(n){if(!n?.type)return;if(n.type==='ForOfStatement')loops.push(n);for(const v of Object.values(n))if(Array.isArray(v))v.forEach(walk);else if(v?.type)walk(v)}walk(f);assert.equal(loops.length,1,name);assert.equal(loops[0].right.type,'CallExpression');assert.equal(loops[0].right.callee.name,'livingNotables');assert.equal(loops[0].right.arguments.length,0);assert.match(program.slice(loops[0].body.start,loops[0].body.end),/n\.alive/);assert.equal(fn(name).replace('for(const n of livingNotables())','for(const n of W.notables)').trim(),baseline[name].slice(0,baseline[name].lastIndexOf('}')+1).trim());}assert.match(fn('tickTitles'),/day\(\)%30!==13/);assert.match(fn('notableById'),/C\.byId\.get\(id\)/);assert.match(source,/W\.notables\.find\(m=>m\.heirs\.includes\(x\.id\)\)/);});
