import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import * as acorn from './vendor/acorn/acorn.mjs';
const source=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const scriptStart=source.indexOf("'use strict';"),script=source.slice(scriptStart,source.indexOf('</script>',scriptStart));
const sourceAst=acorn.parse(script,{ecmaVersion:'latest'});
const fn=n=>{const f=sourceAst.body.find(f=>f.type==='FunctionDeclaration'&&f.id.name===n);return script.slice(f.start,f.end)+'\n';};
function realm(){const C=vm.createContext({console});const run=s=>vm.runInContext(s,C);
 run(`'use strict';let W={clock:{day:13},notables:[],dynasty:3,houses:[{name:'House Crown',seat:0,sigilHue:0,charge:'lion'},{name:'House North',seat:1,sigilHue:1,charge:'bear'}],settlements:[{name:'Capital'},{name:'Northern Seat'}]},G={},effects=[],draws=[];function day(){return W.clock.day}function ageOf(n){return Math.floor((day()-n.birthDay)/360)}const document={getElementById:()=>null};function sigURL(){throw Error('unused DOM')}function markSigilDirty(){}function dynastyChanged(...x){effects.push(x)}function nameUse(...x){effects.push(['nameUse',...x])}function deriveTraits(){return ['bold']}let rngState=123;function endow(n){rngState=(Math.imul(rngState,1664525)+1013904223)>>>0;draws.push(rngState);n.g=[rngState];}`);
 const start=source.indexOf('const NOTABLE_INDEXES=');run(source.slice(start,source.indexOf('\nconst TRAITS=',start))+fn('houseOf')+fn('fullTitle')+fn('notableById')+fn('killNotable')+"function esc(s){return String(s)}\n"+fn('referenceRegex')+fn('referenceAdd')+fn('nameLinker')+['tickTitles','adoptDynasty'].map(n=>fn(n)).join('\n'));
 run('notableIndexRebuild()');return {run};
}
function single(dead=0){const r=realm();r.run(`for(let i=0;i<${dead};i++)mkNotable({name:'Archive '+i,alive:false,traits:['bold']});mkNotable({name:'Royal',role:'monarch',sex:'m',traits:['bold']});mkNotable({name:'North',house:1,role:'head',sex:'f',traits:['bold']});mkNotable({name:'Court',role:'courtier',sex:'f',traits:['bold']});W.monarch=W.notables[${dead}];`);return r;}
test('name callbacks retain live archive append/death ordering',()=>{const r=single();const expr="(()=>{const full=fullTitle;let once=true;let named=[];fullTitle=function(n){named.push(n.name);if(once){once=false;notableSetAlive(W.notables[1],false);mkNotable({name:'Name Append',role:'courtier',traits:['bold']})}return full(n)};nameLinker();return named.join(',')})()";r.run(expr);assert.equal(r.run(expr),'Royal,Court,Name Append,Name Append');});
for(const dead of [0,10000])test(`title and dynasty loops avoid ${dead} dead archive reads`,()=>{const r=single(dead);r.run("let reads=0,liveVisits=0;const archive=W.notables;W.notables=new Proxy(archive,{get(t,k,a){if(typeof k==='string'&&/^\\d+$/.test(k))reads++;return Reflect.get(t,k,a)}});NOTABLE_INDEXES.get(W).archive=W.notables;const originalLiving=livingNotables;livingNotables=function*(){for(const n of originalLiving()){liveVisits++;yield n;}};");r.run('tickTitles();adoptDynasty(1)');assert.equal(r.run('reads'),0);assert.equal(r.run('liveVisits'),6);assert.equal(r.run('W.notables.length'),dead+3);});
test('current name map avoids dead archive reads independently of title ticks',()=>{const r=single(10000);r.run("let reads=0,visits=0;const archive=W.notables;W.notables=new Proxy(archive,{get(t,k,a){if(typeof k==='string'&&/^\\d+$/.test(k))reads++;return Reflect.get(t,k,a)}});NOTABLE_INDEXES.get(W).archive=W.notables;const live=livingNotables;livingNotables=function*(){for(const n of live()){visits++;yield n;}};nameLinker();");assert.equal(r.run('reads'),0);assert.equal(r.run('visits'),3);});
test('AST contract pins title and dynasty live loops and isolates name-map iteration',()=>{const program=source.slice(source.indexOf("'use strict';"),source.indexOf('</script>',source.indexOf("'use strict';"))),ast=acorn.parse(program,{ecmaVersion:'latest'});const functions=ast.body.filter(n=>n.type==='FunctionDeclaration'),walkLoops=f=>{const loops=[];function walk(n){if(!n?.type)return;if(n.type==='ForOfStatement')loops.push(n);for(const v of Object.values(n))if(Array.isArray(v))v.forEach(walk);else if(v?.type)walk(v)}walk(f);return loops;};for(const name of ['tickTitles','adoptDynasty']){const f=functions.find(n=>n.type==='FunctionDeclaration'&&n.id.name===name),loops=walkLoops(f);assert.equal(loops.length,1,name);assert.equal(loops[0].right.type,'CallExpression');assert.equal(loops[0].right.callee.name,'livingNotables');assert.equal(loops[0].right.arguments.length,0);assert.match(program.slice(loops[0].body.start,loops[0].body.end),/n\.alive/);}assert.match(fn('adoptDynasty'),/G\.crownDirty=true/);const linker=walkLoops(functions.find(n=>n.type==='FunctionDeclaration'&&n.id.name==='nameLinker'));assert.equal(linker.filter(n=>n.right.type==='CallExpression'&&n.right.callee.name==='livingNotables').length,1);assert.ok(!linker.some(n=>n.right.type==='MemberExpression'&&n.right.object.name==='W'&&n.right.property.name==='notables'),'nameLinker must not traverse the archive');assert.match(fn('nameLinker'),/for\(const a of W\.armies\|\|\[\]\)/,'army names remain included');assert.match(fn('tickTitles'),/day\(\)%30!==13/);assert.match(fn('notableById'),/C\.byId\.get\(id\)/);assert.match(source,/W\.notables\.find\(m=>m\.heirs\.includes\(x\.id\)\)/);});
