import test from 'node:test';import assert from 'node:assert/strict';import {realm,near} from './ownership-fixture.mjs';
function setup(cash=100){const r=realm({grain:0,fish:0,cash,households:2});r.eval("s.stores.timber=10;s.stores.stone=10;s.px.timber=s.px.stone=1;offer(s,'timber','crown',10);offer(s,'stone','crown',10);storageInit(s)");return r;}
for(const good of ['timber','stone'])test(good+' installation consumes only affordable buyer purchase',()=>{const r=setup(2);r.eval(`const used=buyBuildingMaterial(s,'${good}',H[0],4)`);near(r.eval('used'),2);near(r.s.stores[good],8);near(r.eval(`mkt(s,'${good}').get('crown')`),8);near(r.H[0].w,0);near(r.W.treasury,2);assert.equal(r.eval(`[...s.storage.lots.values()].filter(l=>l.good==='${good}'&&l.pendingPurchase).length`),0);});
test('an unfunded work cannot seize unbought timber',()=>{const r=setup(0);r.eval("buyBuildingMaterial(s,'timber',H[0],4)");near(r.s.stores.timber,10);near(r.eval("mkt(s,'timber').get('crown')"),10);});
test('construction leaves another buyers pending physical purchase intact',()=>{const r=setup();r.eval("purchase(s,'timber',H[1],1);const before=[...s.storage.lots.values()].find(l=>l.good==='timber'&&l.owner===accountOwner(H[1])&&l.pendingPurchase).id;buyBuildingMaterial(s,'timber',H[0],4)");near(r.s.stores.timber,6);near(r.eval("s.storage.lots.get(before).qty"),1);assert.equal(r.eval("s.storage.lots.get(before).pendingPurchase"),true);near(r.eval("mkt(s,'timber').get('crown')"),5);});
test('tiny positive purchase installs exact bought amount without pooled rounding subtraction',()=>{const r=realm({grain:0,fish:0,cash:100});r.eval("s.stores.timber=1e-12;s.px.timber=1;offer(s,'timber','crown',1e-12);storageInit(s);buyBuildingMaterial(s,'timber',H[0],5e-13)");assert.equal(r.s.stores.timber,5e-13);assert.equal(r.eval("mkt(s,'timber').get('crown')"),5e-13);});
test('legacy non-lot work also consumes only what was purchased',()=>{const r=realm({grain:0,fish:0,cash:2});r.eval("s.stores.timber=10;s.px.timber=1;offer(s,'timber','crown',10);buyBuildingMaterial(s,'timber',H[0],4)");near(r.s.stores.timber,8);near(r.eval("mkt(s,'timber').get('crown')"),8);});
test('pooled timber transfer moves charcoal alias title with its existing custody',()=>{const r=realm({grain:0,fish:0,cash:100});r.eval("householdsOf(s);s.stores.timber=20;offer(s,'timber','crown',16);addHeld(s,H[0],'char',4);storageInit(s);storageTitles(s,'timber');const d={name:'destination',owner:0,pos:{x:100,z:0},stores:{timber:0},buildings:[],_owners:new Map(),_ownershipReady:true};W.settlements.push(d);storageInit(d);moveStock(s,d,'timber',5);storageTitles(s,'timber');storageTitles(d,'timber')");near(r.s.stores.timber,15);near(r.W.settlements[1].stores.timber,5);near(r.eval("pantry(s,H[0]).char"),3);near(r.eval("pantry(W.settlements[1],H[0]).char"),1);near(r.eval("mkt(s,'timber').get('crown')"),12);near(r.eval("mkt(W.settlements[1],'timber').get('crown')"),4);near(r.eval("[...W.settlements[1].storage.lots.values()].filter(l=>l.claimGood==='char').reduce((n,l)=>n+l.qty,0)"),1);});
test('pooled transfer does not complete an unrelated pending receiver purchase',()=>{const r=realm({grain:0,fish:0,cash:100});r.eval("householdsOf(s);s.stores.timber=20;offer(s,'timber','crown',16);addHeld(s,H[0],'char',4);storageInit(s);storageTitles(s,'timber');const d={name:'destination',owner:0,pos:{x:100,z:0},stores:{timber:5},buildings:[],_owners:new Map(),_ownershipReady:true};W.settlements.push(d);offer(d,'timber','crown',5);storageInit(d);purchase(d,'timber',H[0],1,1);const pending=[...d.storage.lots.values()].find(l=>l.pendingPurchase).id;moveStock(s,d,'timber',5)");assert.equal(r.eval('d.storage.lots.get(pending).pendingPurchase'),true);near(r.eval('d.storage.lots.get(pending).qty'),1);near(r.eval('pantry(d,H[0]).char'),1);});
test('day1302 mature inland timber/charcoal transfer conserves exact observed magnitudes',()=>{const r=realm({grain:0,fish:0,cash:100});r.eval("householdsOf(s);s.stores.timber=406.92595112042716;offer(s,'timber','crown',406.92595112042716-41.98288601417815);addHeld(s,H[0],'char',41.98288601417815);storageInit(s);storageTitles(s,'timber');const d={name:'destination',owner:0,pos:{x:100,z:0},stores:{timber:0},buildings:[],_owners:new Map(),_ownershipReady:true};W.settlements.push(d);storageInit(d);moveStock(s,d,'timber',406.92595112042716-367.72752530853126);storageTitles(s,'timber');storageTitles(d,'timber')");near(r.s.stores.timber,367.72752530853126);near(r.eval('pantry(d,H[0]).char'),4.04413392231434);const gap=r.eval("[...s._owners.values()].reduce((n,x)=>n+(x.held.timber||0)+(x.held.char||0)+(x.sale.timber||0),0)-s.stores.timber");assert.ok(Math.abs(gap)<1e-10);near(r.s.stores.timber+r.W.settlements[1].stores.timber,406.92595112042716);});
