import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8'),core=source.split('// VISUAL DEFERRAL BEGIN')[1].split('// VISUAL DEFERRAL END')[0];
function fixture(hash=''){const timers=new Map();let next=0;const c=vm.createContext({window:{},location:{hash},W:{prehistory:false},G:{},speedIdx:5,performance:{now:()=>0},setTimeout:fn=>{timers.set(++next,fn);return next;},clearTimeout:i=>timers.delete(i),simErr:()=>{},setSpeed:i=>{c.speedIdx=i;}});vm.runInContext("//"+core,c);return{v:c.window.FURLONG_VISUAL,c,timers,step(){const [i,fn]=timers.entries().next().value||[];if(fn){timers.delete(i);fn();}}};}
test('coalesces each kind to its latest projection and settles after pause',()=>{const f=fixture(),out=[];f.v.defer('walls',()=>out.push(1));f.v.defer('walls',()=>out.push(2));f.v.defer('fences',()=>out.push(3));assert.equal(f.timers.size,1);assert.equal(f.v.jobs.size,2);f.c.speedIdx=0;f.v.settle();f.step();f.step();assert.deepEqual(out,[2,3]);assert.equal(f.v.jobs.size,0);});
test('prehistory retains bounded dirty work and runs none before it ends',()=>{const f=fixture();f.c.W.prehistory=true;for(let i=0;i<100;i++)f.v.defer('walls',()=>{});assert.equal(f.v.jobs.size,1);assert.equal(f.timers.size,0);f.c.W.prehistory=false;f.v.settle();f.step();assert.equal(f.v.jobs.size,0);});
test('new world discards obsolete callbacks',()=>{const f=fixture();let ran=false;f.v.defer('walls',()=>{ran=true;});f.c.G={};f.step();assert.equal(ran,false);assert.equal(f.v.jobs.size,0);});
test('projection failure pauses and retains dirty work until retry succeeds',()=>{const f=fixture();let fail=true,ran=0;f.v.defer('walls',()=>{if(fail)throw new Error('bad mesh');ran++;});f.step();assert.equal(f.c.speedIdx,0);assert.equal(f.v.jobs.size,1);assert.equal(f.timers.size,0);assert.match(f.v.status().fault,/bad mesh/);assert.equal(f.v.projecting,false);fail=false;f.v.retry();f.step();assert.equal(ran,1);assert.equal(f.v.jobs.size,0);});
test('ordinary pace and explicit off run synchronously',()=>{const f=fixture();f.c.speedIdx=1;assert.equal(f.v.defer('walls',()=>{}),false);const off=fixture('&defer=off');assert.equal(off.v.defer('walls',()=>{}),false);assert.equal(off.timers.size,0);});
test('projection does not recursively enqueue itself',()=>{const f=fixture();let nested;f.v.defer('walls',()=>{nested=f.v.defer('walls',()=>{});});f.step();assert.equal(nested,false);assert.equal(f.v.jobs.size,0);});
test('only the fastest player speed defers; prehistory alone cannot enable it',()=>{const f=fixture();for(const i of [0,1,2,3,4,6]){f.c.speedIdx=i;assert.equal(f.v.fast(),false);}f.c.W.prehistory=true;assert.equal(f.v.fast(),false);f.c.speedIdx=5;assert.equal(f.v.fast(),true);});
test('pure fence classification cannot populate the market price cache',()=>{const fn=source.match(/function fenceStoneView\(s\)\{[^\n]+/)[0],c=vm.createContext({price0:(_s,g)=>g==='stone'?5:10});vm.runInContext(fn,c);const s={res:{},px:{}};assert.equal(c.fenceStoneView(s),true);assert.deepEqual(s.px,{});s.px={stone:9,timber:10};assert.equal(c.fenceStoneView(s),false);});
test('uncached parcel projection is readonly; semantic wrapper alone retains the cache',()=>{const code=source.slice(source.indexOf('function furlongPoly(f)'),source.indexOf('function fenceStone(s)')),f={i:0,j:0,jx:0.5,jz:0.5,k:0},c=vm.createContext({G:{land:{F:[f]}},FN:1,FG:10,SIZE:10});vm.runInContext(code,c);const p=c.computeFurlongPoly(f);assert.equal(p.length,4);assert.equal(f.poly,undefined);assert.deepEqual(c.furlongPoly(f),p);assert.equal(c.furlongPoly(f),f.poly);});
test('catch-up waits for the original semantic detail refresh without invoking it',()=>{const f=fixture();f.c.speedIdx=0;f.c.G.detDirty=true;f.v.world=f.c.G;f.v.catching=true;f.v.schedule();f.step();assert.equal(f.c.G.detDirty,true);assert.equal(f.timers.size,1);assert.deepEqual(Array.from(f.v.status().pending),['details']);f.c.G.detDirty=false;f.step();assert.equal(f.v.catching,false);assert.equal(f.timers.size,0);});
test('settled catch-up relinquishes ordinary pace rendering',()=>{const f=fixture();f.c.speedIdx=0;f.v.catching=true;f.v.queue('fences',()=>{});f.step();assert.equal(f.v.catching,false);assert.equal(f.v.defer('fences',()=>{}),false);});
test('finish times out honestly when disabled RAF leaves semantic details pending',async()=>{const f=fixture();f.c.speedIdx=0;f.c.G.detDirty=true;f.v.world=f.c.G;f.v.catching=true;await assert.rejects(f.v.finish(0),/Visual catch-up timeout: details/);assert.equal(f.c.G.detDirty,true);assert.equal(f.v.catching,true);});
