import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';
import {inspectCheckpoint,personNamespace,INSPECT,validateExpressions} from './long-run-check.mjs';
import {inventoryAudit} from './inventory-audit.mjs';
const residual=8.881784197001252e-16;
function town(){return {name:'native-shaped',pop:0,stores:{sheep:10},_herdLast:{sheep:10},_owners:new Map(Array.from({length:161},(_,i)=>[i,{animals:{},held:{},sale:{}}]))};}
function check(s,state){return inspectCheckpoint({settlements:[s]}, {bldList:[]},361,['sheep'],{},inventoryAudit,personNamespace,state);}
test('retained observed sheep scale survives cancellation while fresh scope reproduces native false alarm',()=>{const s=town(),state={};assert.deepEqual(check(s,state).faults,[]);s.stores.sheep=0;s._herdLast.sheep=0;s._owners.get(0).sale.sheep=residual;assert.deepEqual(check(s,state).faults,[]);const fresh=check(s);assert.equal(fresh.faults[0].kind,'animal-overclaim');assert.ok(JSON.stringify(fresh).includes('animal-overclaim'));assert.equal(state.checks,2);s._owners.get(0).sale.sheep=1e-5;assert.ok(JSON.stringify(check(s,state)).includes('animal-overclaim'));});
test('settlement identities and fresh world scopes never borrow another observed scale',()=>{const state={},first=town();check(first,state);const late=town();late.stores.sheep=0;late._herdLast.sheep=0;late._owners.get(0).sale.sheep=residual;assert.ok(JSON.stringify(check(late,state)).includes('animal-overclaim'));assert.ok(JSON.stringify(check(late,{})).includes('animal-overclaim'));assert.equal(state.scales.has(first),true);assert.equal(state.scales.has(late),true);assert.notEqual(state.scales.get(first),state.scales.get(late));});
test('native expression uses one persistent state object without modifying game balances',()=>{validateExpressions();const s=town(),H={inventoryState:{}},C=vm.createContext({W:{settlements:[s]},G:{bldList:[]},day:()=>361,BEASTS:['sheep'],STORAGE_GOODS:{},__long:H});assert.deepEqual(Array.from(vm.runInContext(INSPECT,C).faults),[]);s.stores.sheep=0;s._herdLast.sheep=0;s._owners.get(0).sale.sheep=residual;assert.deepEqual(Array.from(vm.runInContext(INSPECT,C).faults),[]);assert.equal(H.inventoryState.checks,2);assert.equal(s.stores.sheep,0);assert.equal(s._owners.get(0).sale.sheep,residual);});
