import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';
import {inspectCheckpoint,personNamespace,INSPECT,validateExpressions} from './long-run-check.mjs';
import {inventoryAudit} from './inventory-audit.mjs';
const residual=8.881784197001252e-16;
function town(){return {name:'native-shaped',pop:0,stores:{sheep:10},_herdLast:{sheep:10},_owners:new Map(Array.from({length:161},(_,i)=>[i,{animals:{},held:{},sale:{}}]))};}
function check(s,state){return inspectCheckpoint({settlements:[s]}, {bldList:[]},361,['sheep'],{},inventoryAudit,personNamespace,state);}
test('retained observed sheep scale survives cancellation while fresh scope reproduces native false alarm',()=>{const s=town(),state={};assert.deepEqual(check(s,state).faults,[]);s.stores.sheep=0;s._herdLast.sheep=0;s._owners.get(0).sale.sheep=residual;assert.deepEqual(check(s,state).faults,[]);const fresh=check(s);assert.equal(fresh.faults[0].kind,'animal-overclaim');assert.ok(JSON.stringify(fresh).includes('animal-overclaim'));assert.equal(state.checks,2);s._owners.get(0).sale.sheep=1e-5;assert.ok(JSON.stringify(check(s,state)).includes('animal-overclaim'));});
test('settlement identities and fresh world scopes never borrow another observed scale',()=>{const state={},first=town();check(first,state);const late=town();late.stores.sheep=0;late._herdLast.sheep=0;late._owners.get(0).sale.sheep=residual;assert.ok(JSON.stringify(check(late,state)).includes('animal-overclaim'));assert.ok(JSON.stringify(check(late,{})).includes('animal-overclaim'));assert.equal(state.scales.has(first),true);assert.equal(state.scales.has(late),true);assert.notEqual(state.scales.get(first),state.scales.get(late));});
test('native expression uses one persistent state object without modifying game balances',()=>{validateExpressions();const s=town(),H={inventoryState:{}},C=vm.createContext({W:{settlements:[s]},G:{bldList:[]},day:()=>361,BEASTS:['sheep'],STORAGE_GOODS:{},__long:H});assert.deepEqual(Array.from(vm.runInContext(INSPECT,C).faults),[]);s.stores.sheep=0;s._herdLast.sheep=0;s._owners.get(0).sale.sheep=residual;assert.deepEqual(Array.from(vm.runInContext(INSPECT,C).faults),[]);assert.equal(H.inventoryState.checks,2);assert.equal(s.stores.sheep,0);assert.equal(s._owners.get(0).sale.sheep,residual);});

test('actual source sale cancellation is allowed only by its own recorded operation budget',async()=>{const {realm}=await import('./ownership-fixture.mjs');const r=realm({grain:0,fish:0});r.eval('householdsOf(s);s.stores.sheep=6.586026944572982;const K=storageInit(s);offer(s,"sheep",H[0],6.586026944572983);consumeOwnStock(s,H[0],"sheep",6.586026944572983)');const K=r.s.storage,q=r.eval('mkt(s,"sheep").get(H[0])'),budget=K.roundoff.get('sheep').budget;assert.equal(q,residual);assert.equal(r.s.stores.sheep,0);assert.ok(budget>=q);assert.deepEqual(Array.from(K.roundoff.get('sheep').last.inputs),[6.586026944572983,residual,-6.586026944572982]);assert.equal(inventoryAudit([r.s],{},['sheep'],{}),null);assert.equal(r.eval('mkt(s,"sheep").get(H[0])'),q);const record=K.roundoff.get('sheep');K.roundoff.delete('sheep');assert.equal(inventoryAudit([r.s],{},['sheep'],{}).kind,'animal-overclaim');K.roundoff.set('cattle',record);assert.equal(inventoryAudit([r.s],{},['sheep'],{}).kind,'animal-overclaim');K.roundoff.set('sheep',record);r.eval('stockOf(s,H[0]).sale.sheep=1e-5');assert.equal(inventoryAudit([r.s],{},['sheep'],{}).kind,'animal-overclaim');});
test('invalid producer budgets cannot authorize animal overclaims',()=>{for(const budget of [NaN,Infinity,-1,'1',null,undefined]){const s=town();s.storage={roundoff:new Map([['sheep',{budget}]])};assert.equal(inventoryAudit([s],{},['sheep'],{}).kind,'invalid-animal-roundoff-budget');}const first=town();first.storage={roundoff:new Map([['sheep',{budget:1}]])};const second=town();second.stores.sheep=0;second._herdLast.sheep=0;second._owners.get(0).sale.sheep=residual;assert.equal(inventoryAudit([second],{},['sheep'],{}).kind,'animal-overclaim');});

test('present malformed provenance records fail while genuinely absent entries retain old behavior',()=>{for(const record of [undefined,null,0,1,'record',true,{}]){const s=town();s.storage={roundoff:new Map([['sheep',record]])};assert.equal(inventoryAudit([s],{},['sheep'],{}).kind,'invalid-animal-roundoff-budget');}const s=town();s.stores.sheep=0;s._herdLast.sheep=0;s._owners.get(0).sale.sheep=residual;s.storage={roundoff:new Map()};assert.equal(inventoryAudit([s],{},['sheep'],{}).kind,'animal-overclaim');});
