import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {buildGameConfig} from './game-write-game-config.mjs';import {transformWrites} from './game-write-transform.mjs';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8'),config=buildGameConfig(html),source=html.slice(config.script.offset,config.script.offset+config.script.length);
test('actual game persistent globals have source-resolved declaration offsets and unique tokens',()=>{for(const name of ['W','RS','PID','NID','JOURNAL','MOD','armyN','campN','speedIdx','simAccum','REPLAYING']){const b=config.transformOptions.bindings.find(v=>v.name===name);assert.ok(b,name);assert.equal(source.slice(b.declarationStart,b.declarationStart+name.length),name);}assert.equal(new Set(config.transformOptions.bindings.map(v=>v.token)).size,config.transformOptions.bindings.length);assert.match(config.sourceSHA256,/^[0-9a-f]{64}$/);assert.equal(config.manifest.sourceSHA256,config.sourceSHA256);});
test('existing history geography and land root inventory retain parent replacement gap',()=>{for(const expression of ['W','MOD','JOURNAL','G.tg','G.trackSet','G.rivHash','G.treeHash','G.land.F','G.land.mask','G.land.flood'])assert.ok(config.registrations.objects.some(v=>v.expression===expression),expression);assert.equal(config.registrations.objects.find(v=>v.expression==='G').status,'blocked');assert.ok(config.gaps.some(v=>v.reason.includes('parent replacement')));assert.equal(config.complete,false);});
test('RNG parameter cells and layout mutable/constant bindings remain explicit initialization gaps',()=>{const rng=config.registrations.closures.filter(v=>v.owner==='sfc32');assert.deepEqual(rng.map(v=>v.name),['a','b','c','d']);assert.ok(rng.every(v=>v.status==='unsupported'&&v.tokenRequirement.includes('stream')));const cur=config.registrations.closures.find(v=>v.name==='curE');assert.equal(cur.bindingKind,'let');assert.equal(source.slice(cur.declarationStart,cur.declarationStart+4),'curE');const idx=config.registrations.closures.find(v=>v.name==='idx');assert.equal(idx.bindingKind,'const');assert.equal(idx.role,'layout-construction-binding');});
test('only pinned recorder modules and spatial scratch are excluded; mixed helpers remain classified',()=>{for(const fn of ['storageTick','tickEconomy','buildTracks','animateWorld','setSpeed','storageBindClaims']){const start=source.indexOf('function '+fn+'(');assert.ok(start>=0);assert.ok(!config.transformOptions.excludeRanges.some(r=>start>=r.start&&start<r.end),fn);}assert.ok(config.writes.some(v=>v.target==='s.storageReport'&&v.status==='lowered'));assert.ok(config.writes.some(v=>v.target==='G.tg'&&v.authority.includes('mixed')));assert.ok(!config.transformOptions.bindings.some(v=>v.name==='HASH_STAMP'));assert.ok(config.scratchExclusions.length>0);});
test('native status inventory never assumes sort/comparator, static assign or unknown method coverage',()=>{assert.ok(config.transformOptions.nativeContracts.set);assert.ok(!config.transformOptions.nativeContracts.sort);const sort=config.calls.find(v=>v.method==='sort'&&v.status!=='excluded');assert.equal(sort.status,'unsupported');const assign=config.calls.find(v=>v.callee==='Object.assign'&&v.status!=='excluded');assert.equal(assign.status,'unsupported');assert.ok(config.calls.some(v=>v.method==='move'&&v.status==='unsupported'));assert.ok(config.calls.every(v=>v.runtimeIdentityRequired));});
test('source-derived contracts detect drift rather than silently omitting new global authority',()=>{assert.throws(()=>buildGameConfig(html.replace('this.globals,{SEED,','this.globals,{unknownAuthority,SEED,')),/declaration missing/);const changed=html.replace('let SEED=','let newAuthority=0;let SEED=').replace('this.globals,{SEED,','this.globals,{newAuthority,SEED,');const c=buildGameConfig(changed);assert.ok(c.transformOptions.bindings.some(v=>v.name==='newAuthority'));assert.notEqual(c.sourceSHA256,config.sourceSHA256);assert.throws(()=>buildGameConfig(html.replace('// HISTORY CORE BEGIN','// missing core')),/Missing excluded module fence/);});
test('usable options generate the source-pinned script without writing product and reject unresolved full coverage',()=>{const r=transformWrites(source,config.transformOptions);assert.equal(r.manifest.sourceSHA256,config.sourceSHA256);assert.ok(r.code.includes('.cellSet('));assert.ok(r.code.includes('.set('));assert.ok(r.manifest.sites.some(v=>v.status==='unsupported'));assert.throws(()=>transformWrites(source,{...config.transformOptions,failUnsupported:true}),/Unsupported/);});

test('canonical facade hydration explicitly retains actual backing data and dynamic projections',()=>{for(const name of ['settlement-lard','stock-claim-proxy','person-household-assets','household-herd','settlement-population','physical-store-quantity','owned-market-view']){const f=config.registrations.facades.find(v=>v.name===name);assert.ok(f,name);assert.equal(f.status,'unsupported');assert.ok(f.backing.length>0);assert.match(f.sourceSHA256,/^[0-9a-f]{64}$/);assert.ok(!config.transformOptions.excludeRanges.some(r=>f.start>=r.start&&f.end<=r.end));}assert.ok(config.registrations.facades.find(v=>v.name==='settlement-lard').behavior.includes('ownKeys'));assert.ok(config.writes.some(w=>w.target==='t[g]'&&w.status==='lowered'));assert.ok(config.writes.some(w=>w.target==='x.held[g]'&&w.status==='lowered'));});
