import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {transformWrites,transformInlineScripts,markerExclusions} from './game-write-transform.mjs';
// Deliberately independent semantic oracle; no production logger imports.
function runtime(){const effects=[];const set=(o,k,v,strict)=>{if(o==null)throw TypeError('null receiver');k=Reflect.ownKeys({[k]:0})[0];const yes=Reflect.set(Object(o),k,v,o);if(!yes&&strict)throw new TypeError('write failed');effects.push(['set',String(k),typeof v==='bigint'?String(v)+'n':v]);return v;};const operators={'+':(a,b)=>a+b,'-':(a,b)=>a-b,'*':(a,b)=>a*b,'/':(a,b)=>a/b,'%':(a,b)=>a%b,'**':(a,b)=>a**b,'<<':(a,b)=>a<<b,'>>':(a,b)=>a>>b,'>>>':(a,b)=>a>>>b,'&':(a,b)=>a&b,'|':(a,b)=>a|b,'^':(a,b)=>a^b,'=':(a,b)=>b};
const numeric=v=>{const box={v};return [box.v++,box.v];};
const GLOG={key(k){return Reflect.ownKeys({[k]:0})[0];},set,ref(o,k,strict,site){return {value:o[k],write:v=>set(o,k,v,strict),site};},compound(r,v,op){return r.write(operators[op](r.value,v));},update(o,k,delta,prefix,strict){const [old,next]=numeric(o[k]);const value=delta===1?next:typeof old==='bigint'?old-1n:old-1;set(o,k,value,strict);return prefix?value:old;},delete(o,k,strict){if(o==null)throw TypeError();const yes=Reflect.deleteProperty(Object(o),k);if(!yes&&strict)throw new TypeError('delete failed');effects.push(['delete',String(k),yes]);return yes;},call(o,method,args){const value=Reflect.apply(method,o,args);effects.push(['call',args.length]);return value;},cellSet(write,v){const value=write(v);effects.push(['cell',v]);return value;},cellRef(read,write){return{value:read(),write:v=>{write(v);effects.push(['cell',v]);return v;}};},cellInit(v){effects.push(['init',v]);return v;},cellUpdate(read,write,delta,prefix){const [old,next]=numeric(read()),value=delta===1?next:typeof old==='bigint'?old-1n:old-1;write(value);effects.push(['cell',value]);return prefix?value:old;}};GLOG.cellCompound=GLOG.compound;return{GLOG,effects};}
function run(source,transformed,options={}){const {GLOG,effects}=runtime(),ctx=vm.createContext({GLOG});const code=transformed?transformWrites(source,options).code:source;let error;try{vm.runInContext(code,ctx);}catch(e){error={name:e.name};}return{result:ctx.result===undefined?undefined:JSON.parse(JSON.stringify(ctx.result)),error,effects,code};}
function same(source,options){const a=run(source,false,options),b=run(source,true,options);assert.deepEqual(b.result,a.result,b.code);assert.deepEqual(b.error,a.error,b.code);return b;}
test('receiver, key coercion and RHS are evaluated once in original order',()=>{const b=same(`let trace=[];const o={};const key={ [Symbol.toPrimitive](){trace.push('key');return 'x';}};function receiver(){trace.push('object');return o;}function rhs(){trace.push('rhs');return 7;}const v=receiver()[key]=rhs();result={trace,v,x:o.x};`);assert.deepEqual(b.result.trace,['object','rhs','key']);assert.equal(b.effects.filter(e=>e[0]==='set').length,1);});
test('compound getter precedes RHS while primitive conversion follows RHS',()=>same(`let trace=[];const left={valueOf(){trace.push('left convert');return 3;}};const o={get x(){trace.push('get');return left;},set x(v){trace.push('set '+v);}};const v=o.x+=(trace.push('rhs'),4);result={trace,v};`));
test('logical assignment skips getter/RHS/setter correctly and keeps lexical this/arguments',()=>same(`function f(){let trace=[];const o={x:0,y:2,z:null};const __gw_ref=9;const a=o.x&&=(trace.push('bad'),1);const b=o.y||=(trace.push('bad'),1);const c=o.z??=(trace.push(this.n+arguments[0]+__gw_ref),7);return {trace,a,b,c,o};}result=f.call({n:2},3);`));
test('postfix and prefix updates preserve ToNumeric BigInt and return value',()=>same(`const o={a:4n,b:'6',c:{valueOf(){return 3n;}}};const a=o.a++,b=--o.b,c=o.c--;result={a:String(a),b,c:String(c),end:[String(o.a),o.b,String(o.c)]};`));
test('strict/sloppy failed writes and deletes keep exception behavior',()=>{for(const directive of ['',"'use strict';"]){same(`${directive}const o={};Object.defineProperty(o,'x',{value:1,writable:false,configurable:false});const a=o.x=2;const b=delete o.x;result={a,b,x:o.x};`);}});
test('assignment return retains exact RHS object identity and exception partial effects',()=>{same(`const o={},v={n:1};const answer=o.x=v;result={same:answer===v&&o.x===v};`);same(`const o={};try{o.x=(o.y=2,(()=>{throw Error('rhs');})());}catch(e){}result={y:o.y,hasX:Object.hasOwn(o,'x')};`);});
test('member native call captures receiver and method before arguments with original this',()=>same(`let trace=[];const a=[];Object.defineProperty(a,'push',{get(){trace.push('method');return function(...x){trace.push(this===a?'this':'wrong');return Array.prototype.push.apply(this,x);};}});function recv(){trace.push('receiver');return a;}function arg(){trace.push('argument');return 4;}const v=recv().push(arg());result={trace,v,values:[...a]};`,{nativeContracts:{push:'canonical array data'}}));
test('native superclass collection mutations keep this, returns and invalidation order',()=>same(`let trace=[];class P extends Map{set(k,v){const r=super.set((trace.push('key'),k),(trace.push('value'),v));trace.push(r===this?'same':'wrong');return this;}}const p=new P();p.set('a',2);result={trace,entries:[...p]};`,{nativeContracts:{set:'native collection superclass'}}));
test('awaited simple and compound member RHS remain valid with preserved evaluation',async()=>{const source=`let trace=[];const o={x:2};async function f(){o.x+=await Promise.resolve((trace.push('rhs'),3));o.y=await Promise.resolve(7);return {trace,x:o.x,y:o.y};}globalThis.answer=f();`;for(const changed of [false,true]){const ctx=vm.createContext({GLOG:runtime().GLOG});vm.runInContext(changed?transformWrites(source).code:source,ctx);assert.deepEqual(JSON.parse(JSON.stringify(await ctx.answer)),{trace:['rhs'],x:5,y:7});}});
test('logical/native suspension, super and destructuring are explicit unsupported sites',()=>{for(const source of [`async function f(o){o.x ||= await f();}`,`function* f(o){o.x &&= yield 2;}`,`async function f(o){o.push(await f());}`,`class A extends B{f(){super.x=2;}}`,`({x:o.x}=a);`]){const r=transformWrites(source,{nativeContracts:{push:'approved'}});assert.ok(!r.manifest.complete);assert.ok(r.manifest.sites.some(s=>s.status==='unsupported'));assert.throws(()=>transformWrites(source,{failUnsupported:true}),/Unsupported/);}});
test('direct eval cannot be moved into generated lexical scopes',()=>{const r=transformWrites(`function f(o){o.x ||= eval('var x=2');o.push(eval('var y=3'));}`,{nativeContracts:{push:'approved'}});assert.ok(r.manifest.sites.some(s=>s.reason.includes('logical')));assert.ok(!r.manifest.complete);assert.ok(r.code.includes("o.x ||= eval"));});
test('explicit declaration-bound cell contract ignores shadowing and preserves typeof TDZ',()=>{const source=`const token='global';let x=1;x+=2;function f(){let x=8;x++;return x;}let t;try{t=typeof y;}catch(e){t=e.name;}let y;result={x,inner:f(),t};`;const start=source.indexOf('x=1');const b=same(source,{bindings:[{name:'x',declarationStart:start,token:'token'}]});assert.deepEqual(b.effects.filter(v=>['cell','init'].includes(v[0])),[['init',1],['cell',3]]);assert.equal(b.result.t,'ReferenceError');});
test('binding update/logical assignments and immutable cells retain semantics',()=>{const source=`const token='cell';let x=2n;const a=x++;x??=7n;const b=--x;result={a:String(a),b:String(b),x:String(x)};`;same(source,{bindings:[{name:'x',declarationStart:source.indexOf('x=2n'),token:'token'}]});const c=`const token='cell';const x=2;x=3;`;same(c,{bindings:[{name:'x',declarationStart:c.indexOf('x=2'),token:'token'}]});});
test('manifest source hashes, explicit exclusions, unknown native sites and inline selection',()=>{const source='a.x=2;a.sort(f);';const r=transformWrites(source,{excludeRanges:[{start:0,end:6,reason:'audited scratch'}]});assert.match(r.manifest.sourceSHA256,/^[a-f0-9]{64}$/);assert.equal(r.manifest.sites[0].status,'excluded');assert.equal(r.manifest.sites.find(s=>s.kind==='native-call').status,'unsupported');assert.ok(!r.manifest.complete);const html=`<script src="external"></script><script>a.x=1;</script><script type="text/plain">invalid !</script>`;assert.equal(transformInlineScripts(html).scripts.length,1);});

test('raw keys preserve repeated read and PutValue coercion with different keys',()=>{for(const op of ['+= 3','&&= 3','||= 3','??= 3','++','--']){const source=`let trace=[],count=0;const key={[Symbol.toPrimitive](){trace.push('key '+count);return count++===0?'a':'b';}};const o={a:${op.startsWith('||')?'0':op.startsWith('??')?'null':'2'},b:9};let v;${op==='++'||op==='--'?`v=o[key]${op};`:`v=(o[key] ${op});`}result={trace,v,o};`;same(source);}same(`let trace=[],count=0;const key={[Symbol.toPrimitive](){trace.push('key');return count++?'b':'a';}};const o={a:2,b:7};const v=o[key]??=(trace.push('bad'),8);result={trace,v,o};`);});
test('null and primitive member references preserve RHS and failure ordering',()=>{for(const body of ["null[key]=rhs()","null[key]+=rhs()","null[key]++","'abc'.x=rhs()","delete 'abc'.x"]){same(`let trace=[];const key={[Symbol.toPrimitive](){trace.push('key');return'x';}};function rhs(){trace.push('rhs');return 1;}try{${body};}catch(e){trace.push(e.name);}result={trace};`);}});

test('module exclusion fences and unresolved globals cannot silently pass coverage',()=>{const source='// LOG BEGIN\na.x=1;\n// LOG END\nb.x=2;';const excludeRanges=markerExclusions(source,[{begin:'// LOG BEGIN',end:'// LOG END',reason:'logger self-instrumentation excluded'}]);const r=transformWrites(source,{excludeRanges});assert.equal(r.manifest.sites[0].status,'excluded');assert.equal(r.manifest.sites[1].status,'lowered');assert.throws(()=>markerExclusions(source,[{begin:'missing',end:'end',reason:'x'}]),/Missing/);assert.equal(transformWrites('unknownGlobal=2').manifest.complete,false);});

test('selected loop, parameter and catch cells require explicit initialization lowering',()=>{for(const [source,name,needle]of [['function f(x){x++;}','x','x)'],['for(let x of a){x++;}','x','x of'],['try{}catch(x){x=2;}','x','x)']]){const r=transformWrites(source,{bindings:[{name,declarationStart:source.indexOf(needle),token:'token'}]});assert.ok(!r.manifest.complete);assert.ok(r.manifest.sites.some(s=>s.reason.includes('initialization')||s.reason.includes('statement lowering')));}});
