import {spawn,execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {pathToFileURL} from 'node:url';
const CHROME=process.env.CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',sleep=ms=>new Promise(r=>setTimeout(r,ms)),active=new Set();
for(const sig of ['SIGINT','SIGTERM'])process.on(sig,()=>{for(const stop of active)stop();process.exit(sig==='SIGINT'?130:143);});
class CDP{
  constructor(url){this.ws=new WebSocket(url);this.n=0;this.wait=new Map();this.listeners=new Map();this.open=new Promise((res,rej)=>{this.ws.onopen=res;this.ws.onerror=rej;});
    this.ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=this.wait.get(m.id);if(p){this.wait.delete(m.id);m.error?p.reject(new Error(m.error.message)):p.resolve(m.result);}}else for(const f of this.listeners.get(m.method)||[])f(m.params);};
    this.ws.onclose=()=>{for(const p of this.wait.values())p.reject(new Error('Chrome closed'));this.wait.clear();};}
  send(method,params={}){const id=++this.n;this.ws.send(JSON.stringify({id,method,params}));return new Promise((resolve,reject)=>this.wait.set(id,{resolve,reject}));}
  on(method,f){if(!this.listeners.has(method))this.listeners.set(method,[]);this.listeners.get(method).push(f);}
}
async function evaluate(c,expression){const r=await c.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;}
async function launch(){const profile=fs.mkdtempSync(path.join(os.tmpdir(),'furlong-performance-'));
  const proc=spawn(CHROME,['--headless=new','--remote-debugging-port=0',`--user-data-dir=${profile}`,'--no-first-run','--no-default-browser-check','--disable-background-timer-throttling','--disable-renderer-backgrounding','--disable-backgrounding-occluded-windows',...(process.platform==='darwin'?['--use-angle=metal']:[]),'--enable-gpu','--ignore-gpu-blocklist','--window-size=1440,900','about:blank'],{stdio:['ignore','ignore','pipe']});
  let c;const stop=()=>{active.delete(stop);c?.ws.close();proc.kill('SIGKILL');fs.rmSync(profile,{recursive:true,force:true});};active.add(stop);
  try{const ws=await new Promise((res,rej)=>{let buf='';const timer=setTimeout(()=>rej(new Error('Chrome startup timeout')),30000);proc.stderr.on('data',d=>{buf+=d;const m=/DevTools listening on (ws:\/\/\S+)/.exec(buf);if(m){clearTimeout(timer);res(m[1]);}});proc.on('error',rej);proc.on('exit',code=>{clearTimeout(timer);rej(new Error('Chrome exited '+code));});});
    const list=await(await fetch(`http://127.0.0.1:${new URL(ws).port}/json/list`)).json();c=new CDP(list.find(t=>t.type==='page').webSocketDebuggerUrl);await c.open;return{c,stop};
  }catch(e){stop();throw e;}}


// Usage: node tools/inventory-trace.mjs OUT candidate|GIT_REF [YEARS] [SEED] [sea|land]
// Drives the main-thread reference simulation (foreground=1); pre-worker GIT_REFs ignore the flag.
const dir=process.argv[2],years=Number(process.argv[4]||20),seed=Number(process.argv[5]||1001),coast=process.argv[6]||'sea',source=process.argv[3]==='candidate'?fs.readFileSync('index.html','utf8'):execFileSync('git',['show',(process.argv[3]||'9753322dea76eeca750a928e9133cf38d17f211d')+':index.html'],{encoding:'utf8',maxBuffer:20e6});if(fs.existsSync(dir))throw new Error('Choose a fresh evidence directory');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'source.html'),source);fs.writeFileSync(path.join(dir,'source.sha256'),createHash('sha256').update(source).digest('hex')+'\n');
const audit=`window.__inventoryAudit={first:null,trace:[],purchases:[]};window.__inventoryScales=new WeakMap();
function inventoryCheck(phase,only){const A=window.__inventoryAudit;if(A.first)return;for(const s of (only?[only]:W?.settlements||[]))for(const k of BEASTS){let n=0;for(const x of s._owners?.values()||[]){const v=x.animals[k];for(const kind of ['animals','sale','held'])if(x[kind][k]!==undefined&&!Number.isFinite(x[kind][k])){A.first={day:day(),phase,town:s.name,good:k,invalid:String(x[kind][k]),kind,trace:A.trace.slice(),purchases:A.purchases};return;}n+=(v||0)+(x.sale[k]||0)+(x.held[k]||0);}const physical=s.stores[k]||0,scales=window.__inventoryScales.get(s)||{};window.__inventoryScales.set(s,scales);const scale=scales[k]=Math.max(scales[k]||0,Math.abs(physical),Math.abs(n)),tolerance=32*Number.EPSILON*scale*Math.max(1,s._owners?.size||0);if(n>physical+tolerance){A.first={day:day(),phase,town:s.name,good:k,physical,owned:n,scale,tolerance,last:s._herdLast?.[k],trace:A.trace.slice(),purchases:A.purchases};return;}}}
for(const name of ['purchase','offer','reconcile','herdSync','herdInit','herdProduce','winterFeed','moveStock','moveHouseholdGoods','driveOffHerds','takeHorses','yearOfFolk','tickEconomy','tickHouseholds','tickLivestock','tickMarket','tickFolk','tickMilitary']){const original=window[name];if(typeof original==='function')window[name]=function(...args){const A=window.__inventoryAudit;if(!A.first)A.trace.push({day:typeof day==='function'?day():null,name,town:args[0]?.name,physical:args[0]?.stores?.sheep,last:args[0]?._herdLast?.sheep,owned:args[0]?._owners?[...args[0]._owners.values()].reduce((n,x)=>n+(x.animals.sheep||0),0):null});if(A.trace.length>12)A.trace.shift();if(['purchase','offer','reconcile'].includes(name)&&args[0]?.name==='Rougecastel'&&(args[1]==='sheep'||name==='reconcile')){A.purchases.push({day:day(),name,qty:args[3],physical:args[0].stores.sheep,owned:[...args[0]._owners.values()].reduce((n,x)=>n+(x.animals.sheep||0),0),sale:[...args[0]._owners.values()].reduce((n,x)=>n+(x.sale.sheep||0),0)});if(A.purchases.length>30)A.purchases.shift();}const result=original.apply(this,args);if(['herdSync','herdInit','herdProduce','winterFeed','yearOfFolk','tickHouseholds'].includes(name))inventoryCheck(name,args[0]);if(name==='takeHorses')inventoryCheck(name,args[1]);if(name==='moveHouseholdGoods'){inventoryCheck(name,args[1]);inventoryCheck(name,args[2]);}return result;};}`;
const file=path.join(dir,'parent-audit.html');fs.writeFileSync(file,source.replace('boot();',audit+'\nwindow.inventoryCheck=inventoryCheck; // boot() sits in a strict block: expose the block-scoped declaration to the CDP expressions\nboot();'));
const {c,stop}=await launch(),browserErrors=[];try{await c.send('Page.enable');await c.send('Runtime.enable');c.on('Runtime.exceptionThrown',e=>browserErrors.push(e.exceptionDetails.exception?.description||e.exceptionDetails.text));await c.send('Page.addScriptToEvaluateOnNewDocument',{source:'window.requestAnimationFrame=()=>0;window.setInterval=()=>0;'});/* foreground=1: reference driver (simTick() throws under the worker) */await c.send('Page.navigate',{url:pathToFileURL(file).href+`#s=${seed}&f=${seed}&c=${coast}&y=850&foreground=1`});
let ready=false;for(let i=0;i<1200;i++){await sleep(100);if(browserErrors.length)throw new Error(browserErrors.join('\n'));if(await evaluate(c,"typeof W!=='undefined'&&!!W&&!document.getElementById('loading')").catch(()=>false)){ready=true;break;}}if(!ready)throw new Error('World boot timeout');
console.log(await evaluate(c,"({audit:window.__inventoryAudit,day:day(),loading:!!document.getElementById('loading')})"));
const gpu=await evaluate(c,"(()=>{const gl=renderer.getContext(),e=gl.getExtension('WEBGL_debug_renderer_info');return e?gl.getParameter(e.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER)})()");if(/SwiftShader|llvmpipe|Software Rasterizer/i.test(gpu))throw new Error('hardware GPU required');fs.writeFileSync(path.join(dir,'metadata.json'),JSON.stringify({seed,coast,years,gpu,source:process.argv[3]},null,2));await evaluate(c,'setSpeed(0)');for(let y=0;y<years;y++){const r=await evaluate(c,`(async()=>{for(let i=0;i<360&&!__inventoryAudit.first;i++){if(simTick()===false){await STORAGE_OUTCOMES.wait();i--;continue;}inventoryCheck('day');if(day()%30===15)await new Promise(r=>setTimeout(r,0));}return {day:day(),errors:errN,pop:W.settlements.reduce((n,s)=>n+s.pop,0),grain:W.settlements.reduce((n,s)=>n+s.stores.grain,0),audit:__inventoryAudit};})()`);fs.writeFileSync(path.join(dir,'trace.json'),JSON.stringify(r,null,2));fs.appendFileSync(path.join(dir,'annual.jsonl'),JSON.stringify(r)+'\n');console.log(JSON.stringify({year:y+1,day:r.day,first:r.audit.first,errors:r.errors,grain:r.grain,pop:r.pop}));if(browserErrors.length)throw new Error(browserErrors.join('\n'));if(r.errors||!Number.isFinite(r.grain)||!Number.isFinite(r.pop))process.exitCode=1;if(r.audit.first){process.exitCode=1;break;}}
}finally{stop();}
