import test from 'node:test';import assert from 'node:assert/strict';import {inventoryAudit} from './inventory-audit.mjs';
function fixture(){const owner={},lot={id:'lot:0:1',good:'grain',qty:1e-12,owner,location:'yard',availability:'held'},K={lots:new Map([[lot.id,lot]]),locations:new Map([['yard',{id:'yard',capacity:1,active:true}]]),byGood:new Map([['grain',new Set([lot.id])]]),byLocation:new Map([['yard',new Set([lot.id])]]),byOwner:new Map([[owner,new Set([lot.id])]]),byAvailability:new Map([['held',new Set([lot.id])]]),totals:new Map([['grain',1e-12]]),occupancy:new Map([['yard',1e-12]])};const s={name:'fixture',stores:{grain:1e-12,sheep:1},_owners:new Map([[owner,{held:{},sale:{sheep:.25},animals:{sheep:.75}}]]),storage:K};return {s,K,lot,owner};}
const audit=(f,state={})=>inventoryAudit([f.s],state,['sheep'],{grain:{volume:1}});
test('positive tiny quantity remains intact and matching',()=>{const f=fixture();assert.equal(audit(f),null);assert.equal(f.lot.qty,1e-12);});
for(const [name,edit,kind]of [
['nonfinite store',f=>f.s.stores.grain=NaN,'invalid-store'],['negative store',f=>f.s.stores.grain=-1,'invalid-store'],['past muster title overclaim',f=>f.s.stores.sheep=0,'animal-overclaim'],['NaN animal claim',f=>f.s._owners.get(f.owner).animals.sheep=NaN,'invalid-animal-claim'],['negative animal claim',f=>f.s._owners.get(f.owner).held.sheep=-1,'invalid-animal-claim'],['nonfinite lot',f=>f.lot.qty=Infinity,'invalid-lot-quantity'],['zero live lot',f=>f.lot.qty=0,'invalid-lot-quantity'],['missing forward index',f=>f.K.byOwner.clear(),'missing-index'],['stale reverse index',f=>f.K.byGood.get('grain').add('retired'),'stale-index'],['missing location',f=>f.K.locations.clear(),'missing-location'],['wrong store total',f=>f.s.stores.grain=2,'lot-store-mismatch'],['capacity breach',f=>f.K.locations.get('yard').capacity=0,'capacity-exceeded'],['occupancy cache drift',f=>f.K.occupancy.set('yard',1),'occupancy-cache-mismatch'],['total cache drift',f=>f.K.totals.set('grain',1),'total-cache-mismatch'],['incompatible good',f=>f.K.locations.get('yard').goods=['stone'],'incompatible-location'],['inactive location',f=>f.K.locations.get('yard').active=false,'incompatible-location'],
])test(name+' fails',()=>{const f=fixture();edit(f);assert.equal(audit(f).kind,kind);});
test('intended unoffered lord remainder is reported',()=>{const f=fixture(),state={};f.s.stores.sheep=2;assert.equal(audit(f,state),null);assert.equal(state.unclaimed.sheep,1);});
test('subtractive cancellation bound uses observed input without trimming residual',()=>{const f=fixture(),state={};audit(f,state);f.s.stores.sheep=0;f.s._owners.get(f.owner).animals.sheep=Number.EPSILON;f.s._owners.get(f.owner).sale.sheep=0;assert.equal(audit(f,state),null);assert.equal(f.s._owners.get(f.owner).animals.sheep,Number.EPSILON);});
test('nonfinite occupancy cache fails',()=>{const f=fixture();f.K.occupancy.set('yard',NaN);assert.equal(audit(f).kind,'occupancy-cache-mismatch');});
test('duplicate live lot identity across settlements fails',()=>{const a=fixture(),b=fixture();assert.equal(inventoryAudit([a.s,b.s],{},['sheep'],{grain:{volume:1}}).kind,'lot-identity');});
test('transit quantity is excluded from settlement stores, retained in indices and capacity',()=>{const f=fixture();f.K.locations.get('yard').transit=true;f.s.stores.grain=0;f.K.totals.set('grain',0);assert.equal(audit(f),null);assert.equal(f.lot.qty,1e-12);});
import vm from 'node:vm';
test('browser-injected oracle has no module dependencies',()=>{const standalone=vm.runInNewContext('('+inventoryAudit.toString()+')');const f=fixture();assert.equal(standalone([f.s],{},['sheep'],{grain:{volume:1}}),null);});
for(const index of ['byGood','byLocation','byOwner','byAvailability'])test(index+' forward corruption fails',()=>{const f=fixture();f.K[index].clear();assert.equal(audit(f).kind,'missing-index');});
test('migration baseline reset cannot conceal stranded animal title',()=>{const f=fixture();f.s.stores.sheep=.2;f.s._herdLast={sheep:.2};assert.equal(audit(f).kind,'animal-overclaim');});
