// Independent day-boundary matching; no reconciliation, rounding or mutation.
export function inventoryAudit(settlements,state,beasts,volumes){
  state.scales??=new WeakMap();state.checks=(state.checks||0)+1;const ids=new Set(),unclaimed={};let lots=0;
  const fault=(kind,s,details)=>({kind,town:s.name,...details});
  for(const s of settlements){let scales=state.scales.get(s);if(!scales)state.scales.set(s,scales={});
    for(const g of Object.keys(s.stores||{})){const q=s.stores[g];if(!Number.isFinite(q)||q<0)return fault('invalid-store',s,{good:g,value:String(q)});}
    // Animal claim proxies record cancellation operands even after the herd vanishes.
    // Use only this settlement/good's finite budget, plus the existing observed-scale bound.
    for(const g of beasts){let claims=0;for(const x of s._owners?.values()||[])for(const kind of ['animals','held','sale']){const q=x[kind]?.[g];if(q!==undefined){if(!Number.isFinite(q)||q<0)return fault('invalid-animal-claim',s,{good:g,accountKind:kind,value:String(q)});claims+=q;}}const physical=s.stores[g]||0;const scale=scales[g]=Math.max(scales[g]||0,physical,claims,s._herdLast?.[g]||0),observedTolerance=32*Number.EPSILON*scale*Math.max(1,s._owners?.size||0);const roundoff=s.storage?.roundoff,hasProvenance=roundoff?.has(g)===true,provenance=hasProvenance?roundoff.get(g):undefined;let recordedBudget=0;if(hasProvenance){recordedBudget=provenance?.budget;if(typeof recordedBudget!=='number'||!Number.isFinite(recordedBudget)||recordedBudget<0)return fault('invalid-animal-roundoff-budget',s,{good:g,value:String(recordedBudget)});}const tolerance=observedTolerance+recordedBudget;if(!Number.isFinite(tolerance))return fault('invalid-animal-roundoff-bound',s,{good:g});if(claims>physical+tolerance)return fault('animal-overclaim',s,{good:g,physical,claims,tolerance});unclaimed[g]=(unclaimed[g]||0)+Math.max(0,physical-claims);}
    const K=s.storage;if(!K)continue;const totals=new Map(),used=new Map(),counts=new Map();
    for(const [id,l]of K.lots){lots++;if(id!==l.id||ids.has(id))return fault('lot-identity',s,{id});ids.add(id);if(!Number.isFinite(l.qty)||!(l.qty>0))return fault('invalid-lot-quantity',s,{id,qty:String(l.qty)});const n=K.locations.get(l.location);if(!n)return fault('missing-location',s,{id,location:l.location});if(!n.active||n.goods&&!n.goods.includes(l.good))return fault('incompatible-location',s,{id,location:l.location});for(const [name,key]of [['byGood',l.good],['byLocation',l.location],['byOwner',l.owner],['byAvailability',l.availability]])if(!K[name]?.get(key)?.has(id))return fault('missing-index',s,{id,index:name});if(!n.transit)totals.set(l.good,(totals.get(l.good)||0)+l.qty);used.set(l.location,(used.get(l.location)||0)+l.qty*(volumes[l.good]?.volume??1));counts.set(l.location,(counts.get(l.location)||0)+1);}
    for(const [name,field]of [['byGood','good'],['byLocation','location'],['byOwner','owner'],['byAvailability','availability']])for(const [key,set]of K[name])for(const id of set){const l=K.lots.get(id);if(!l||l[field]!==key)return fault('stale-index',s,{id,index:name});}
    for(const [g,total]of totals){const physical=s.stores[g];const tolerance=32*Number.EPSILON*Math.max(total,Math.abs(physical||0))*Math.max(1,K.lots.size);if(!Number.isFinite(physical)||Math.abs(total-physical)>tolerance)return fault('lot-store-mismatch',s,{good:g,total,physical,tolerance});}
    for(const g of Object.keys(s.stores||{})){if(beasts.includes(g))continue;const total=totals.get(g)||0,physical=s.stores[g],tolerance=32*Number.EPSILON*Math.max(total,physical)*Math.max(1,K.lots.size);if(Math.abs(total-physical)>tolerance)return fault('store-lot-mismatch',s,{good:g,total,physical,tolerance});}
    for(const [id,n]of K.locations){const q=used.get(id)||0,tolerance=32*Number.EPSILON*Math.max(q,Math.abs(n.capacity===Infinity?0:n.capacity))*Math.max(1,counts.get(id)||0);if(n.id!==id||!(n.capacity>=0)||n.capacity!==Infinity&&!Number.isFinite(n.capacity))return fault('invalid-location',s,{id});if(q>n.capacity+tolerance)return fault('capacity-exceeded',s,{id,used:q,capacity:n.capacity,tolerance});if(K.occupancy.has(id)&&(!Number.isFinite(K.occupancy.get(id))||Math.abs(K.occupancy.get(id)-q)>tolerance))return fault('occupancy-cache-mismatch',s,{id,used:q,cached:K.occupancy.get(id)});}
    for(const [g,q]of K.totals){const total=totals.get(g)||0,tolerance=32*Number.EPSILON*Math.max(total,Math.abs(q))*Math.max(1,K.lots.size);if(!Number.isFinite(q)||Math.abs(q-total)>tolerance)return fault('total-cache-mismatch',s,{good:g,total,cached:q});}
  }
  state.unclaimed=unclaimed;state.lots=lots;return null;
}
