import test from 'node:test';
import assert from 'node:assert/strict';
import {realm} from './ownership-fixture.mjs';
import {BASELINE_TITLE_TAKE,BASELINE_CLEAR_MARKET} from './fixtures/market-baseline.mjs';
const graph=`function graph(root){const seen=new Map(),nodes=[],queue=[];function value(x){if(x===undefined)return ['undefined'];if(typeof x==='function')return ['function',x.toString()];if(typeof x==='bigint')return ['bigint',String(x)];if(typeof x==='number'&&(!Number.isFinite(x)||Object.is(x,-0)))return ['number',Object.is(x,-0)?'-0':String(x)];if(x===null||typeof x!=='object')return x;if(!seen.has(x)){seen.set(x,queue.length);queue.push(x);}return ['ref',seen.get(x)];}const r=value(root);for(let i=0;i<queue.length;i++){const x=queue[i];if(x instanceof Map)nodes[i]=['map',[...x].map(([k,v])=>[value(k),value(v)])];else if(x instanceof Set)nodes[i]=['set',[...x].map(value)];else if(ArrayBuffer.isView(x))nodes[i]=['typed',x.constructor.name,[...x].map(value)];else nodes[i]=[Array.isArray(x)?'array':'object',Reflect.ownKeys(x).map(k=>{const d=Object.getOwnPropertyDescriptor(x,k);return [k,d.enumerable,d.configurable,d.writable,'value'in d?value(d.value):['accessor',d.get?.toString(),d.set?.toString()]]})];}return JSON.stringify([r,nodes]);}`;
function pair({households=6,quantity=3}={}){return [true,false].map(old=>{const r=realm({households,grain:0,fish:0,cash:100,crown:1000});if(old)r.eval(BASELINE_TITLE_TAKE.replace('for(const l of [...K.lots.values()])','for(const l of (globalThis.fullScans++,globalThis.fullVisits+=K.lots.size,[...K.lots.values()]))')+'\n'+BASELINE_CLEAR_MARKET);r.eval(`globalThis.fullScans=0;globalThis.fullVisits=0;for(const h of H)Object.setPrototypeOf(h,Object.prototype);storageInit(s);globalThis.K=s.storage;for(const h of H){householdAccount(h);stockOf(s,h);}for(let i=0;i<3;i++){const owner=accountOwner(H[i]);const lot=K.create('grain',${quantity},owner,'yard','sale');K.annotate(lot,{tag:i,nested:{missing:undefined,negative:-0,huge:12n,array:[,undefined]}});mkt(s,'grain').set(owner,${quantity});}storageTitles(s);K.events=[];globalThis.results=[];`);if(!old)r.eval('globalThis.batches=[];const makeBatch=storageSaleBatch;storageSaleBatch=(...args)=>{const batch=makeBatch(...args);batches.push(batch);return batch;};');r.eval(graph);return r;});}
function compare(P,expr){for(const r of P)r.eval(expr);assert.equal(P[1].eval('graph(W)'),P[0].eval('graph(W)'));assert.equal(P[1].eval('graph(K.events.map(e=>storageExpandOutcome(e)))'),P[0].eval('graph(K.events.map(e=>storageExpandOutcome(e)))'));assert.deepEqual(Array.from(P[1].C.results),Array.from(P[0].C.results));}
test('one clearing reuses insertion-ordered sale buckets with exact custody, wallets and rounding',()=>{const P=pair();compare(P,"results=clearMarket(s,'grain',[[H[0],1],[H[3],2.125],[H[4],1.375],[H[5],2.5]],1);storageTitles(s,'grain')");const batch=P[1].C.batches[0];assert.ok(batch);assert.equal(batch.scans,1);assert.equal(batch.fallbacks,0);assert.equal(batch.calls,4);assert.equal(batch.visits,3);assert.equal(P[0].C.fullScans,4);assert.ok(P[0].C.fullVisits>batch.visits);});
test('multiple goods, partial and tiny quantities retain complete events and model state',()=>{for(const q of [1e-13,0.125,3]){const P=pair({quantity:q});compare(P,`results=clearMarket(s,'grain',[[H[0],${q/2}],[H[3],${q*1.7}],[H[4],${q*2.3}]],1);for(let i=0;i<2;i++){const owner=accountOwner(H[i]);K.create('fish',2,owner,'yard','sale');mkt(s,'fish').set(owner,2);}results.push(...clearMarket(s,'fish',[[H[3],1],[H[5],2]],2));storageTitles(s);`);assert.equal(P[1].C.batches.filter(Boolean).length,2);}});
test('pending purchases and deliberately different owner-index order retain lot insertion order',()=>{const P=pair();compare(P,"const lot=[...K.lots.values()][0];K.annotate(lot,{pendingPurchase:false});const ids=K.byOwner.get(lot.owner);ids.delete(lot.id);ids.add(lot.id);results=clearMarket(s,'grain',[[H[3],1.5],[H[4],2.5]],1);storageTitles(s)");assert.ok(P[1].C.batches[0]);});
test('custom ledger mutation and reentrant observation conservatively retain baseline scanning',()=>{for(const custom of ["const originalTransfer=K.transfer;K.transfer=function(...args){return originalTransfer.apply(this,args)}", "globalThis.FURLONG_STORAGE_AUDIT_OBSERVER=e=>{}"]){const P=pair();compare(P,custom+";results=clearMarket(s,'grain',[[H[3],1],[H[4],1]],1);storageTitles(s)");assert.equal(P[1].C.batches[0],null);}});
test('new actor and replaced household projection use baseline fallback',()=>{const P=pair();compare(P,"const getter=Object.getOwnPropertyDescriptor(H[3],'w').get;Object.defineProperty(H[3],'w',{configurable:true,enumerable:true,get(){return getter.call(this)},set(v){householdAccount(this).assets.w=v}});results=clearMarket(s,'grain',[[H[3],1]],1)");assert.equal(P[1].C.batches[0],null);const Q=pair();compare(Q,"const fresh={id:99,gn:'new',si:0,w:100};s.folk.push(fresh);results=clearMarket(s,'grain',[[fresh,1]],1)");assert.equal(Q[1].C.batches[0],null);});
test('explicit read-only audit observes optimized stream without changing state',()=>{const P=pair();compare(P,"globalThis.FURLONG_MARKET_READ_ONLY_AUDIT=true;globalThis.seen=[];FURLONG_STORAGE_AUDIT_OBSERVER=e=>seen.push(e);results=clearMarket(s,'grain',[[H[3],1],[H[4],1]],1)");assert.ok(P[1].C.batches[0]);assert.equal(P[1].C.batches[0].fallbacks,0);assert.equal(P[1].eval('graph(seen)'),P[0].eval('graph(seen)'));});
test('revision changes invalidate a live operation bucket before sale-list expansion',()=>{const P=pair();compare(P,"const batch=typeof storageSaleBatch==='function'?storageSaleBatch(s,'grain',[[H[3],1]]):null;storageTitleTake(s,H[0],H[3],'grain',.5,'held',batch);const owner=accountOwner(H[0]),lot=K.create('grain',.25,owner,'yard','sale');K.annotate(lot,{late:true});mkt(s,'grain').set(owner,(mkt(s,'grain').get(owner)||0)+.25);results=[...storageTitleTake(s,H[0],H[4],'grain',2.6,'held',batch)].map(l=>l.qty);globalThis.directBatch=batch;");assert.equal(P[1].C.directBatch.fallbacks,1);assert.equal(P[1].C.directBatch.invalid,true);});
test('custom method getters are not invoked early by batching eligibility',()=>{const P=pair();compare(P,"globalThis.lookups=0;const originalTransfer=K.transfer;Object.defineProperty(K,'transfer',{configurable:true,get(){lookups++;return originalTransfer}});results=clearMarket(s,'grain',[[H[3],1]],1)");assert.equal(P[1].C.batches[0],null);assert.equal(P[1].C.lookups,P[0].C.lookups);});
test('an undeclared callback adding sale lots mid-transfer retains original per-call snapshots',()=>{const P=pair();compare(P,"globalThis.added=false;globalThis.storageOutcome=e=>{K.events.push(e);if(!added&&e.cause==='title-transfer'){added=true;const owner=accountOwner(H[1]);K.create('grain',.25,owner,'yard','sale');mkt(s,'grain').set(owner,(mkt(s,'grain').get(owner)||0)+.25);}};results=clearMarket(s,'grain',[[H[3],1],[H[4],1]],1)");assert.equal(P[1].C.batches[0],null);});
test('many buyers and unrelated lots require one broad scan, with unchanged exact model',()=>{const P=pair({households:35});compare(P,"for(let i=0;i<40;i++){const lot=K.create('fish',.125,null,'yard','unassigned');K.annotate(lot,{unrelated:i});}results=clearMarket(s,'grain',Array.from(H).slice(3).map(h=>[h,.2]),1)");const batch=P[1].C.batches[0];assert.ok(batch);assert.equal(batch.scans,1);assert.equal(batch.visits,43);assert.equal(batch.fallbacks,0);assert.equal(P[0].C.fullScans,3);assert.ok(P[0].C.fullVisits>=129);});
test('empty orders avoid building a bucket and retain baseline state',()=>{const P=pair();compare(P,"results=clearMarket(s,'grain',[],1)");assert.equal(P[1].C.batches[0],null);});
test('custom title-event and assertion hooks expanding sale lists force original snapshots',()=>{for(const hook of ["const originalTitleEvent=storageTitleEvent;storageTitleEvent=function(ledger,e){originalTitleEvent(ledger,e);if(!injected&&e.cause==='title-transfer')inject();};", "globalThis.storageOutcomeAssert=function(){if(!injected&&K.events.length)inject();};"]){const P=pair();compare(P,"globalThis.injected=false;function inject(){injected=true;const owner=accountOwner(H[1]);const lot=K.create('grain',1,owner,'yard','sale');K.annotate(lot,{injected:true});mkt(s,'grain').set(owner,(mkt(s,'grain').get(owner)||0)+1);}"+hook+"const batch=typeof storageSaleBatch==='function'?storageSaleBatch(s,'grain',[[H[3],1]]):null;storageTitleTake(s,H[0],H[3],'grain',1,'held',batch);results=storageTitleTake(s,H[1],H[3],'grain',4,'held',batch).map(l=>l.qty);globalThis.directBatch=batch;");assert.equal(P[1].C.directBatch,null);}});
test('custom roundoff record getters and native collection methods retain fallback',()=>{for(const custom of ["const record=K.roundoff.get('grain'),budget=record.budget;Object.defineProperty(record,'budget',{enumerable:true,configurable:true,get(){return budget},set(v){}});", "const get=K.byOwner.get;K.byOwner.get=function(...args){return get.apply(this,args)};"]){const P=pair();compare(P,custom+"results=clearMarket(s,'grain',[[H[3],1]],1)");assert.equal(P[1].C.batches[0],null);}});
