import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {execFileSync} from 'node:child_process';
const source=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const baseline=execFileSync('git',['show','24be535:index.html'],{encoding:'utf8',maxBuffer:20e6});
function fn(s,n){return s.match(new RegExp('^function '+n+'\\b[\\s\\S]*?(?=^function |^const |$(?![\\s\\S]))','m'))[0];}
function realm(old=false){const history=[],draws=[];let state=0xabcdef01;
const r=vm.createContext({console,history,draws,clamp:(v,a,b)=>Math.max(a,Math.min(b,v)),chance:(stream,p)=>{state^=state<<13;state^=state>>>17;state^=state<<5;const u=(state>>>0)/4294967296;draws.push([stream,p,u]);return u<p;},pick:(stream,x)=>x[0],vary:(key,x)=>x[0](),nameUse(){},endow:n=>{},deriveTraits:()=>[],twoTraits:()=>[],personName:()=> 'Newborn',emit:(...args)=>history.push(args),houseOf:n=>r.run('W').houses[n.house],fullTitle:n=>n.name,checkWarSpark(){},sheltered:()=>0,mythMult:()=>1,ordinal:x=>String(x),educate(){},lordsNaturalChild(){},GV:0,GF:4,MOD:{fert:1,aggr:0,tax:12}});
vm.runInContext("'use strict';let W={clock:{day:1},notables:[],legitimacy:70,houses:[{name:'Royal',seat:0}],settlements:[{name:'Town',pos:{x:0,z:0},pop:100,unrest:0,kind:'capital'}],treasury:1000};W.capital=W.settlements[0];function day(){return W.clock.day}function ageOf(n){return Math.floor((day()-n.birthDay)/360)}",r);
const cast=(old?baseline:source);const start=old?cast.indexOf('let NID=1;'):cast.indexOf('const NOTABLE_INDEXES=');
vm.runInContext("'use strict';"+cast.slice(start,cast.indexOf('\nconst TRAITS=',start))+fn(cast,'notableById')+fn(cast,'killNotable')+fn(cast,'tickPolitics'),r);
if(!old)vm.runInContext(fn(cast,'publicOrderMen'),r);
if(!old)vm.runInContext('notableIndexRebuild()',r);
r.run=s=>vm.runInContext(s,r);r.world=()=>r.run('W');return r;}
function pair(){return[realm(true),realm()];}
function state(r){return structuredClone(r.run('({world:W,history,draws})'));}
function equal(P){assert.deepEqual(state(P[1]),state(P[0]));}
const cast="mkNotable({name:'Mother',sex:'f',age:23,birthDay:-8280,spouse:2,role:'courtier',traits:['fertile']});mkNotable({name:'Father',sex:'m',age:25,birthDay:-9000,spouse:1,role:'courtier',traits:['bold']});mkNotable({name:'Sibling',sex:'f',age:20,birthDay:-7200,role:'scion',traits:['bold'],house:0});";
test('production politics preserves exact RNG/results/history across birth and marriage schedules',()=>{const P=pair();for(const r of P){r.run(cast);r.run("for(let d=1;d<120;d++){W.clock.day=d;tickPolitics()}");}equal(P);});
test('fixed living cast and huge complete dead archive have bounded active visits and ID lookup',()=>{const r=realm();r.run("for(let i=0;i<30000;i++)mkNotable({name:'Archive',alive:false,age:40,traits:['bold']});"+cast);assert.equal(r.run('W.notables.length'),30003);assert.equal(r.run('[...livingNotables()].length'),3);r.run("let archiveReads=0;const full=W.notables;W.notables=new Proxy(full,{get(t,k,a){if(typeof k==='string'&&/^\\d+$/.test(k))archiveReads++;return Reflect.get(t,k,a)}});const C=NOTABLE_INDEXES.get(W);C.archive=W.notables;");r.run('tickPolitics();notableById(20000);notableById(999999)');assert.equal(r.run('archiveReads'),0);assert.equal(r.run('notableById(20000).id'),20000);});
test('iterator sees appended newborns and death of current/next never skips following',()=>{const r=realm();r.run(cast);const seen=r.run("(()=>{const seen=[];for(const n of livingNotables()){seen.push(n.id);if(n.id===1){notableSetAlive(n,false);notableSetAlive(W.notables[1],false);mkNotable({name:'Baby',age:0,traits:['bold']})}}return seen})()");assert.deepEqual([...seen],[1,3,4]);assert.equal(r.run('W.notables.length'),4);});
test('resurrection keeps archive insertion order and does not revisit earlier ordinals',()=>{const r=realm();r.run(cast);r.run('notableSetAlive(W.notables[0],false)');assert.deepEqual([...r.run('[...livingNotables()].map(n=>n.id)')],[2,3]);r.run('notableSetAlive(W.notables[0],true)');assert.deepEqual([...r.run('[...livingNotables()].map(n=>n.id)')],[1,2,3]);assert.deepEqual([...r.run("(()=>{const seen=[];for(const n of livingNotables()){seen.push(n.id);if(n.id===2){notableSetAlive(W.notables[0],false);notableSetAlive(W.notables[0],true)}}return seen})()")],[1,2,3]);});
test('explicit adoption rebuilds first-ID lookup, NaN strict matching and pending historical cleanup',()=>{const r=realm();r.run("W.notables=[{id:5,alive:false,_just:true},{id:5,alive:true},{id:NaN,alive:true}];notableIndexRebuild()");assert.equal(r.run('notableById(5)===W.notables[0]'),true);assert.equal(r.run('notableById(NaN)'),undefined);r.run('notableMarriageCleanup([])');assert.equal(r.run("Object.hasOwn(W.notables[0],'_just')"),false);});
test('world/reload replacement requires explicit adoption; unknown contract remains visible fallback',()=>{const r=realm();r.run(cast);r.run("W={notables:[{id:90,alive:true},{id:91,alive:false}]}");assert.equal(r.run('notableIndex().supported'),false);assert.equal(r.run('notableById(90).id'),90);r.run('notableIndexRebuild()');assert.equal(r.run('notableIndex().supported'),true);assert.deepEqual([...r.run('[...livingNotables()].map(n=>n.id)')],[90]);r.run('W.notables.push({id:92,alive:true})');assert.equal(r.run('notableIndex().supported'),false);});
test('unsupported accessors fall back and native index adds no fields to the historical model',()=>{const r=realm();r.run("W.notables=[{id:1,get alive(){return true}}];notableIndexRebuild()");assert.equal(r.run('notableIndex().supported'),false);assert.equal(r.run('notableById(1).id'),1);const ordinary=realm();ordinary.run(cast);assert.deepEqual([...ordinary.run('Object.keys(W)').filter(k=>/index|living/i.test(k))],[]);});
test('adoption/house transitions never change living order or first-ID historical lookup',()=>{const r=realm();r.run(cast);r.run("W.notables[0].house=2;W.notables[0].role='head';W.notables[1].house=0;W.notables[1].oldBlood=1");assert.deepEqual([...r.run('[...livingNotables()].map(n=>n.id)')],[1,2,3]);assert.equal(r.run('notableById(2)===W.notables[1]'),true);});
test('actual death transitions preserve spouse updates, dead archive lookup and next birthday visits',()=>{const P=pair();for(const r of P){r.run(cast);r.run("killNotable(W.notables[0],'in testing',true);W.clock.day=360;tickPolitics()");}equal(P);assert.equal(P[1].run('notableById(1).alive'),false);assert.deepEqual([...P[1].run('[...livingNotables()].map(n=>n.id)')],[2,3]);});
test('unknown accessor worlds retain original alive read counts during politics',()=>{const P=pair();for(const r of P)r.run("let aliveReads=0;W.notables=[{id:1,get alive(){aliveReads++;return false}}];tickPolitics()");assert.equal(P[1].run('aliveReads'),P[0].run('aliveReads'));});
test('forced births and marriage exercise appended cast and paired cleanup with exact draw order',()=>{const P=pair();for(const r of P){r.run(cast);r.run("W.houses.push({name:'Other',seat:0,exiled:true,loyalty:70});mkNotable({name:'Suitor',sex:'m',age:22,birthDay:-7920,house:1,role:'scion',traits:['bold']});chance=(stream,p)=>{draws.push([stream,p]);return true};W.clock.day=9;tickPolitics();W.clock.day=37;tickPolitics()");}equal(P);assert.equal(P[1].run('W.notables.length'),5);assert.equal(P[1].run("W.notables.some(n=>Object.hasOwn(n,'_just'))"),false);assert.equal(P[1].run('W.notables[2].spouse'),4);});
import * as acorn from './vendor/acorn/acorn.mjs';
test('source mutation manifest rejects new alive, marriage-cleanup or archive writers',()=>{const program=source.slice(source.indexOf("'use strict';"),source.indexOf('</script>',source.indexOf("'use strict';"))),ast=acorn.parse(program,{ecmaVersion:'latest'}),writes=[],ids=[];
function key(n){return n?.type==='MemberExpression'?(n.computed?n.property.type==='Literal'?n.property.value:null:n.property.name):null;}
function visit(n){if(!n?.type)return;if(['AssignmentExpression','UpdateExpression'].includes(n.type)&&key(n.left||n.argument)==='id')ids.push(program.slice(n.start,n.end));if((n.type==='AssignmentExpression'||n.type==='UpdateExpression'||n.type==='UnaryExpression'&&n.operator==='delete')&&['alive','_just','notables'].includes(key(n.left||n.argument)))writes.push(program.slice(n.start,n.end));if(n.type==='CallExpression'&&key(n.callee?.object)==='notables'&&['push','pop','shift','unshift','splice','sort','reverse','fill','copyWithin'].includes(key(n.callee)))writes.push(program.slice(n.start,n.end));for(const v of Object.values(n))if(Array.isArray(v))v.forEach(visit);else if(v?.type)visit(v);}
visit(ast);assert.deepEqual(writes,['n.alive=alive','delete n._just','delete n._just','W.notables.push(n)','a._just=b._just=true','b._just=true']);
assert.match(source.slice(source.indexOf('async function generateWorld('),source.indexOf("await progress('Raising")),/notableIndexRebuild\(\)/);assert.match(fn(source,'killNotable'),/notableSetAlive\(n,false\)/);
// These two assignments set IDs on newly-created event DOM nodes; retain them
// as exact allowlisted sites alongside the existing non-notable ID writers.
// The world save numbers the shapes (key lists) it writes: t.id is a shape's place in its table, not a notable's.
assert.deepEqual(ids,["state.id=q.storageProjectId","el.id='terrlegend'","el.id='terrlegend'","el.id='terrlegend'","events.id='eventpanel'","bubble.id='eventbubble'","h.id=next.id+'-title'","el.id='mapview'","this.id=id","o.id=auto?'auto:'+o.hash:'s'+Date.now()","t.id=shapes.length","el.id='advchat'"]);
assert.equal((source.match(/W\.notables\s*=/g)||[]).length,0);
});
