// Stable accounts, owner inventories, customary inheritance and lifecycle conservation.
import test from 'node:test';
import assert from 'node:assert/strict';
import {realm,near} from './ownership-fixture.mjs';
const init=r=>r.eval('ownershipTick()');
const held=(r,i,g)=>r.eval(`pantry(s,H[${i}]).${g}||0`);
const total=(r,g)=>r.eval(`heldTotal(s,'${g}')+[...mkt(s,'${g}').values()].reduce((a,b)=>a+b,0)`);
function family({age=850,cult='anglo'}={}){const r=realm({cash:0,households:4});r.s.cult=cult;
  r.eval(`AD=()=>${age};H[0].sx='m';H[0].b=-40;H[1].sx='f';H[1].b=-38;H[2].sx='m';H[2].b=-12;H[2].age=12;H[3].sx='f';H[3].b=-8;H[3].age=8;H[0].sp=H[1];H[1].sp=H[0];H[2].ma=H[1];H[2].pa=H[0];H[3].ma=H[1];H[3].pa=H[0];H[0].kids=[H[2],H[3]];H[1].kids=[H[2],H[3]];H[0].w=90;ownershipTick()`);return r;}
function death(r,i=0){r.eval(`inherit(H[${i}]);H[${i}].dead=true`);}

test('one stable account, one purse, for a couple and dependent children',()=>{const r=family();near(r.coins(),90);assert.equal(r.eval('new Set(H.map(p=>householdAccount(p))).size'),1);near(r.H[1].w,0);near(r.eval('means(H[1])'),90);});
test('a non-head death cannot distribute the whole household estate',()=>{const r=family();r.eval("addHeld(s,H[0],'grain',8)");death(r,2);near(r.coins(),90);near(held(r,0,'grain'),8);assert.equal(r.eval('householdAccount(H[0]).head'),r.H[0]);});
test('widow succeeds as head without losing account identity or grain',()=>{const r=family(),id=r.eval('householdAccount(H[0]).id');r.eval("addHeld(s,H[0],'grain',8);offer(s,'tools',H[0],6,4)");death(r);assert.equal(r.eval('householdAccount(H[1]).id'),id);assert.equal(r.eval('householdHead(H[2])'),r.H[1]);near(r.coins(),90);near(held(r,1,'grain'),8);near(r.eval("mkt(s,'tools').get(H[1])"),6);near(r.eval("rsv(s,'tools').get(H[1])"),4);});
test('hungry poor households cannot consume the rich household crock',()=>{const r=realm({households:2,cash:0,grain:10,fish:0});init(r);r.eval("H[0]._debt=foodYr()*.25;H[1]._debt=foodYr()*.25;mkt(s,'grain').set('crown',0);addHeld(s,H[0],'grain',10)");r.run();near(r.s.hunger,.5);near(r.eval('householdAccount(H[0]).hunger'),0);near(r.eval('householdAccount(H[1]).hunger'),1);near(held(r,0,'grain'),9.25);});
test('market quantities reference the owned inventory, including reservation prices',()=>{const r=realm();init(r);r.eval("offer(s,'tools',H[0],8,4);stockOf(s,H[0]).sale.tools=5");near(r.eval("mkt(s,'tools').get(H[0])"),5);r.eval("mkt(s,'tools').set(H[0],2)");near(r.eval('stockOf(s,H[0]).sale.tools'),2);});
test('purchases stay in the buyer inventory',()=>{const r=realm({households:2});init(r);r.eval("purchase(s,'grain',H[0],3);addHeld(s,H[0],'grain',purchase.got)");near(held(r,0,'grain'),3);near(held(r,1,'grain'),0);});
test('relief targets need and remains owned after allocation',()=>{const r=realm({households:2});init(r);r.eval("householdAccount(H[1]).hunger=1;giveFood(s,'grain',12)");assert.ok(held(r,1,'grain')>held(r,0,'grain'));near(r.eval("heldTotal(s,'grain')"),12);});
test('community population is the sum of household cohorts',()=>{const r=realm({households:2});init(r);r.eval('householdAccount(H[0]).population.set(s,25)');near(r.s.pop,100);r.s.pop=200;near(r.eval('householdAccount(H[0]).population.get(s)'),50);});
test('demography uses each household hunger rather than applying town hunger to all',()=>{const r=realm({households:2,cash:0,grain:10,fish:0});init(r);r.eval("H[0]._debt=foodYr()*.25;H[1]._debt=foodYr()*.25;mkt(s,'grain').set('crown',0);addHeld(s,H[0],'grain',10);MOD.mort=1");r.run();assert.ok(r.eval('householdAccount(H[0]).population.get(s)>householdAccount(H[1]).population.get(s)'));});
test('children setting up house receive a portion without emptying the parents purse',()=>{const r=family();r.eval('householdPortion(H[2],.15)');near(r.H[0].w,76.5);near(r.H[2].w,13.5);assert.notEqual(r.eval('householdAccount(H[2]).id'),r.eval('householdAccount(H[0]).id'));near(r.coins(),90);});
test('wedding dependent children cannot confiscate either parental purse',()=>{const r=realm({households:4,cash:0});r.eval("H[0].sx='f';H[1].sx='m';H[1].ma=H[0];H[1].age=20;H[2].sx='f';H[3].sx='f';H[3].ma=H[2];H[3].age=20;H[0].w=100;H[2].w=200;ownershipTick();marryHouseholds(H[1],H[3])");near(r.H[0].w,85);near(r.H[2].w,170);near(r.H[1].w,45);near(r.coins(),300);});
test('creditors are paid before chattels are divided',()=>{const r=family();r.eval("W.treasury=100;borrow(s,H[0],10)");near(r.H[0]._debt,10);death(r);near(r.W.treasury,100);near(r.H[1].w,90);near(r.H[1]._debt,0);});
test('English late-twelfth-century thirds protect widow, children and soul share',()=>{const r=family({age:1215});death(r);near(r.H[1].w,60);near(r.W.treasury,30);near(r.coins(),90);});
test('earlier English kin division does not impose later thirds',()=>{const r=family({age:1000});death(r);near(r.H[1].w,90);near(r.W.treasury,0);});
test('movables divide among children, regardless of eldest-son land custom',()=>{const r=realm({households:3,cash:0});r.eval("H[0].kids=[H[1],H[2]];H[1].pa=H[0];H[2].pa=H[0];H[1].own=H[2].own=true;H[0].w=80;ownershipTick()");death(r);near(r.H[1].w,40);near(r.H[2].w,40);near(r.coins(),80);});
test('minor sons inherit land and the widow retains dower use',()=>{const r=family();r.s.furl=[{k:0,own:1,wk:1,ten:'free'}];r.s.buildings=[{ownerId:1}];r.eval('bindPropertyRights(s)');death(r);assert.equal(r.s.furl[0].own,3);assert.equal(r.s.furl[0].dower,2);near(r.s.furl[0].dowerFraction,1/3);assert.equal(r.s.buildings[0].ownerId,3);assert.equal(r.s.furl[0].title.own.owner,r.eval('householdAccount(H[2])'));});
test('existing partible custom divides strips among sons including minors',()=>{const r=realm({households:3,cash:0});r.s.cult='celtic';r.eval("H[0].kids=[H[1],H[2]];H[1].pa=H[0];H[2].pa=H[0];H[1].sx=H[2].sx='m';H[1].age=10;H[2].age=8;H[1].b=-10;H[2].b=-8;ownershipTick()");r.s.furl=[{k:0,own:1,wk:1},{k:1,own:1,wk:1}];death(r);assert.deepEqual(r.s.furl.map(f=>f.own),[2,3]);});
test('local youngest-heir custom overrides the cultural default',()=>{const r=realm({households:3,cash:0});r.s.custom={land:'youngest'};r.eval("H[0].kids=[H[1],H[2]];H[1].pa=H[0];H[2].pa=H[0];H[1].b=-20;H[2].b=-10;H[1].sx=H[2].sx='m';ownershipTick()");r.s.furl=[{own:1,wk:1}];death(r);assert.equal(r.s.furl[0].own,3);});
test('remote children and siblings precede escheat',()=>{const r=realm({households:2,cash:0});r.eval("H[0].ma={kids:H,dead:true};H[1].ma=H[0].ma;H[0].w=50;ownershipTick();s.folk.splice(1,1);H[1].si=1");death(r);near(r.H[1].w,50);near(r.W.treasury,0);});
test('insolvent estates repay chattels in kind and do not impose debt on minor heirs',()=>{const r=family();r.eval("H[0].w=0;H[0]._debt=20;H[0]._owe=[['crown',20]];H[0].herd={cattle:1};s.stores.cattle=1;addHeld(s,H[0],'tools',8)");const before=total(r,'tools');death(r);near(total(r,'tools'),before);near(r.H[1]._debt,0);assert.ok(r.eval('stockOf(s,"crown").held.tools>0'));near(r.coins(),0);});
test('late debts owed to an extinct household reach its heirs',()=>{const r=realm({households:3,cash:0});r.eval("H[0].kids=[H[1],H[2]];H[1].pa=H[0];H[2].pa=H[0];H[1].own=H[2].own=true;ownershipTick()");death(r);r.eval('acct(H[0],10)');near(r.H[1].w,5);near(r.H[2].w,5);});
test('customary heriot takes one best beast, preserving the rest',()=>{const r=family();r.s.furl=[{own:1,wk:1,ten:'villein'}];r.eval('s.px.horses=25;s.px.cattle=12;H[0].herd={horses:2,cattle:3};s.stores.horses=2;s.stores.cattle=3');death(r);near(r.H[1].herd.horses,1);near(r.H[1].herd.cattle,3);});
test('goods moved between places retain their owner rather than becoming communal food',()=>{const r=realm({households:2,grain:10});init(r);r.eval("addHeld(s,H[0],'grain',4);mkt(s,'grain').set('crown',6);W.settlements.push({...s,pop:20,folk:[],stores:{grain:0,fish:0},_lard:{grain:0,fish:0},_owners:new Map(),_populationReady:false,_ownershipReady:false,households:[],_householdsD:-1});moveStock(s,W.settlements[1],'grain',5)");near(held(r,0,'grain'),2);near(r.eval("pantry(W.settlements[1],H[0]).grain"),2);near(r.s.stores.grain,5);near(r.W.settlements[1].stores.grain,5);});

test('a whole household migration carries its purchased goods and beasts with its identity',()=>{const r=family();r.eval("addHeld(s,H[0],'grain',6);H[0].herd={cattle:2};s.stores.cattle=2;W.settlements.push({name:'destination',stores:{grain:0,fish:0,cattle:0},folk:[],pop:10,buildings:[],furl:[]});for(const p of H)p.si=1;W.settlements[1].folk=H.slice();arriveHousehold(H[0],0,1)");near(r.eval('pantry(W.settlements[1],H[0]).grain'),6);near(held(r,0,'grain'),0);near(r.s.stores.cattle,0);near(r.W.settlements[1].stores.cattle,2);});
test('individual departure leaves the remaining family its account and fair share',()=>{const r=family();r.eval("addHeld(s,H[0],'grain',8);departHousehold(H[2],0,1,'migrant')");near(r.H[0].w,67.5);near(r.H[2].w,22.5);near(held(r,0,'grain'),6);near(held(r,2,'grain'),2);near(r.coins(),90);});
test('an inherited holding follows its beneficiary when they establish their own household',()=>{const r=family();r.s.furl=[{k:0,own:1,wk:1,ten:'free'}];r.eval('bindPropertyRights(s)');death(r);r.eval('householdPortion(H[2])');assert.equal(r.s.furl[0].title.own.owner,r.eval('householdAccount(H[2])'));});
test('widow dower is a lifetime share of the family crop, not the lord tithe',()=>{const r=realm({households:2,cash:0});init(r);r.eval("offerLand(s,'grain',H[0],12,{dower:H[1].id,dowerFraction:1/3})");near(r.eval("mkt(s,'grain').get(H[0])"),8);near(r.eval("mkt(s,'grain').get(H[1])"),4);});
test('primogeniture represents a deceased eldest son through his minor child',()=>{const r=realm({households:4,cash:0});r.eval("H[0].kids=[H[1],H[2]];H[1].dead=true;H[1].b=-20;H[1].sx='m';H[1].pa=H[0];H[1].kids=[H[3]];H[2].b=-15;H[2].sx='m';H[2].pa=H[0];H[3].pa=H[1];H[3].b=-5;H[3].sx='m';H[3].age=5;ownershipTick()");r.s.furl=[{own:1,wk:1}];death(r);assert.equal(r.s.furl[0].own,4);});
test('a childless deceased branch does not inherit from its dying parent',()=>{const r=realm({households:3,cash:0});r.eval("H[0].kids=[H[1],H[2]];H[1].dead=true;H[1].b=-20;H[1].sx='m';H[1].pa=H[0];H[2].b=-15;H[2].sx='m';H[2].pa=H[0];ownershipTick()");r.s.furl=[{own:1,wk:1}];death(r);assert.equal(r.s.furl[0].own,3);});
test('natural children keep maternal land rights and follow paternal local custom',()=>{const r=realm({households:3,cash:0});r.eval("H[0].kids=[H[1],H[2]];H[1].pa=H[0];H[1].b=-20;H[1].bast=true;H[1].sx='m';H[2].pa=H[0];H[2].b=-15;H[2].sx='m';ownershipTick()");assert.equal(r.eval('landHeirs(H[0],s)[0]'),r.H[2]);r.s.cult='celtic';assert.equal(r.eval('landHeirs(H[0],s)[0]'),r.H[1]);});
test('a dead lender estate divides later repayments even if the widow account survives',()=>{const r=family({age:1215});death(r);r.eval('acct(H[0],9)');near(r.H[1].w,66);near(r.W.treasury,33);});

test('milk and fleece belong to the byre owner and are produced only once',()=>{const r=realm({households:2,grain:0,fish:0});init(r);r.eval("H[0].herd={cattle:2,sheep:10};s.stores.cattle=2;s.stores.sheep=10;s.stores.swine=0;s.stores.wool=0;s.stores.cloth=0;herdProduce(s)");near(held(r,0,'grain'),.28);near(held(r,1,'grain'),0);near(r.s.stores.grain,.28);near(r.eval("stockOf(s,H[0]).sale.wool"),.1104);near(held(r,0,'cloth'),.0048);});
test('winter fodder cannot be taken from a neighbour haystack',()=>{const r=realm({households:2});init(r);r.eval("H[0].herd={cattle:2};H[1].herd={cattle:2};s.stores.cattle=4;s.stores.sheep=s.stores.horses=s.stores.swine=0;s.stores.hay=2;addHeld(s,H[0],'hay',2);winterFeed(s,false)");near(r.H[0].herd.cattle,2);near(r.H[1].herd.cattle,1.8);near(held(r,0,'hay'),1.3);near(r.s.stores.cattle,3.8);});
test('animals inherited by a remote household retain their location and ownership',()=>{const r=realm({households:2,cash:0});r.eval("H[0].kids=[H[1]];H[1].pa=H[0];H[1].own=true;ownershipTick();H[0].herd={cattle:2};s.stores.cattle=2;W.settlements.push({name:'remote',stores:{grain:0,fish:0,cattle:0},folk:[],pop:10,buildings:[]});H[1].si=1");death(r);near(r.eval('stockOf(s,H[1]).animals.cattle'),2);near(r.s.stores.cattle,2);near(r.W.settlements[1].stores.cattle,0);});
test('the widow retains the household home when its head dies',()=>{const r=family();r.eval("H[0].bh={id:'roof'}");death(r);assert.equal(r.H[1].bh.id,'roof');});

test('daily spoilage removes the same fraction from each owner and pending output',()=>{const r=realm({households:2,grain:10});init(r);r.eval("mkt(s,'grain').clear();addHeld(s,H[0],'grain',4);offer(s,'grain',H[1],4);s._made.grain=2;spoilOwned(s,'grain',.1)");near(r.s.stores.grain,9);near(held(r,0,'grain'),3.6);near(r.eval("mkt(s,'grain').get(H[1])"),3.6);near(r.s._made.grain,1.8);near(total(r,'grain')+r.s._made.grain,9);});
test('fresh food is allocated to its producer before surplus reconciliation',()=>{const r=realm({households:2,cash:0,grain:0,fish:4});r.eval("mkt(s,'fish').clear();H[0].tr='fisher';s._made.fish=4;H[1]._debt=foodYr()*.25");r.run();near(r.eval("mkt(s,'fish').get('crown')||0"),0);assert.ok(r.eval("mkt(s,'fish').get(H[0])>0"));near(r.eval('householdAccount(H[0]).hunger'),0);near(r.eval('householdAccount(H[1]).hunger'),1);});

test('a repeated death notification cannot distribute an estate twice',()=>{const r=family();r.eval('dropPerson(H[0]);dropPerson(H[0])');near(r.H[1].w,90);near(r.coins(),90);});
test('the parish removes a stale corpse before schooling or marriage',()=>{const r=realm();r.eval("H[0].dead=true;H[0].sk=undefined;houseFolk=()=>{};yearOfFolk(s,0)");assert.equal(r.s.folk.length,0);});
test('a bride household move cannot put a levied child on both army and parish rolls',()=>{const r=realm({households:3,cash:0});r.eval("H[0].sx='f';H[0].age=25;H[0].fam=1;H[1].sx='m';H[1].age=18;H[1].ma=H[0];H[2].sx='m';H[2].age=27;H[2].fam=2;H[2].si=1;W.settlements.push({name:'far',folk:[H[2]],pop:10,buildings:[],stores:{grain:0,fish:0}});s.folk=[H[0]];W.armies=[{men:[H[1]]}];householdAccount(H[1]);householdAccount(H[2]);let choices=[1,0];frand=()=>choices.length?choices.shift():0;educate=()=>{};trait=()=>0;attraction=()=>1;standing=()=>0;houseFolk=()=>{};nearestOther=()=>W.settlements[1];W.travellers=[];journey=(p,from,to)=>{W.travellers.push({p,from,to});p.si=-1;};yearOfFolk(s,0)");assert.equal(r.W.travellers.length,1);assert.equal(r.W.travellers[0].p,r.H[0]);assert.equal(r.W.armies[0].men[0],r.H[1]);});

test('a wedding invalidates the same-day household census',()=>{const r=realm({households:2,cash:0});init(r);assert.equal(r.s.households.length,2);r.eval('marryHouseholds(H[0],H[1]);householdsOf(s)');assert.equal(r.s.households.length,1);near(r.s.pop,150);});
test('property assigned to a newly registered household resolves beyond a stale person index',()=>{const r=realm({households:2,cash:0});init(r);r.s.buildings=[{ownerId:1}];r.eval("bindPropertyRights(s);const q={id:99,gn:'new',si:0,age:30};s.folk.push(q);householdAccount(q);s.buildings[0].ownerId=99");assert.equal(r.s.buildings[0].title.owner,r.eval('householdAccount(s.folk[2])'));});

test('monthly provisioning for an unnamed cohort credits that cohort pantry',()=>{const r=realm({households:0,cash:0});init(r);r.eval('provision(s,[],new Map())');assert.ok(r.eval("pantry(s,s.households[0]).grain>0"));near(r.eval("pantry(s,'crown').grain||0"),0);});

test('population totals invalidate on direct ledger set, delete and clear',()=>{const r=realm({households:3});init(r);
  const check=()=>assert.equal(r.s.pop,r.eval('s.households.reduce((n,h)=>n+(h.population.get(s)||0),0)'));
  check();r.eval('s.households[1].population.set(s,0.1)');check();r.eval('s.households[0].population.delete(s)');check();r.eval('s.households[2].population.clear()');check();r.s.pop=17;check();});
test('population cache preserves summation order and invalidates after household recomposition',()=>{const r=realm({households:3});init(r);
  r.eval('s.households[0].population.set(s,1e16);s.households[1].population.set(s,1);s.households[2].population.set(s,1)');assert.equal(r.s.pop,1e16);
  r.eval('marryHouseholds(H[0],H[1]);householdsOf(s)');assert.equal(r.s.pop,r.eval('s.households.reduce((n,h)=>n+(h.population.get(s)||0),0)'));});
test('markets retain owner order across direct writes, deletion and whole-inventory replacement',()=>{const r=realm({households:70});init(r);
  r.eval("for(const h of H)stockOf(s,h);for(const i of [69,32,31,2,0])stockOf(s,H[i]).sale.tools=i+1");
  assert.deepEqual(Array.from(r.eval("[...mkt(s,'tools')].map(([w])=>w.id)")),[1,3,32,33,70]);
  r.eval("delete stockOf(s,H[31]).sale.tools;stockOf(s,H[2]).sale={wine:2};stockOf(s,H[31]).sale.tools=32");
  assert.deepEqual(Array.from(r.eval("[...mkt(s,'tools')].map(([w])=>w.id)")),[1,32,33,70]);
  r.eval("const discarded=stockOf(s,H[31]).sale;stockOf(s,H[31]).sale={tools:4};delete discarded.tools");near(r.eval("mkt(s,'tools').get(H[31])"),4);assert.equal(r.eval("mkt(s,'tools').size"),4);});
test('market iterator sees forward additions and new owners while skipping removed entries',()=>{const r=realm({households:4});init(r);
  r.eval("for(const h of H)stockOf(s,h);offer(s,'tools',H[0],1);offer(s,'tools',H[2],3);const it=mkt(s,'tools').entries();it.next();offer(s,'tools',H[1],2);mkt(s,'tools').delete(H[2]);offer(s,'tools',H[3],4);offer(s,'tools','late',5)");
  assert.deepEqual(Array.from(r.eval("[...it].map(([w,v])=>[w.gn?w.id:w,v])"),x=>Array.from(x)),[[2,2],[4,4],['late',5]]);});
test('held totals preserve owner order after replacement and defined zero or undefined entries',()=>{const r=realm({households:3});init(r);
  r.eval("stockOf(s,H[2]).held.tools=1;stockOf(s,H[0]).held.tools=1e16;stockOf(s,H[1]).held.tools=1");assert.equal(r.eval("heldTotal(s,'tools')"),1e16);
  r.eval("stockOf(s,H[0]).held={tools:0};stockOf(s,H[1]).held.tools=undefined");assert.equal(r.eval("heldTotal(s,'tools')"),1);});
test('person index is reused between changes and refreshed after removal or household registration',()=>{const r=realm();init(r);
  assert.equal(r.eval('folkIndex()===folkIndex()'),true);r.eval('const oldIndex=folkIndex();removeAt(s,0);dropPerson(H[0]);const q={id:99,gn:"new",si:0};householdAccount(q)');
  assert.equal(r.eval('folkIndex()===oldIndex'),false);assert.equal(r.eval('folkIndex().has(1)'),false);assert.equal(r.eval('folkIndex().has(99)'),true);});
test('a census is reused across quiet days and recomputed after parish membership changes',()=>{const r=realm({households:2});init(r);const first=r.s.households;
  r.eval('day=()=>2;householdsOf(s)');assert.equal(r.s.households,first);r.eval('removeAt(s,0);day=()=>3;householdsOf(s)');assert.notEqual(r.s.households,first);assert.equal(r.s.households.length,1);near(r.s.pop,150);});
test('own-stock purchases retain demand, sale and income accounting',()=>{const r=realm({households:2});init(r);r.eval("mkt(s,'tools').clear();offer(s,'tools',H[0],4);offer(s,'tools',H[1],9);const cash0=means(H[0]);purchase(s,'tools',H[0],3,2)");
  near(r.eval('purchase.got'),3);near(r.eval('means(H[0])'),r.eval('cash0'));near(r.eval("mkt(s,'tools').get(H[1])"),9);near(r.eval("s._dem.tools"),3);near(r.eval("s._sold.tools"),3);near(r.eval('H[0]._inc'),6);});
test('market settlement reads live quantities when two inventory owners project the same head',()=>{
  // Freeze existing alias behavior: ownership repair is separate from performance work.
  for(const bulk of [false,true]){const r=realm({households:3,cash:100});init(r);
    r.eval("mkt(s,'tools').clear();const old=householdAccount(H[0]);bindHousehold(H[1],old);offer(s,'tools',H[0],10);householdPortion(H[0]);offer(s,'tools',H[0],20)");
    if(bulk)r.eval("clearMarket(s,'tools',[[H[2],15]],1)");else near(r.eval("purchase(s,'tools',H[2],15,1)"),7.5);
    near(r.eval("mkt(s,'tools').get(H[0])"),2.5);
  }
});
