#!/usr/bin/env node
// Serial hardware Chrome timing and independent expanded-storage replay checks.
import {MODEL_GRAPH_ORACLE} from './replay-graph.mjs';
import {ReplayFieldOracle,TRANSACTION_VALUE_ORACLE} from './replay-fields.mjs';
import {StorageEventReducer} from './storage-event-reducer.mjs';
import {CommoditySettlementReducer} from './commodity-settlement-reducer.mjs';
import {spawn,execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
import {isDeepStrictEqual} from 'node:util';
import {summarize,performanceGate} from './replay-metrics.mjs';
const CHROME=process.env.CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',sleep=ms=>new Promise(r=>setTimeout(r,ms)),active=new Set();
for(const sig of ['SIGINT','SIGTERM'])process.on(sig,()=>{for(const stop of active)stop();process.exit(sig==='SIGINT'?130:143);});
class CDP{
  constructor(url){this.ws=new WebSocket(url);this.n=0;this.wait=new Map();this.listeners=new Map();this.open=new Promise((res,rej)=>{const timer=setTimeout(()=>rej(new Error('CDP socket open timeout after 120s')),120000);this.ws.onopen=()=>{clearTimeout(timer);res();};this.ws.onerror=e=>{clearTimeout(timer);rej(e);};});
    this.ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=this.wait.get(m.id);if(p){clearTimeout(p.timer);this.wait.delete(m.id);m.error?p.reject(new Error(m.error.message)):p.resolve(m.result);}}else for(const f of this.listeners.get(m.method)||[])f(m.params);};
    this.ws.onclose=()=>{for(const p of this.wait.values()){clearTimeout(p.timer);p.reject(new Error('Chrome closed during '+p.label));}this.wait.clear();};}
  send(method,params={}){const id=++this.n,label=method+(params.expression?' expression='+params.expression.slice(0,240):params.url?' url='+params.url:'');return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.wait.delete(id);reject(new Error('CDP response timeout after 120s: '+label));},120000);this.wait.set(id,{resolve,reject,timer,label});try{this.ws.send(JSON.stringify({id,method,params}));}catch(e){clearTimeout(timer);this.wait.delete(id);reject(e);}});}
  on(method,f){if(!this.listeners.has(method))this.listeners.set(method,[]);this.listeners.get(method).push(f);}
}
async function evaluate(c,expression){const r=await c.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;}
async function launch(){const profile=fs.mkdtempSync(path.join(os.tmpdir(),'furlong-performance-'));
  const proc=spawn(CHROME,['--headless=new','--enable-precise-memory-info','--remote-debugging-port=0',`--user-data-dir=${profile}`,'--no-first-run','--no-default-browser-check','--disable-background-timer-throttling','--disable-renderer-backgrounding','--disable-backgrounding-occluded-windows',...(process.platform==='darwin'?['--use-angle=metal']:[]),'--enable-gpu','--ignore-gpu-blocklist','--window-size=1440,900','about:blank'],{stdio:['ignore','ignore','pipe']});
  let c;const stop=()=>{active.delete(stop);c?.ws.close();proc.kill('SIGKILL');fs.rmSync(profile,{recursive:true,force:true,maxRetries:10,retryDelay:100});};active.add(stop);
  try{const ws=await new Promise((res,rej)=>{let buf='';const timer=setTimeout(()=>rej(new Error('Chrome startup timeout')),30000);proc.stderr.on('data',d=>{buf+=d;const m=/DevTools listening on (ws:\/\/\S+)/.exec(buf);if(m){clearTimeout(timer);res(m[1]);}});proc.on('error',rej);proc.on('exit',code=>{clearTimeout(timer);rej(new Error('Chrome exited '+code));});});
    const list=await(await fetch(`http://127.0.0.1:${new URL(ws).port}/json/list`)).json();c=new CDP(list.find(t=>t.type==='page').webSocketDebuggerUrl);await c.open;return{c,stop};
  }catch(e){stop();throw e;}}




const AUDIT="window.__storageReplayEvents=[];\nfunction independentData(v){if(v===undefined)return {$auditType:'undefined'};if(typeof v==='number'&&!Number.isFinite(v))return {$auditNumber:String(v)};if(Object.is(v,-0))return {$auditNumber:'-0'};if(typeof v==='bigint')return {$auditBigInt:String(v)};if(v===null||typeof v!=='object')return v;const out={};for(const key of Reflect.ownKeys(v)){if(Array.isArray(v)&&key==='length')continue;if(typeof key!=='string')throw Error('Symbol in actual record');const d=Object.getOwnPropertyDescriptor(v,key);if(!('value' in d))throw Error('Accessor in actual record');out[key.startsWith('$audit')?'$'+key:key]=independentData(d.value);}return Array.isArray(v)?{$auditArray:{length:v.length,fields:out}}:out;}\nfunction independentOwner(o){if(o==null)return 'unassigned';if(typeof o!=='object')return typeof o+':'+String(o);if(o.household)return 'household:'+o.id;let i=W.houses.indexOf(o);if(i>=0)return 'house:'+i;i=W.settlements.indexOf(o);if(i>=0)return 'settlement:'+i;if(o.gn!==undefined&&o.id!=null)return 'person:'+o.id;return o.storageOwnerId||'unregistered-account';}\nfunction independentRecord(record,location){const out={};for(const key of Reflect.ownKeys(record)){if(typeof key!=='string')throw Error('Symbol in actual record');const d=Object.getOwnPropertyDescriptor(record,key);if(!('value' in d))throw Error('Accessor in actual record');out[key.startsWith('$audit')?'$'+key:key]=key==='owner'?independentOwner(d.value):location&&key==='building'?d.value?.storageId??null:independentData(d.value);}return out;}\nwindow.independentSnapshot=()=>W.settlements.flatMap((s,i)=>s.storage?[{settlement:i,lots:[...s.storage.lots.values()].map(l=>independentRecord(l,false)),locations:[...s.storage.locations.values()].map(l=>independentRecord(l,true))}]:[]);\nif(window.FURLONG_STORAGE_AUDIT_SUPPORTED===true){window.FURLONG_STORAGE_AUDIT_OBSERVER=e=>__storageReplayEvents.push(independentData(e));}else{const storageOutcomeOriginal=window.storageOutcome;window.storageOutcome=function(e){const result=storageOutcomeOriginal(e);__storageReplayEvents.push(independentData(e));return result;};}";
const COMMODITY_AUDIT=AUDIT.replace(
  "window.independentSnapshot=()=>W.settlements.flatMap((s,i)=>s.storage?[{settlement:i,lots:[...s.storage.lots.values()].map(l=>independentRecord(l,false)),locations:[...s.storage.locations.values()].map(l=>independentRecord(l,true))}]:[]);",
  "function commodityPlain(v){if(v===null||typeof v!=='object')return v;if(Array.isArray(v))return v.map(commodityPlain);const out={};for(const key of Reflect.ownKeys(v)){if(typeof key!=='string')throw Error('Symbol in commodity metadata');const d=Object.getOwnPropertyDescriptor(v,key);if(!d||!('value'in d))throw Error('Accessor in commodity metadata');out[key]=commodityPlain(d.value);}return out;}\nconst commodityCmp=(a,b)=>a<b?-1:a>b?1:0;window.independentSnapshot=()=>W.settlements.flatMap((s,settlement)=>{const K=s.storage;if(!K||K.version!==3)return[];const locations=[...K.facilities].sort((a,b)=>commodityCmp(a[0],b[0])).map(([id,f])=>({id,metadata:commodityPlain(f.metadata)})),balances=[];for(const[id,f]of K.facilities)for(const[good,owners]of f.balances)for(const[owner,availability]of owners)for(const[kind,quantity]of availability)if(quantity>0)balances.push({location:id,good,owner:independentOwner(owner),availability:kind,quantity});balances.sort((a,b)=>commodityCmp(a.location,b.location)||commodityCmp(a.good,b.good)||commodityCmp(a.owner,b.owner)||commodityCmp(a.availability,b.availability));return[{settlement,locations,balances}];});"
).replace(
  "if(window.FURLONG_STORAGE_AUDIT_SUPPORTED===true){window.FURLONG_STORAGE_AUDIT_OBSERVER=e=>__storageReplayEvents.push(independentData(e));}else{const storageOutcomeOriginal=window.storageOutcome;window.storageOutcome=function(e){const result=storageOutcomeOriginal(e);__storageReplayEvents.push(independentData(e));return result;};}",
  "if(window.FURLONG_STORAGE_AUDIT_SUPPORTED===true){window.FURLONG_STORAGE_AUDIT_OBSERVER=e=>__storageReplayEvents.push(e);}else{const storageOutcomeOriginal=window.storageOutcome;window.storageOutcome=function(e){const result=storageOutcomeOriginal(e);__storageReplayEvents.push(e);return result;};}"
);
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),A=Object.fromEntries(process.argv.slice(2).reduce((a,v,i,all)=>{if(v.startsWith('--'))a.push([v.slice(2),all[i+1]&&!all[i+1].startsWith('--')?all[i+1]:true]);return a;},[]));
if(A.help){console.log('node tools/replay-check.mjs --baseline REF --source HTML --out FRESH_DIR [--days 30 --seed 1001 --coast sea --cadence 1 --variants baseline,candidate,legacyoff,transactionsoff --mode both|timing|correctness --driver tick|raf --timeout 600 --audit observer|journal --reference COMPLETED_BASELINE_DIR --commodity --debug-events]');process.exit(0);}
const OUT=path.resolve(A.out||path.join(os.tmpdir(),'furlong-replay-'+Date.now())),days=Number(A.days||30),seed=Number(A.seed||1001),coast=A.coast||'sea',cadence=Number(A.cadence||1),driver=A.driver||'tick',mode=A.mode||'both',timeout=Number(A.timeout||600)*1000,variants=String(A.variants||'baseline,candidate').split(',');
if((A.audit&&!['observer','journal'].includes(A.audit))||!Number.isInteger(days)||days<1||!Number.isInteger(seed)||seed<0||!['sea','land'].includes(coast)||!Number.isInteger(cadence)||cadence<1||!['tick','raf'].includes(driver)||!['both','timing','correctness'].includes(mode)||!Number.isFinite(timeout)||timeout<1000||variants.some(v=>!['baseline','candidate','legacyoff','transactionsoff'].includes(v))||A.commodity&&(variants.length!==1||variants[0]!=='candidate'||mode==='timing'))throw Error('Invalid options');
const free=fs.statfsSync(path.dirname(OUT),{bigint:true});if(free.bavail*free.bsize<BigInt(Number(A['min-free-mb']||2048))*1024n*1024n)throw Error('Insufficient free disk; preserve evidence and choose a smaller run or recover headroom');if(fs.existsSync(OUT))throw Error('Choose fresh OUT');fs.mkdirSync(OUT,{recursive:true});const hash=s=>createHash('sha256').update(s).digest('hex');
const sources={baseline:execFileSync('git',['show',(A.baseline||'405fed3')+':index.html'],{cwd:ROOT,encoding:'utf8',maxBuffer:20e6,timeout:120000}),candidate:fs.readFileSync(A.source||path.join(ROOT,'index.html'),'utf8')};
for(const[k,s]of Object.entries(sources))fs.writeFileSync(path.join(OUT,k+'.source.html'),s);
fs.writeFileSync(path.join(OUT,'run.json'),JSON.stringify({args:A,node:process.version,chrome:execFileSync(CHROME,['--version'],{encoding:'utf8',timeout:120000}).trim(),sourceSHA256:Object.fromEntries(Object.entries(sources).map(([k,s])=>[k,hash(s)])),harnessSHA256:hash(fs.readFileSync(fileURLToPath(import.meta.url))),startedUTC:new Date().toISOString(),schema:A.commodity?'commodity-v3':'legacy-v2',limits:'Storage replay oracle; no complete-game hydration/continuation claim. Timing and correctness are separate fresh runs; sequential browser instances.'},null,2));
// Reuse only a completed comparison baseline with identical source and scenario.
let reference=null;
if(A.reference){const dir=path.resolve(A.reference),meta=JSON.parse(fs.readFileSync(path.join(dir,'run.json'),'utf8')),args=meta.args;assert.equal(meta.schema||'legacy-v2',A.commodity?'commodity-v3':'legacy-v2','Reference schema');assert.equal(meta.sourceSHA256[A.commodity?'candidate':'baseline'],hash(sources[A.commodity?'candidate':'baseline']),'Reference source');for(const[k,v]of Object.entries({days,cadence,seed,coast,driver,audit:A.audit||'observer'})){const defaults={days:30,cadence:1,seed:1001,coast:'sea',driver:'tick',audit:'observer'};assert.equal(String(args[k]??defaults[k]),String(v),'Reference scenario '+k);}if(A.commodity){reference={correctness:JSON.parse(fs.readFileSync(path.join(dir,'candidate-correctness.json'),'utf8'))};}else{reference={correctness:JSON.parse(fs.readFileSync(path.join(dir,'baseline-correctness.json'),'utf8')),timing:JSON.parse(fs.readFileSync(path.join(dir,'baseline-timing.json'),'utf8'))};}for(const r of Object.values(reference)){assert.equal(r.pass,true,'Reference run passed');assert.equal(r.sourceSHA256,hash(sources[A.commodity?'candidate':'baseline']),'Reference result source');assert.equal(r.variant,A.commodity?'candidate':'baseline');}assert.equal(reference.correctness.endDay-reference.correctness.startDay,days);if(!A.commodity)assert.equal(!!reference.timing.profiled,!!A.profile,'Reference profiling mode');}
const results=[];
async function run(variant,correctness){const name=variant+'-'+(correctness?'correctness':'timing'),source=sources[variant==='baseline'?'baseline':'candidate'];const control=`window.FURLONG_COMMODITY_BALANCES=${!!A.commodity&&variant==='candidate'};`+(variant==='legacyoff'?'window.FURLONG_REPLAY_LEGACY_AUDIT=true;':'');
const auditScript=A.commodity?COMMODITY_AUDIT:AUDIT;
const journalAudit=A.audit==='journal'?auditScript.slice(0,auditScript.indexOf('if(window.FURLONG_STORAGE_AUDIT_SUPPORTED'))+"for(const Journal of [OutcomeJournal,RawOutcomeJournal]){const originalAppend=Journal.prototype.append;Journal.prototype.append=function(e){const result=originalAppend.call(this,e);__storageReplayEvents.push(e.version===3?e:independentData(storageExpandOutcome(e)));return result;};}":auditScript;
const instrumentation=correctness?journalAudit+'\n'+TRANSACTION_VALUE_ORACLE+'\n'+MODEL_GRAPH_ORACLE:`window.__measure={ticks:[],heartbeat:[],peakPending:0};const originalTick=simTick;simTick=function(){const start=performance.now(),result=originalTick.apply(this,arguments);const m=__measure;m.peakPending=Math.max(m.peakPending,STORAGE_OUTCOMES.status().pendingBytes||0);m.peakHeap=Math.max(m.peakHeap||0,performance.memory?.usedJSHeapSize||0);if(result!==false)m.ticks.push(performance.now()-start);return result;};`;
const file=path.join(OUT,name+'.html');if(!source.includes('boot();'))throw Error('Missing boot marker');fs.writeFileSync(file,source.replace('boot();',()=>control+instrumentation+'\nboot();'));
const {c,stop}=await launch(),errors=[],started=Date.now(),result={variant,correctness,sourceSHA256:hash(source)};
try{await c.send('Page.enable');await c.send('Runtime.enable');c.on('Runtime.exceptionThrown',e=>errors.push(e.exceptionDetails.exception?.description||e.exceptionDetails.text));c.on('Runtime.consoleAPICalled',e=>{if(e.type==='error')errors.push(e.args.map(a=>a.description||a.value).join(' '));});await c.send('Page.addScriptToEvaluateOnNewDocument',{source:'window.__nativeRAF=window.requestAnimationFrame.bind(window);window.__nativeInterval=window.setInterval.bind(window);window.requestAnimationFrame=()=>0;window.setInterval=()=>0;'});await c.send('Page.navigate',{url:pathToFileURL(file).href+`#s=${seed}&f=${seed}&c=${coast}&y=850${['legacyoff','transactionsoff'].includes(variant)?'&transactions=off':''}`});
while(!await evaluate(c,"typeof W!=='undefined'&&!!W&&!document.getElementById('loading')").catch(()=>false)){if(Date.now()-started>timeout)throw Error('Boot timeout');if(errors.length)throw Error(errors.join('\n'));await sleep(100);}
result.gpu=await evaluate(c,"(()=>{const g=renderer.getContext(),e=g.getExtension('WEBGL_debug_renderer_info');return e?g.getParameter(e.UNMASKED_RENDERER_WEBGL):g.getParameter(g.RENDERER)})()");if(/SwiftShader|llvmpipe/i.test(result.gpu))throw Error('Hardware GPU required');await evaluate(c,"(async()=>{setSpeed(0);if(typeof VISUAL!=='undefined')await VISUAL.finish();await STORAGE_OUTCOMES.flush();})()");result.startDay=await evaluate(c,'day()');
if(!correctness){if(A.profile){await c.send('Profiler.enable');await c.send('Profiler.start');result.profiled=true;}await evaluate(c,`(()=>{const m=__measure;m.ticks=[];m.heartbeat=[];m.peakPending=0;m.peakHeap=performance.memory?.usedJSHeapSize||0;m.draws=0;const originalRender=renderer.render;renderer.render=function(){m.draws++;return originalRender.apply(this,arguments);};let last=performance.now();m.timer=__nativeInterval(()=>{const now=performance.now();m.heartbeat.push(Math.max(0,now-last-25));last=now;},25);m.start=performance.now();m.target=day()+${days};${driver==='raf'?`const measureTick=simTick;simTick=function(){if(day()>=m.target){setSpeed(0);return false;}return measureTick.apply(this,arguments);};window.requestAnimationFrame=__nativeRAF;lastT=0;requestAnimationFrame(animate);setSpeed(5);`:''}})()`);
for(let i=0;driver==='tick'&&i<days;i++){await evaluate(c,'(async()=>{while(simTick()===false)await STORAGE_OUTCOMES.wait();if(day()%30===15||day()%360===0)await new Promise(r=>setTimeout(r,0));})()');if(Date.now()-started>timeout)throw Error('Timing timeout');}
while(driver==='raf'&&await evaluate(c,'day()<__measure.target')){if(Date.now()-started>timeout)throw Error('RAF timeout');await sleep(50);}
Object.assign(result,await evaluate(c,'(async()=>{setSpeed(0);const m=__measure;clearInterval(m.timer);const simulationMs=performance.now()-m.start,preflush=STORAGE_OUTCOMES.status();await STORAGE_OUTCOMES.flush();return {elapsedMs:performance.now()-m.start,simulationMs,ticks:m.ticks,heartbeat:m.heartbeat,peakPending:m.peakPending,peakHeap:m.peakHeap,rendererDraws:m.draws,endDay:day(),preflush,journal:STORAGE_OUTCOMES.status(),errors:errN};})()'));assert.equal(result.endDay-result.startDay,days,'Exact timed day count');if(driver==='raf')assert.ok(result.rendererDraws>0,'Actual RAF renderer draws');result.daysPerSecond=days/(result.elapsedMs/1000);result.tickMs=summarize(result.ticks);result.inputHeartbeatMs=summarize(result.heartbeat);result.maxStallMs=Math.max(result.tickMs.max||0,result.inputHeartbeatMs.max||0);delete result.ticks;delete result.heartbeat;if(A.profile){const {profile}=await c.send('Profiler.stop');fs.writeFileSync(path.join(OUT,name+'.cpuprofile'),JSON.stringify(profile));}
}else{const accepted=createHash('sha256'),durable=createHash('sha256'),Reducer=A.commodity?CommoditySettlementReducer:StorageEventReducer,live=new Reducer(),disk=new Reducer(),acceptedEvents=A['debug-events']&&A.commodity?[]:null,durableEvents=A['debug-events']&&A.commodity?[]:null;result.boundaries=[];let eventCount=0,persistedEventCount=0;const absorb=(events,reducer,digest)=>{for(const e of events){if(e.kind==='begin')continue;digest.update(JSON.stringify(e)+'\n');if(reducer===live)eventCount++;else persistedEventCount++;if(A['debug-events']&&A.commodity)(reducer===live?acceptedEvents:durableEvents).push(e);if(A.commodity){if(e.kind==='storage'&&e.cause==='daily-settlement'&&e.version===3)reducer.apply(e);}else reducer.apply(e);}},verify=(reducer,actual)=>{if(!A.commodity)return reducer.compare(actual);const expected=reducer.snapshot().map(({settlement,locations,balances})=>({settlement,locations,balances}));assert.deepEqual(expected,actual,'V3 independent facility-balance projection');};
for(let i=0;i<=days;i++){const state=await evaluate(c,`(async()=>{if(${i}>0){while(simTick()===false)await STORAGE_OUTCOMES.wait();if(day()%30===15||day()%360===0)await new Promise(r=>setTimeout(r,0));}if(typeof VISUAL!=='undefined')await VISUAL.finish();await STORAGE_OUTCOMES.flush();return {day:day(),events:__storageReplayEvents.splice(0),actual:${i%cadence===0||i===days?'independentSnapshot()':'null'},graph:${A.commodity?'null':i%cadence===0||i===days?'await independentModelGraph()':'null'},rng:Object.fromEntries(['gen','sim','folk'].map(k=>[k,RS[k].state()])),errors:errN};})()`);absorb(state.events,live,accepted);if(state.actual){verify(live,state.actual);result.boundaries.push({day:state.day,stateSHA256:hash(JSON.stringify(state.actual)),graph:state.graph,rng:state.rng,eventSHA256:accepted.copy().digest('hex')});}if(state.errors||errors.length)throw Error('Simulation/browser errors');if(Date.now()-started>timeout)throw Error('Correctness timeout');}
await evaluate(c,'(async()=>{await STORAGE_OUTCOMES.flush();window.__persistedReplay=(STORAGE_OUTCOMES.storageRecords||STORAGE_OUTCOMES.records).call(STORAGE_OUTCOMES);})()');let done=false;while(!done){const batch=await evaluate(c,`(async()=>{const events=[];let done=false;for(let i=0;i<1000;i++){const n=await __persistedReplay.next();if(n.done){done=true;break;}events.push(${A.commodity?'n.value.event':'independentData(n.value.event)'});}return {events,done};})()`);absorb(batch.events,disk,durable);done=batch.done;if(Date.now()-started>timeout)throw Error('Persisted replay timeout');}verify(disk,await evaluate(c,'independentSnapshot()'));result.acceptedSHA256=accepted.digest('hex');result.persistedSHA256=durable.digest('hex');if(A['debug-events']&&A.commodity){const common=Math.min(acceptedEvents.length,durableEvents.length);let mismatch=-1;for(let i=0;i<common;i++)if(JSON.stringify(acceptedEvents[i])!==JSON.stringify(durableEvents[i])){mismatch=i;break;}if(mismatch>=0)result.eventDifference={index:mismatch,accepted:acceptedEvents[mismatch],persisted:durableEvents[mismatch],sameValue:isDeepStrictEqual(acceptedEvents[mismatch],durableEvents[mismatch])};else if(acceptedEvents.length!==durableEvents.length)result.eventDifference={index:common,accepted:acceptedEvents[common]??null,persisted:durableEvents[common]??null,sameValue:false,acceptedCount:acceptedEvents.length,persistedCount:durableEvents.length};}assert.equal(result.acceptedSHA256,result.persistedSHA256,A.commodity?'Accepted/persisted settlement envelopes':'Accepted/persisted expanded events');result.endDay=await evaluate(c,'day()');assert.equal(result.endDay-result.startDay,days,'Exact correctness day count');result.events=A.commodity?eventCount:live.count;if(A.commodity){result.persistedEvents=persistedEventCount;result.commodity={version:3,verifiedAgainst:'independent facility balances and CommoditySettlementReducer',schemaComparable:false};}result.transactions=await evaluate(c,'typeof FURLONG_TRANSACTIONS==="undefined"?null:FURLONG_TRANSACTIONS.status()');
if(result.transactions){const fields=new ReplayFieldOracle();await evaluate(c,'window.__semanticReplay=FURLONG_TRANSACTIONS.records()');let complete=false;while(!complete){const b=await evaluate(c,`(async()=>{const transactions=[];let done=false;for(let i=0;i<500;i++){const n=await __semanticReplay.next();if(n.done){done=true;break;}const tx=n.value.event;transactions.push({id:tx.id,fields:tx.effects.filter(e=>e.kind==='definition'||e.kind==='field').map(e=>e.kind==='definition'?{kind:e.kind,entity:e.entity,path:e.path,fields:Object.entries(e.fields).map(([k,v])=>[k,independentData(v)])}:{kind:e.kind,entity:e.entity,path:e.path,before:independentData(e.before),after:independentData(e.after)})});}return {transactions,done};})()`);for(const tx of b.transactions)fields.apply(tx);complete=b.done;if(Date.now()-started>timeout)throw Error('Semantic field replay timeout');}
const queries=fields.queries(),actual=[];for(let i=0;i<queries.length;i+=500){const batch=queries.slice(i,i+500).map(({entity,path})=>({entity,path}));actual.push(...await evaluate(c,`(()=>{const q=${JSON.stringify(batch)};return q.map(({entity,path})=>{const parent=FURLONG_TRANSACTIONS.resolve(entity,path.slice(0,-1)),key=path.at(-1),d=parent==null?null:Object.getOwnPropertyDescriptor(parent,key);if(d&&!('value'in d))throw Error('Recorded scalar became accessor '+entity);return {entity,path,state:independentData(d?{present:true,value:independentTransactionValue(d.value)}:{present:false})};});})()`));}fields.compare(actual);result.semanticFields={transactions:fields.transactions,fields:queries.length,effects:fields.effects,skipped:fields.skipped,structured:fields.structured,pass:true,scope:'Converted own scalar/structured fields and registered reference identity; accessors skipped; no complete-game coverage claim'};}else result.semanticFields={supported:false};result.journal=await evaluate(c,'STORAGE_OUTCOMES.status()');}
if(errors.length||result.errors)throw Error('Browser/simulation errors');assert.equal(result.journal.pendingBytes,0);if(Number.isInteger(result.journal.records)&&Number.isInteger(result.journal.committed))assert.equal(result.journal.committed,result.journal.records-1,'Final sequence durable');assert.equal(result.journal.fault,null);assert.equal(result.journal.modelFault,null);result.pass=true;
}catch(e){result.pass=false;result.error=e.stack;}finally{result.browserErrors=errors;stop();fs.writeFileSync(path.join(OUT,name+'.json'),JSON.stringify(result,null,2));}return result;}
for(const v of variants){if(mode!=='correctness')results.push(await run(v,false));if(mode!=='timing')results.push(await run(v,true));}
const baseline=results.find(r=>r.variant==='baseline'&&r.correctness)||reference?.correctness,checks=A.commodity?results.filter(r=>r.correctness).map(r=>({variant:r.variant,matched:reference?!!reference.correctness?.pass&&r.pass&&JSON.stringify(reference.correctness.boundaries)===JSON.stringify(r.boundaries)&&reference.correctness.acceptedSHA256===r.acceptedSHA256:null,schemaComparable:false,comparison:reference?'same-v3 reference':'independent v3 reducer only'})):results.filter(r=>r.correctness&&r.variant!=='baseline').map(r=>({variant:r.variant,matched:!!baseline&&baseline.pass&&r.pass&&JSON.stringify(baseline.boundaries)===JSON.stringify(r.boundaries)&&baseline.acceptedSHA256===r.acceptedSHA256}));
const timingBase=results.find(r=>r.variant==='baseline'&&!r.correctness)||reference?.timing;const gates=results.filter(r=>r.variant!=='baseline'&&!r.correctness).map(r=>({variant:r.variant,...performanceGate(timingBase,r,{driver:A.profile?'profiled':driver})}));
fs.writeFileSync(path.join(OUT,'checks.json'),JSON.stringify({baselineOnly:variants.every(v=>v==='baseline'),schema:A.commodity?'commodity-v3':'legacy-v2',schemaComparable:!A.commodity,performanceClaim:checks.length&&gates.length?'Compare reported gates; correctness also required':'No comparative candidate gate established',gates,results:results.map(r=>({variant:r.variant,correctness:r.correctness,pass:r.pass})),checks},null,2));console.log(JSON.stringify({out:OUT,checks,gates},null,2));if(results.some(r=>!r.pass)||checks.some(r=>r.matched===false)||!A.commodity&&checks.some(r=>!r.matched))process.exitCode=1;
