import test from 'node:test';import assert from 'node:assert/strict';import {ReplayFieldOracle} from './replay-fields.mjs';
const definition={kind:'definition',entity:'household:child',path:['assets'],fields:[['w',{present:true,value:10}]]};const change=(before,after)=>({kind:'field',entity:'household:child',path:['assets','w'],before,after});
test('own presence and exact tiny values survive ordered field replay',()=>{const o=new ReplayFieldOracle();o.apply({fields:[definition,change({present:true,value:10},{present:true,value:1e-20})]});o.compare([{entity:'household:child',path:['assets','w'],state:{present:true,value:1e-20}}]);assert.throws(()=>o.compare([{entity:'household:child',path:['assets','w'],state:{present:false}}]));});
test('stale prior record cannot be healed by before or repeated definitions',()=>{const o=new ReplayFieldOracle();o.apply({fields:[definition]});assert.throws(()=>o.apply({fields:[definition,change({present:true,value:11},{present:true,value:12})]}));});
test('accessors are explicitly skipped while structured data is retained',()=>{const o=new ReplayFieldOracle();o.apply({fields:[{kind:'definition',entity:'x',path:[],fields:[['access',{present:true,accessor:true}],['array',{present:true,value:[1]}]]}]});assert.equal(o.skipped,1);assert.equal(o.fields.size,1);});

test('failed field transaction is atomically rejected',()=>{const o=new ReplayFieldOracle();o.apply({fields:[definition]});const before=JSON.stringify({fields:o.queries(),effects:o.effects,transactions:o.transactions});assert.throws(()=>o.apply({fields:[change({present:true,value:10},{present:true,value:5}),change({present:true,value:11},{present:true,value:2})]}));assert.equal(JSON.stringify({fields:o.queries(),effects:o.effects,transactions:o.transactions}),before);});
test('debt arrays preserve creditor identity and order',()=>{const o=new ReplayFieldOracle(),state={present:true,value:{$auditArray:{length:2,fields:{0:{$auditArray:{length:2,fields:{0:{$ref:'household:parent'},1:2}}},1:{$auditArray:{length:2,fields:{0:{$ref:'household:child'},1:1e-20}}}}}}};o.apply({fields:[{kind:'definition',entity:'household:debtor',path:['assets'],fields:[['_owe',state]]}]});o.compare([{entity:'household:debtor',path:['assets','_owe'],state}]);assert.throws(()=>o.compare([{entity:'household:debtor',path:['assets','_owe'],state:{...state,value:{$ref:'household:parent'}}}]));});
import vm from 'node:vm';import {TRANSACTION_VALUE_ORACLE} from './replay-fields.mjs';
test('independent raw debt serializer validates reference pointer identity',()=>{const creditor={household:true,id:'hh1'},child={household:true,id:'hh2'},refs=new Map([['household:hh1',creditor],['household:hh2',child]]),c=vm.createContext({W:{houses:[],settlements:[]},FURLONG_TRANSACTIONS:{resolve:id=>refs.get(id)},creditor,child});vm.runInContext(TRANSACTION_VALUE_ORACLE,c);const text=vm.runInContext("JSON.stringify(independentTransactionValue([[creditor,3],[child,1e-20]]))",c);assert.deepEqual(JSON.parse(text),[[{$ref:'household:hh1'},3],[{$ref:'household:hh2'},1e-20]]);refs.set('household:hh1',child);assert.throws(()=>vm.runInContext('independentTransactionValue([creditor,3])',c),/identity differs/);});
test('independent raw structure keeps array holes and ordered Map/Set entries',()=>{const c=vm.createContext({W:{houses:[],settlements:[]},FURLONG_TRANSACTIONS:{resolve:()=>null}});vm.runInContext(TRANSACTION_VALUE_ORACLE,c);const out=vm.runInContext("(()=>{const a=new Array(3);a[1]=undefined;const o=independentTransactionValue({a,m:new Map([['b',2],['a',1]]),s:new Set(['b','a'])});return {hole:!Object.hasOwn(o.a,'0'),undefinedPresent:Object.hasOwn(o.a,'1'),length:o.a.length,ordered:JSON.stringify([o.m,o.s])};})()",c);assert.equal(out.hole,true);assert.equal(out.undefinedPresent,true);assert.equal(out.length,3);assert.equal(out.ordered,'[{"$map":[["b",2],["a",1]]},{"$set":["b","a"]}]');});
