import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {realm,near} from './ownership-fixture.mjs';import {moneyFlowGap} from './money-flow.mjs';
const source=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const tick=source.slice(source.indexOf('function tickHouseholds('));const rent=tick.slice(tick.indexOf('const rent=rentOfHome(s,h);'),tick.indexOf('// what is left'));
const coins=r=>r.W.treasury+[...r.W.households.values()].reduce((n,h)=>n+(h.assets.w||0),0);
function fixture({cash=100,nonhead=false,dead=false,same=false}={}){const r=realm({cash,crown:0,households:2});r.eval('householdAccount(H[0]);householdAccount(H[1])');const owner={id:400,gn:'Owner',si:0,dead,ma:r.H[1]};r.C.owner=owner;r.eval('bindHousehold(owner,householdAccount(H[1]))');if(!nonhead&&!same)r.H[1]._hh.head=owner;if(same)r.eval('bindHousehold(owner,householdAccount(H[0]))');if(dead){r.H[1]._hh.head=r.H[1];owner._estateShares=[[r.H[1],1]];}r.C.h=r.H[0];r.H[0].bh={rural:true,ownerId:owner.id};r.W._pm=new Map([[owner.id,owner]]);r.C.rentOfHome=()=>25.144620202627266;return {r,owner};}
for(const mode of [{nonhead:true},{},{dead:true}])test('rural rent credits canonical owner account '+JSON.stringify(mode),()=>{const {r}=fixture(mode),before=coins(r),recipient=r.H[1]._hh.assets.w;const flows={...r.W._flow};r.eval('{'+rent+'}');near(coins(r),before);near(r.H[1]._hh.assets.w-recipient,25.144620202627266);near(r.H[0].w,100-25.144620202627266);assert.equal(moneyFlowGap(flows,r.W._flow||{}).expect,0);});
test('rural rent within same household conserves its purse',()=>{const {r}=fixture({same:true});const before=r.H[0].w,income=r.H[0]._hh.assets._inc;r.eval('{'+rent+'}');assert.equal(r.H[0].w,before);assert.equal(r.H[0]._hh.assets._inc,income);});
test('rural rent caps actual payment at available tenant purse',()=>{const {r}=fixture({cash:5,nonhead:true}),before=coins(r);r.eval('{'+rent+'}');assert.equal(r.H[0].w,0);assert.equal(r.H[1].w,10);assert.equal(coins(r),before);});
test('missing recorded landlord does not debit tenant',()=>{const {r}=fixture({nonhead:true});r.W._pm.clear();r.eval('{'+rent+'}');assert.equal(r.H[0].w,100);});
test('positive tiny rural rent is retained without a floor',()=>{const {r}=fixture({nonhead:true});r.C.rentOfHome=()=>1e-12;const before=r.H[1].w;r.eval('{'+rent+'}');assert.ok(r.H[1].w>before);assert.equal(r.W._flow?.['<>lost'],undefined);});

test('child landlord rent follows formation of an independent household',()=>{const {r,owner}=fixture({cash:100,nonhead:true}),parent=owner._hh,tenant=r.H[0]._hh;const property={title:{owner:parent,beneficiary:owner}};r.s.buildings.push(property);const initial=coins(r);r.eval('{'+rent+'}');const parentAfter=parent.assets.w;near(parentAfter,125.144620202627266);r.eval('householdPortion(owner)');const independent=owner._hh;assert.notEqual(independent,parent);assert.notEqual(independent,tenant);assert.equal(independent.head,owner);assert.equal(parent.head,r.H[1]);assert.equal(owner.own,true);assert.equal(property.title.owner,independent);assert.equal(property.title.beneficiary,owner);r.eval('{'+rent+'}');assert.equal(parent.assets.w,parentAfter);near(independent.assets.w,25.144620202627266);near(coins(r),initial);});
test('child owning the family roof incurs rent only after forming own household',()=>{const {r,owner}=fixture({cash:100,same:true}),family=owner._hh;const property={title:{owner:family,beneficiary:owner}};r.s.buildings.push(property);const before=coins(r),income=family.assets._inc;r.eval('{'+rent+'}');assert.equal(family.assets.w,100);assert.equal(family.assets._inc,income);r.eval('householdPortion(owner)');const child=owner._hh;assert.notEqual(child,family);assert.equal(child.head,owner);assert.equal(family.head,r.H[0]);assert.equal(property.title.owner,child);r.eval('{'+rent+'}');near(family.assets.w,100-25.144620202627266);near(child.assets.w,25.144620202627266);near(coins(r),before);});
