import test from 'node:test';
import assert from 'node:assert/strict';
import {realm} from './ownership-fixture.mjs';
function count(program){return program.replace('of storageClaimOwners(s,g))for',"of (function*(){for(const pair of storageClaimOwners(s,g)){claimOwnerVisits++;yield pair;}})())for").replace('of s._owners||[])for',"of (function*(){for(const pair of s._owners||[]){claimOwnerVisits++;yield pair;}})())for");}
function run(r,expr){try{return {value:r.eval(expr)}}catch(e){return {name:e.name,message:e.message}}}
function single(empty=0){const r=realm({households:3,grain:0,fish:0,cash:100,bootstrap:'let claimOwnerVisits=0;',transformSource:count});r.eval(`for(let i=0;i<${empty};i++)stockOf(s,{id:10000+i});storageInit(s);const K=s.storage;K.location('a',{capacity:1000});for(let i=0;i<H.length;i++){K.create('grain',3,accountOwner(H[i]),'a','held');addHeld(s,H[i],'grain',3);}storageTitles(s);globalThis.randomCalls=0;globalThis.randomState=123;randi=()=>{randomCalls++;randomState=(Math.imul(randomState,1664525)+1013904223)>>>0;return randomState};`);return r;}
for(const n of [0,1000,10000])test(`active collection skips ${n} empty archived owners`,()=>{const r=single(n);r.eval("claimOwnerVisits=0");r.eval("pantry(s,H[0]).grain=2.5;pantry(s,H[1]).grain=3.5;storageTitles(s,'grain');undefined");assert.equal(r.eval('claimOwnerVisits'),3);assert.equal(r.eval("STORAGE_ACTIVE_CLAIMS.get(s).fallback"),false);assert.equal(r.eval("storageClaimOwners(s,'grain').length"),3);assert.equal(r.eval('s._owners.size'),n+3);assert.equal(r.eval("storageClaimOwners(s,'fish').length"),0);});
test('dynamic owners, held-before-sale and char/timber claims keep the active path',()=>{const r=single(50);run(r,"const newOwner={id:8888};addHeld(s,newOwner,'grain',1e-13);pantry(s,H[0]).grain-=1e-13;offer(s,'grain',H[1],1);storageTitles(s,'grain');undefined");assert.equal(r.eval('STORAGE_ACTIVE_CLAIMS.get(s).fallback'),false);run(r,"s.stores.timber=4;K.create('timber',4,null,'yard');addHeld(s,H[0],'char',1);addHeld(s,H[1],'timber',2);offer(s,'timber',H[2],1);storageTitles(s,'timber');undefined");});
test('definition/deletion, zero, negative, NaN and tiny values keep the active path',()=>{const r=single();for(const expr of ["delete pantry(s,H[0]).grain", "Object.defineProperty(pantry(s,H[0]),'grain',{value:1e-13,writable:true,enumerable:true,configurable:true})", "pantry(s,H[0]).grain=NaN", "pantry(s,H[0]).grain=-1", "pantry(s,H[0]).grain=0", "pantry(s,H[0]).grain=3"]){r.eval(expr+";storageTitles(s,'grain');undefined");assert.equal(r.eval('STORAGE_ACTIVE_CLAIMS.get(s).fallback'),false);}});
test('managed table replacement retains activity and unknown replacement falls back',()=>{const r=single();r.eval("storageClaimReplace(stockOf(s,H[0]),'held',{grain:2});pantry(s,H[1]).grain=4;storageTitles(s,'grain');undefined");assert.equal(r.eval('STORAGE_ACTIVE_CLAIMS.get(s).fallback'),false);r.eval("stockOf(s,H[0]).held={grain:1};storageTitles(s,'grain');undefined");assert.equal(r.eval('STORAGE_ACTIVE_CLAIMS.get(s).fallback'),true);});
test('public dirty, custom native map methods and size drift use original scan',()=>{for(const expr of ["storageTitleDirty(s,'grain')", "s._owners.set({id:99999},{held:{grain:1},sale:{},reserve:{},animals:{}});storageTitleKnownDirty(s,'grain')", "s._owners.get=function(k){return Map.prototype.get.call(this,k)};storageTitleKnownDirty(s,'grain')"]){const r=single();run(r,expr+";storageTitles(s,'grain');undefined");assert.equal(r.eval("storageClaimOwners(s,'grain')===s._owners"),true);}});
test('accessor-backed claims and throwing arithmetic use the full owner scan',()=>{const r=single();r.eval("let reads=0;Object.defineProperty(pantry(s,H[0]),'grain',{get(){reads++;return 3},configurable:true,enumerable:true});storageTitles(s,'grain');reads");assert.equal(r.eval("storageClaimOwners(s,'grain')===s._owners"),true);assert.throws(()=>r.eval("pantry(s,H[1]).grain=Symbol('bad')"),{name:'TypeError'});});
test('inheritance, marriage and household growth keep the active path with retained archives',()=>{const r=single(100);run(r,"H[0].kids=[H[1],H[2]];H[1].pa=H[0];H[2].pa=H[0];H[1].own=H[2].own=true;transferOwnership(accountOwner(H[0]),[[accountOwner(H[1]),.3],[accountOwner(H[2]),.7]]);storageTitles(s,'grain');undefined");assert.equal(r.eval('STORAGE_ACTIVE_CLAIMS.get(s).fallback'),false);run(r,"const child={id:9,gn:'child',age:8,si:0,ma:H[1],w:0};H.push(child);s.folk.push(child);consumeOwned(s,child,'grain',.125);householdPortion(child,.15);addHeld(s,child,'grain',.5);storageTitles(s,'grain');undefined");run(r,"marryHouseholds(H[1],H[2]);storageTitles(s,'grain');undefined");assert.equal(r.eval('STORAGE_ACTIVE_CLAIMS.get(s).fallback'),false);});
test('unknown null-prototype claim tables decline admission',()=>{const r=single();r.eval("const table=Object.create(null);table.grain=1;stockOf(s,H[0]).held=table;storageTitles(s,'grain');undefined");assert.equal(r.eval('STORAGE_ACTIVE_CLAIMS.get(s).fallback'),true);});

test('cross-realm owner Map replacement uses original scan',()=>{const r=single();r.s._owners=new Map(r.s._owners);r.eval("storageTitleKnownDirty(s,'grain');storageTitles(s,'grain');undefined");assert.equal(r.eval("storageClaimOwners(s,'grain')===s._owners"),true);});
test('actual audit observer reentrant dirty, replacement and owner admission fall back to the full scan',()=>{const r=single(100);r.eval("let observed=[];let observerOnce=true;storageOutcome=function(e){storageObserveOutcome(e);K.events.push(e)};FURLONG_STORAGE_AUDIT_OBSERVER=function(e){observed.push([e.seq,e.cause]);if(observerOnce&&e.cause==='title-transfer'){observerOnce=false;stockOf(s,H[2]).held={grain:2};addHeld(s,{id:7654},'grain',1,true);storageTitleDirty(s,'grain');}};pantry(s,H[0]).grain=0;pantry(s,H[1]).grain=6;storageTitles(s,'grain');storageTitles(s,'grain');JSON.stringify(observed)");assert.equal(r.eval('observerOnce'),false);assert.equal(r.eval('STORAGE_ACTIVE_CLAIMS.get(s).fallback'),true);});

test('active matching protects true pending custody alongside valid settled claims',()=>{const r=single();r.eval("const p=K.split([...K.lots.values()][0],2);K.annotate(p,{pendingPurchase:true,negativeZero:-0,optional:undefined});pantry(s,H[0]).grain=1;storageTitles(s,'grain')");assert.equal(r.eval('p.pendingPurchase'),true);assert.equal(r.eval('p.qty'),2);assert.equal(r.eval('p.owner===accountOwner(H[0])'),true);assert.equal(r.eval('STORAGE_ACTIVE_CLAIMS.get(s).fallback'),false);assert.equal(r.eval("storageClaimOwners(s,'grain').length"),3);assert.equal(r.eval('K.events.some(e=>e.cause===\"unbacked-title\")'),false);});
