import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {execFileSync} from 'node:child_process';
const candidate=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8'),baseline=execFileSync('git',['show','405fed3:index.html'],{encoding:'utf8',maxBuffer:20e6});
function fn(s,name){const start=s.indexOf('function '+name+'(');assert.ok(start>=0,name);let p=s.indexOf('{',start),depth=1;for(p++;depth;p++){if(s[p]==='{')depth++;else if(s[p]==='}')depth--;}return s.slice(start,p);}
const commodityActiveSource=fn(candidate,'commodityActive');
function realm(source){const c=vm.createContext({});vm.runInContext(`const GRID=101,CELL=5,SIZE=500,SEA_SURFACE=-1;let HASH_STAMP=0;const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist2d=(a,b,c,d)=>Math.hypot(a-c,b-d),lerp=(a,b,f)=>a+(b-a)*f,lerpPt=(a,b,f)=>({x:a.x+(b.x-a.x)*f,z:a.z+(b.z-a.z)*f}),toCell=x=>Math.round(x/5)+50,cIdx=(x,z)=>z*GRID+x,inB=(x,z)=>x>=0&&z>=0&&x<GRID&&z<GRID;const W={water:new Uint8Array(GRID*GRID),h:new Float64Array(GRID*GRID),projects:[],settlements:[]};const G={};function day(){return 0;}function lakeAt(){return false;}function wallRadAt(s){return s.wallRad;}function fortCircuits(){return [];}function fortRoadBlocked(){return false;}function fortStreetRuns(s,st){return [st.pts];}const owner={household:true,id:'hh1',head:{tr:'farmer'}};const s={name:'test',owner:0,pos:{x:0,z:0},places:[{kind:'market',x:0,z:0}],buildings:[],streets:[{pts:[{x:-100,z:0},{x:100,z:0}]},{pts:[{x:0,z:-100},{x:0,z:100}]}],furl:[{x:28,z:16,state:1},{x:49,z:23,state:1},{x:72,z:11,state:1}]};W.settlements=[s];const LS={TILLED:1},ARCH={grange:[12,10],warehouse:[12,10]},STORAGE_TYPES={grange:{capacity:800,cost:360,timber:24,stone:0,days:90},warehouse:{capacity:1000,cost:500,timber:30,stone:15,days:100}};let sites=[],events=[],emits=[],accessCalls=0,pathCalls=0;const K={next:1,lots:new Map([['goods',{owner,qty:400,good:'grain',location:'yard'}]]),locations:new Map([['yard',{exposed:true}]]),volume:()=>1,event:(...v)=>events.push(v)};function storageFacilities(){s.storageReport={exposed:400};return K;}function storageInit(){return K;}function storageOwnerId(x){return x.id;}function storageProjectState(q){return {...q,payer:q.payer.id};}function storageOutcomeAssert(){}function means(){return 100000;}function price(s,g){return g==='grain'?3:2;}function emit(...args){emits.push(args);}s._lay={live:{storageSite(x,z,arch,dry){sites.push([x,z,arch,!!dry]);return {x,z};}}};`,c);
vm.runInContext(commodityActiveSource,c);
// Compare batching against the frozen routing algorithm on the same current, water-safe graph.
for(const name of ['resample','segDist','slopeAt','hAt','makeHash','riverAt','onRoad','paidRoadAt','roadAccessClear','streetGraph','streetPath','storageAccess','storageRoute','planLand','storageSiteQuote','storageCommission','storageInvestment'])vm.runInContext(fn(['onRoad','paidRoadAt','roadAccessClear','streetGraph'].includes(name)?candidate:source,name),c);
if(source.includes('const STORAGE_ROUTE_BATCHES='))vm.runInContext('const STORAGE_ROUTE_BATCHES=new WeakMap();',c);
if(source.includes('function storageRouteBatch('))vm.runInContext(fn(source,'storageRouteBatch'),c);
vm.runInContext("K.exposedLots=()=>[...K.lots.values()].filter(l=>K.locations.get(l.location)?.exposed);",c);
vm.runInContext(`G.rivHash=W.rivHash=makeHash(10);const originalAccess=storageAccess;storageAccess=function(){accessCalls++;return originalAccess.apply(this,arguments);};const originalPath=streetPath;streetPath=function(){pathCalls++;return originalPath.apply(this,arguments);};`,c);return {run:x=>vm.runInContext(x,c),c};}
const value=(r,x)=>JSON.parse(r.run('JSON.stringify('+x+')'));
function compareRoutes(change=''){const a=realm(baseline),b=realm(candidate);for(const r of [a,b])r.run(change);const body=`const endpoints=[s.places[0],...s.furl,{x:31.125,z:-14.75},{x:-0,z:0}];const results=[];for(let k=0;k<3;k++)for(const a of endpoints)for(const b of endpoints)results.push(storageRoute(s,a,b${','}BATCH));`;
a.run(body.replace('BATCH','undefined'));b.run('const BATCH=storageRouteBatch(s);'+body);assert.deepEqual(value(a,'results.map(v=>Number.isFinite(v)?v:String(v))'),value(b,'results.map(v=>Number.isFinite(v)?v:String(v))'));return [a,b];}
test('batch distances and ordered A* ties are bit-exact against frozen baseline',()=>{const[a,b]=compareRoutes();assert.ok(b.run('accessCalls')<a.run('accessCalls'));assert.ok(b.run('pathCalls')<a.run('pathCalls'));});
for(const [name,change]of [['water','W.water[cIdx(toCell(30),toCell(10))]=1;'],['slope','W.h[cIdx(toCell(30),toCell(10))]=20;'],['river','G.rivHash.add({x:30,z:10,a:{x:30,z:-50},b:{x:30,z:50},hw:3},60);'],['no path','s.streets=[{pts:[{x:-100,z:0},{x:-60,z:0}]},{pts:[{x:60,z:0},{x:100,z:0}]}];'],['wall','s.wallRad=25;'],['siege','s.siegeBy={};'],['quarantine','s.quarantineUntil=1;']])test('blocked '+name+' matches baseline',()=>compareRoutes(change));
test('new batch observes changed terrain and graph; moving endpoint cannot reuse stale attachment',()=>{const a=realm(baseline),b=realm(candidate);for(const r of[a,b])r.run(`let p={x:30,z:20},q=s.places[0];`);b.run('let B=storageRouteBatch(s);storageRoute(s,p,q,B)');for(const r of[a,b])r.run(`W.water[cIdx(toCell(30),toCell(20))]=1;s.streets[0].hidden=true;p.x=60;`);b.run('B=storageRouteBatch(s)');assert.equal(a.run('storageRoute(s,p,q)'),b.run('storageRoute(s,p,q,B)'));});
test('investment preserves candidate legality order, quote arithmetic, winner and commission revalidation',()=>{const a=realm(baseline),b=realm(candidate);for(const r of[a,b])r.run('storageInvestment(s)');for(const x of['sites','events','emits','W.projects','G.ordersDirty'])assert.deepEqual(value(a,x),value(b,x),x);assert.equal(b.run('W.projects.length'),1);assert.ok(b.run('accessCalls')<a.run('accessCalls'));assert.ok(b.run('pathCalls')<a.run('pathCalls'));assert.equal(b.run("Object.keys(W.projects[0]).includes('routes')"),false);});
test('moving a cached endpoint within unchanged geometry recomputes its attachment',()=>{const a=realm(baseline),b=realm(candidate);for(const r of[a,b])r.run('let p={x:11,z:37},q=s.places[0];');b.run('const B=storageRouteBatch(s);storageRoute(s,p,q,B)');for(const r of[a,b])r.run('p.x=79;p.z=-23;');assert.equal(a.run('storageRoute(s,p,q)'),b.run('storageRoute(s,p,q,B)'));});
test('illegal candidate sites and reserved ground preserve exact evaluation order and winner',()=>{const a=realm(baseline),b=realm(candidate);for(const r of[a,b])r.run(`s._lay.live.storageSite=function(x,z,arch,dry){sites.push([x,z,arch,!!dry]);return x>60||z<0?null:{x,z};};W.projects=[{type:'storage',dead:false,si:2,x:0,z:0}];storageInvestment(s);`);for(const x of['sites','events','emits','W.projects'])assert.deepEqual(value(a,x),value(b,x),x);});
test('symmetric equal-benefit candidates retain first-in-search tie selection',()=>{const a=realm(baseline),b=realm(candidate);for(const r of[a,b])r.run(`s.furl=[{x:28,z:16,state:1},{x:-28,z:16,state:1}];storageInvestment(s);`);for(const x of['sites','events','W.projects'])assert.deepEqual(value(a,x),value(b,x),x);});
