import test from 'node:test';
import assert from 'node:assert/strict';
import {realm} from './ownership-fixture.mjs';
// Frozen deployed reader from 139dd52. Each pair uses the current physical ledger; the baseline
// performs its full stock read through the original getter before consumption.
const baselineConsume="function consumeOwned(s,who,g,q){const L=pantry(s,who),physical=g==='char'?'timber':g;let v=Math.max(0,Math.min(q,L[g]||0,s.stores[physical]||0));if(s.storage&&!BEASTS.includes(g)){storageTitles(s,physical);let left=v;if(v===0){if(typeof storageOutcomeAssert==='function')storageOutcomeAssert();}else{const owner=accountOwner(who);for(const id of [...s.storage.byOwner.get(owner)||[]]){const l=s.storage.lots.get(id);if(l&&l.owner===owner&&l.good===physical&&(l.claimGood||l.good)===g&&l.availability==='held'){left-=s.storage.remove(l,left,'consumption');if(!(left>0))break;}}}v-=left;L[g]=Math.max(0,(L[g]||0)-v);s.storage.titleMatched?.set(physical,s.storage.titleRevision?.get(physical)||0);}else{L[g]=Math.max(0,(L[g]||0)-v);s.stores[physical]=Math.max(0,(s.stores[physical]||0)-v);}return v;}";
function pair(){return [true,false].map(old=>{const r=realm({grain:0,fish:0,households:3});if(old)r.eval(baselineConsume);r.eval(`storageInit(s);const K=s.storage;K.create('grain',100,null,'yard');addHeld(s,H[0],'grain',40);addHeld(s,H[1],'grain',35);addHeld(s,H[2],'grain',25);K.create('timber',4,null,'yard');addHeld(s,H[0],'char',4);storageTitles(s);`);return r;});}
function canonical(v){if(v===undefined)return ['undefined'];if(typeof v==='number'&&(!Number.isFinite(v)||Object.is(v,-0)))return ['number',Object.is(v,-0)?'-0':String(v)];if(v===null||typeof v!=='object')return v;return [Array.isArray(v)?'array':'object',Reflect.ownKeys(v).map(k=>[k,canonical(Object.getOwnPropertyDescriptor(v,k).value)])];}
function state(r){return canonical(r.eval(`({revision:K.revision,next:K.next,sequence:K.sequence,events:K.events,roundoff:[...K.roundoff],lots:[...K.lots.values()].map(l=>K.lotState(l)),locations:[...K.locations.values()].map(l=>K.locationState(l)),indices:['byOwner','byGood','byLocation','byAvailability'].map(k=>[k,[...K[k]].map(([o,ids])=>[k==='byOwner'?storageOwnerId(o):o,[...ids]])]),totals:[...K.totals],occupancy:[...K.occupancy],titleMatched:[...K.titleMatched||[]],titleRevision:[...K.titleRevision||[]],claims:[...s._owners].map(([o,x])=>[storageOwnerId(o),x.held,x.sale])})`));}
function run(P,script){const values=P.map(r=>canonical(r.eval(script)));assert.deepEqual(values[1],values[0]);assert.deepEqual(state(P[1]),state(P[0]));}
for(const [name,body]of [
 ['sequential small meals',`Array.from({length:120},(_,i)=>consumeOwned(s,H[i%3],'grain',.013))`],
 ['large demand and final exhaustion',`[consumeOwned(s,H[0],'grain',1e6),consumeOwned(s,H[1],'grain',1e6),consumeOwned(s,H[2],'grain',1e6),consumeOwned(s,H[2],'grain',.1)]`],
 ['unusual demand and empty pantry',`[consumeOwned(s,H[0],'grain',0),consumeOwned(s,H[0],'grain',-0),consumeOwned(s,H[0],'grain',NaN),consumeOwned(s,H[1],'fish',1),consumeOwned(s,H[1],'grain',Infinity)]`],
 ['coercible demands preserve the full-reader path',`[consumeOwned(s,H[0],'grain','0.1'),consumeOwned(s,H[0],'grain',null),consumeOwned(s,H[0],'grain',undefined)]`],
 ['char maps to timber',`[consumeOwned(s,H[0],'char',1e-300),consumeOwned(s,H[0],'char',.17)]`]
])test('owned inventory matches deployed consumption: '+name,()=>run(pair(),body));
test('transit custody is excluded from the stock bound',()=>{const P=pair();for(const r of P)r.eval(`K.location('cargo',{capacity:Infinity,transit:true});const l=[...K.byOwner.get(accountOwner(H[2]))].map(id=>K.lots.get(id)).find(l=>l.good==='grain');K.relocate(l,'cargo');`);run(P,`[consumeOwned(s,H[0],'grain',.3),consumeOwned(s,H[1],'grain',100)]`);});
test('changed getters and total overrides retain the original reader',()=>{const P=pair();for(const r of P)r.eval(`let reads=0;Object.defineProperty(s.stores,'grain',{get(){reads++;return 100;},configurable:true});`);run(P,`[consumeOwned(s,H[0],'grain',.3),reads]`);for(const r of P)r.eval(`const previous=K.total;K.total=function(g){return previous.call(this,g)};`);run(P,`[consumeOwned(s,H[0],'char',.3),reads]`);});
test('unchanged physical stock warms the same cache for an accepted tiny unmatched claim',()=>{const P=pair();for(const r of P)r.eval(`stockOf(s,H[0]).held.grain=1e-300;const lot=[...K.byOwner.get(accountOwner(H[0]))].map(id=>K.lots.get(id)).find(l=>l.good==='grain');K.transfer(lot,accountOwner(H[1]),lot.qty,'held');stockOf(s,H[1]).held.grain+=40;storageTitles(s,'grain');K.totals.delete('grain');`);run(P,`consumeOwned(s,H[0],'grain',1e-300)`);assert.equal(P[1].eval("STORAGE_BOUND_TOTALS.get(K)?.size||0"),0);});
test('a failed mutation guard restores the same full cache before throwing',()=>{const P=pair();for(const r of P)r.eval(`K.totals.delete('grain');storageOutcomeAssert=()=>{throw Error('blocked mutation')};`);for(const r of P)assert.throws(()=>r.eval(`consumeOwned(s,H[0],'grain',.01)`),/blocked mutation/);assert.deepEqual(state(P[1]),state(P[0]));assert.equal(P[1].eval("STORAGE_BOUND_TOTALS.get(K)?.size||0"),0);});
test('a small bite does not traverse unrelated town stock and never caches a partial sum',()=>{const P=pair();for(const r of P)r.eval(`for(let i=0;i<1000;i++)K.create('grain',1,'other:'+i,'yard','held');storageTitles(s,'grain');K.totals.delete('grain');let reads=0;const get=K.lots.get;K.lots.get=function(id){reads++;return get.call(this,id)};`);run(P,`consumeOwned(s,H[0],'grain',.01)`);const a=P[0].eval('reads'),b=P[1].eval('reads');assert.ok(a>1000);assert.ok(b<20,"bounded lot reads "+b);assert.equal(P[1].eval("K.totals.has('grain')"),false);run(P,`K.total('grain')`);});

test('fragmented inventory and interleaved floating quantities preserve full-total rounding',()=>{const P=pair();for(const r of P)r.eval(`const own=accountOwner(H[0]);for(const id of [...K.byOwner.get(own)]){const l=K.lots.get(id);if(l.good==='grain')K.remove(l,l.qty,'fixture');}stockOf(s,H[0]).held.grain=0;K.create('grain',1e16,'large-stock','yard','held');K.create('grain',.1,own,'yard','held');K.create('grain',.2,'small-stock','yard','held');K.location('pantry',{capacity:Infinity});K.create('grain',.2,own,'pantry','held');stockOf(s,H[0]).held.grain=.3;storageTitles(s,'grain');K.totals.delete('grain');`);run(P,`consumeOwned(s,H[0],'grain',.3)`);});

test('a total override installed before inventory binding retains its semantics',()=>{const P=[true,false].map(old=>{const r=realm({grain:0,fish:0});if(old)r.eval(baselineConsume);r.eval(`const nativeTotal=StorageLedger.prototype.total;StorageLedger.prototype.total=function(g){return nativeTotal.call(this,g)/2};storageInit(s);const K=s.storage;K.create('grain',1,null,'yard');addHeld(s,H[0],'grain',1);storageTitles(s);K.totals.delete('grain');`);return r;});run(P,`consumeOwned(s,H[0],'grain',1)`);});
