import test from 'node:test';
import assert from 'node:assert/strict';
import {realm} from './ownership-fixture.mjs';
import {StorageEventReducer} from './storage-event-reducer.mjs';
function setup(){const r=realm({grain:0,fish:0});r.eval("s.stores.hay=0;storageInit(s);const K=s.storage");return r;}
function replay(r){const R=new StorageEventReducer();for(const e of structuredClone(r.eval('K.events')))R.apply(e);R.compare([structuredClone(r.eval('({settlement:0,lots:[...K.lots.values()].map(l=>K.captureLot(l)),locations:[...K.locations.values()].map(n=>K.locationState(n))})'))]);}
const values=[['bigint','123n',false],['undefined','undefined',true],['NaN','NaN',false],['Infinity','Infinity',false],['negativeInfinity','-Infinity',false],['negativeZero','-0',false],['null','null',true],['finite','7',true],['string',"'batch'",true],['boolean','true',true],['nestedBigInt','{n:123n}',false],['structured',"{note:'future'}",false],['sparseArray','[,undefined]',false]];
for(const [name,value,merge] of values)for(const good of ['grain','hay'])test(`${good} ${name} survives capture, titles and daily boundary`,()=>{const r=setup();r.eval(`const l=K.create('${good}',0.0012,null,'yard');K.annotate(l,{future:${value}});const captured=K.captureLot(l);K.split(l,0.0006);const before=K.events.length;storageTitles(s,'${good}');storageTick(s)`);assert.equal(r.eval(`K.total('${good}')`),0.0012);assert.equal(r.eval('K.lots.size'),merge?1:2);assert.equal(r.eval('Object.hasOwn(captured,"future")'),true);assert.equal(r.eval("typeof l.future==='object'&&l.future!==null ? [...K.lots.values()].every(x=>x.future===l.future) : [...K.lots.values()].every(x=>Object.hasOwn(x,'future')&&Object.is(x.future,captured.future))"),true);if(name==='sparseArray')assert.equal(r.eval('!(0 in captured.future)&&(1 in captured.future)&&captured.future[1]===undefined'),true);if(name==='nestedBigInt')assert.equal(r.eval('captured.future.n'),123n);assert.equal(r.eval("K.events.slice(before).filter(e=>e.cause==='lot-merged').length"),merge?1:0);assert.equal(r.eval("K.events.some(e=>e.cause==='vermin-remnant-loss')"),false);replay(r);});
for(const values of ['[NaN,Infinity,NaN]','[-0,0,-0]'])test('special scalar collision groups are conservatively preserved '+values,()=>{const r=setup();r.eval(`for(const v of ${values}){const l=K.create('grain',1,null,'yard');K.annotate(l,{future:v});}storageTitles(s,'grain');storageTick(s)`);assert.equal(r.eval('K.lots.size'),3);assert.equal(r.s.stores.grain,3);assert.equal(r.eval("K.events.some(e=>e.cause==='lot-merged')"),false);replay(r);});
for(const failing of ['coalesce','certify'])test('failed '+failing+' cannot cache successful titles and retry preserves recorded partial matching',()=>{const r=setup();r.eval("K.create('grain',1,null,'yard');addHeld(s,H[0],'grain',0.5);const nativeCoalesce=K.coalesce;const nativeCertify=storageTitleCertify;let attempts=0;");r.eval(failing==='coalesce'?"K.coalesce=function(){attempts++;throw Error('forced coalesce')}":"storageTitleCertify=function(){attempts++;throw Error('forced certify')}");assert.throws(()=>r.eval("storageTitles(s,'grain')"),/forced/);assert.equal(r.eval("K.titleMatched?.has('grain')||false"),false);assert.equal(r.eval("K.total('grain')"),1);assert.equal(r.eval("pantry(s,H[0]).grain"),0.5);r.eval("K.coalesce=nativeCoalesce;storageTitleCertify=nativeCertify;storageTitles(s,'grain');const afterRetry=K.events.length;storageTitles(s,'grain')");assert.equal(r.eval("K.titleMatched.get('grain')"),r.eval("K.titleRevision?.get('grain')||0"));assert.equal(r.eval('K.events.length'),r.eval('afterRetry'));replay(r);});
