import test from 'node:test';import assert from 'node:assert/strict';import {StorageEventReducer} from './storage-event-reducer.mjs';
const lot={id:'lot:0:1',qty:2,owner:'household:1',metadata:{custom:['a',{x:1}]}};
const setup=()=>{const r=new StorageEventReducer();r.apply({settlement:0,seq:1,locationAfter:{id:'yard',capacity:{$auditNumber:'Infinity'},active:true,custom:undefined}});r.apply({settlement:0,seq:2,lot:lot.id,lotAfter:lot});return r;};
test('all fields and metadata reconstruct',()=>setup().compare([{settlement:0,lots:[lot],locations:[{id:'yard',capacity:{$auditNumber:'Infinity'},active:true,custom:undefined}]}]));
for(const [name,edit]of [['unlogged metadata',l=>l.metadata.custom[1].x++],['missing own field',l=>delete l.owner],['extra own field',l=>l.pendingPurchase=true]])test(name+' is rejected',()=>{const r=setup(),l=structuredClone(lot);edit(l);assert.throws(()=>r.compare([{settlement:0,lots:[l],locations:[{id:'yard',capacity:{$auditNumber:'Infinity'},active:true,custom:undefined}]}]));});
test('cross-settlement identity departure and arrival',()=>{const r=setup();r.apply({settlement:0,seq:3,lot:lot.id,lotAfter:null});r.apply({settlement:1,seq:1,lot:lot.id,lotAfter:lot});r.compare([{settlement:0,lots:[],locations:[{id:'yard',capacity:{$auditNumber:'Infinity'},active:true,custom:undefined}]},{settlement:1,lots:[lot],locations:[]}]);});
test('missing/reordered events are rejected',()=>assert.throws(()=>setup().apply({settlement:0,seq:4}),/Noncontiguous/));
test('location metadata mismatch is rejected',()=>assert.throws(()=>setup().compare([{settlement:0,lots:[lot],locations:[{id:'yard',capacity:{$auditNumber:'Infinity'},active:false,custom:undefined}]}])));
test('one live lot identity cannot exist in two settlements',()=>{const r=setup();r.apply({settlement:1,seq:1,lot:lot.id,lotAfter:lot});assert.throws(()=>r.compare([{settlement:0,lots:[lot],locations:[{id:'yard',capacity:{$auditNumber:'Infinity'},active:true,custom:undefined}]},{settlement:1,lots:[lot],locations:[]}]),/duplicate live lot/);});
