import test from 'node:test';
import assert from 'node:assert/strict';
import {realm} from './ownership-fixture.mjs';
import {baseline} from './storage-active-claims-baseline.mjs';
function restore(program){for(const[n,body]of Object.entries(baseline))program=program.replace(new RegExp('^function '+n+'\\b[\\s\\S]*?(?=^function |^const |^/\\*|$(?![\\s\\S]))','m'),()=>body);return program;}
function count(program){return program.replace('of storageClaimOwners(s,g))for',"of (function*(){for(const pair of storageClaimOwners(s,g)){claimOwnerVisits++;yield pair;}})())for").replace('of s._owners||[])for',"of (function*(){for(const pair of s._owners||[]){claimOwnerVisits++;yield pair;}})())for");}
function pair(empty=0){return [restore,undefined].map(transformSource=>{const r=realm({households:3,grain:0,fish:0,cash:100,bootstrap:'let claimOwnerVisits=0;',transformSource:p=>count(transformSource?transformSource(p):p)});r.eval(`for(let i=0;i<${empty};i++)stockOf(s,{id:10000+i});storageInit(s);const K=s.storage;K.location('a',{capacity:1000});for(let i=0;i<H.length;i++){K.create('grain',3,accountOwner(H[i]),'a','held');addHeld(s,H[i],'grain',3);}storageTitles(s);globalThis.randomCalls=0;globalThis.randomState=123;randi=()=>{randomCalls++;randomState=(Math.imul(randomState,1664525)+1013904223)>>>0;return randomState};`);return r;});}
function state(r){return structuredClone(r.eval("({next:K.next,revision:K.revision,sequence:K.sequence,titleRevision:[...K.titleRevision||[]],titleMatched:[...K.titleMatched||[]],roundoff:[...K.roundoff],lots:[...K.lots.values()].map(l=>K.lotState(l)),locations:[...K.locations.values()].map(l=>K.locationState(l)),events:K.events,byGood:[...K.byGood].map(([k,v])=>[k,[...v]]),byOwner:[...K.byOwner].map(([k,v])=>[storageOwnerId(k),[...v]]),byAvailability:[...K.byAvailability].map(([k,v])=>[k,[...v]]),claims:[...s._owners].map(([k,x])=>[storageOwnerId(k),{...x.held},{...x.sale},{...x.reserve},{...x.animals}]),coins:H.map(h=>h.w),treasury:W.treasury,randomState,randomCalls,households:[...W.households?.values()||[]].map(h=>({id:h.id,head:h.head?.id,members:[...h.members].map(p=>p.id),population:[...h.population].map(([t,n])=>[W.settlements.indexOf(t),n])}))})"));}
function run(P,expr){const results=P.map(r=>{try{return {value:r.eval(expr)}}catch(e){return {name:e.name,message:e.message}}});assert.deepEqual(results[1],results[0]);assert.deepEqual(state(P[1]),state(P[0]));}
for(const n of [0,1000,10000])test(`active collection skips ${n} empty archived owners with exact outcomes`,()=>{const P=pair(n);for(const r of P)r.eval("claimOwnerVisits=0");run(P,"pantry(s,H[0]).grain=2.5;pantry(s,H[1]).grain=3.5;storageTitles(s,'grain');undefined");assert.equal(P[0].eval('claimOwnerVisits'),n+3);assert.equal(P[1].eval('claimOwnerVisits'),3);const r=P[1];assert.equal(r.eval("STORAGE_ACTIVE_CLAIMS.get(s).fallback"),false);assert.equal(r.eval("storageClaimOwners(s,'grain').length"),3);assert.equal(r.eval('s._owners.size'),n+3);assert.equal(r.eval("storageClaimOwners(s,'fish').length"),0);});
test('dynamic owners, held-before-sale and char/timber claims preserve insertion order',()=>{const P=pair(50);run(P,"const newOwner={id:8888};addHeld(s,newOwner,'grain',1e-13);pantry(s,H[0]).grain-=1e-13;offer(s,'grain',H[1],1);storageTitles(s,'grain');undefined");assert.equal(P[1].eval('STORAGE_ACTIVE_CLAIMS.get(s).fallback'),false);run(P,"s.stores.timber=4;K.create('timber',4,null,'yard');addHeld(s,H[0],'char',1);addHeld(s,H[1],'timber',2);offer(s,'timber',H[2],1);storageTitles(s,'timber');undefined");});
test('definition/deletion, zero, negative, NaN and tiny values update activity exactly',()=>{const P=pair();for(const expr of ["delete pantry(s,H[0]).grain", "Object.defineProperty(pantry(s,H[0]),'grain',{value:1e-13,writable:true,enumerable:true,configurable:true})", "pantry(s,H[0]).grain=NaN", "pantry(s,H[0]).grain=-1", "pantry(s,H[0]).grain=0", "pantry(s,H[0]).grain=3"]){run(P,expr+";storageTitles(s,'grain');undefined");assert.equal(P[1].eval('STORAGE_ACTIVE_CLAIMS.get(s).fallback'),false);}});
test('managed table replacement retains activity and unknown replacement falls back',()=>{const P=pair();run(P,"storageClaimReplace(stockOf(s,H[0]),'held',{grain:2});pantry(s,H[1]).grain=4;storageTitles(s,'grain');undefined");assert.equal(P[1].eval('STORAGE_ACTIVE_CLAIMS.get(s).fallback'),false);run(P,"stockOf(s,H[0]).held={grain:1};storageTitles(s,'grain');undefined");assert.equal(P[1].eval('STORAGE_ACTIVE_CLAIMS.get(s).fallback'),true);});
test('public dirty, custom native map methods and size drift use original scan',()=>{for(const expr of ["storageTitleDirty(s,'grain')", "s._owners.set({id:99999},{held:{grain:1},sale:{},reserve:{},animals:{}});storageTitleKnownDirty(s,'grain')", "s._owners.get=function(k){return Map.prototype.get.call(this,k)};storageTitleKnownDirty(s,'grain')"]){const P=pair();run(P,expr+";storageTitles(s,'grain');undefined");assert.equal(P[1].eval("storageClaimOwners(s,'grain')===s._owners"),true);}});
test('accessor-backed claim read order and throwing arithmetic use original behavior',()=>{const P=pair();run(P,"let reads=0;Object.defineProperty(pantry(s,H[0]),'grain',{get(){reads++;return 3},configurable:true,enumerable:true});storageTitles(s,'grain');reads");assert.equal(P[1].eval("storageClaimOwners(s,'grain')===s._owners"),true);run(P,"pantry(s,H[1]).grain=Symbol('bad')");});
test('false pending metadata and observer interleavings retain historical custody and later dirties',()=>{const P=pair();run(P,"K.annotate([...K.lots.values()][0],{pendingPurchase:false,negativeZero:-0,optional:undefined});pantry(s,H[0]).grain=2;pantry(s,H[1]).grain=4;storageTitles(s,'grain');undefined");run(P,"const transfer0=K.transfer;let once=true;K.transfer=function(...args){const v=transfer0.apply(this,args);if(once){once=false;pantry(s,H[2]).grain=2;}return v};pantry(s,H[0]).grain=0;storageTitles(s,'grain');storageTitleKnownDirty(s,'grain');storageTitles(s,'grain');undefined");});
test('custom public dirty callback retains original argument count',()=>{const P=pair();run(P,"const dirty0=storageTitleDirty;let arities=[];storageTitleDirty=function(s,g){arities.push(arguments.length);return dirty0(s,g)};pantry(s,H[0]).grain=2;storageTitles(s,'grain');arities.join(',')");});
test('inheritance, marriage and household growth preserve retained archives and exact outcomes',()=>{const P=pair(100);run(P,"H[0].kids=[H[1],H[2]];H[1].pa=H[0];H[2].pa=H[0];H[1].own=H[2].own=true;transferOwnership(accountOwner(H[0]),[[accountOwner(H[1]),.3],[accountOwner(H[2]),.7]]);storageTitles(s,'grain');undefined");assert.equal(P[1].eval('STORAGE_ACTIVE_CLAIMS.get(s).fallback'),false);run(P,"const child={id:9,gn:'child',age:8,si:0,ma:H[1],w:0};H.push(child);s.folk.push(child);consumeOwned(s,child,'grain',.125);householdPortion(child,.15);addHeld(s,child,'grain',.5);storageTitles(s,'grain');undefined");run(P,"marryHouseholds(H[1],H[2]);storageTitles(s,'grain');undefined");assert.equal(P[1].eval('STORAGE_ACTIVE_CLAIMS.get(s).fallback'),false);});
test('unknown null-prototype claim tables decline admission',()=>{const P=pair();run(P,"const table=Object.create(null);table.grain=1;stockOf(s,H[0]).held=table;storageTitles(s,'grain');undefined");assert.equal(P[1].eval('STORAGE_ACTIVE_CLAIMS.get(s).fallback'),true);});

test('cross-realm owner Map replacement uses original scan',()=>{const P=pair();for(const r of P)r.s._owners=new Map(r.s._owners);run(P,"storageTitleKnownDirty(s,'grain');storageTitles(s,'grain');undefined");assert.equal(P[1].eval("storageClaimOwners(s,'grain')===s._owners"),true);});
test('actual audit observer reentrant dirty, replacement and owner admission preserve ordered outcomes',()=>{const P=pair(100);run(P,"let observed=[];let observerOnce=true;storageOutcome=function(e){storageObserveOutcome(e);K.events.push(e)};FURLONG_STORAGE_AUDIT_OBSERVER=function(e){observed.push([e.seq,e.cause]);if(observerOnce&&e.cause==='title-transfer'){observerOnce=false;stockOf(s,H[2]).held={grain:2};addHeld(s,{id:7654},'grain',1,true);storageTitleDirty(s,'grain');}};pantry(s,H[0]).grain=0;pantry(s,H[1]).grain=6;storageTitles(s,'grain');storageTitles(s,'grain');JSON.stringify(observed)");assert.equal(P[1].eval('observerOnce'),false);assert.equal(P[1].eval('STORAGE_ACTIVE_CLAIMS.get(s).fallback'),true);});

test('matching and consumption leave RNG continuation identical',()=>{const P=pair(1000);run(P,"consumeOwned(s,H[0],'grain',.125);pantry(s,H[1]).grain=2.5;pantry(s,H[2]).grain=3.5;storageTitles(s,'grain');Array.from({length:10},()=>randi()).join(',')");});

test('active matching protects true pending custody alongside valid settled claims',()=>{const r=pair()[1];r.eval("const p=K.split([...K.lots.values()][0],2);K.annotate(p,{pendingPurchase:true,negativeZero:-0,optional:undefined});pantry(s,H[0]).grain=1;storageTitles(s,'grain')");assert.equal(r.eval('p.pendingPurchase'),true);assert.equal(r.eval('p.qty'),2);assert.equal(r.eval('p.owner===accountOwner(H[0])'),true);assert.equal(r.eval('STORAGE_ACTIVE_CLAIMS.get(s).fallback'),false);assert.equal(r.eval("storageClaimOwners(s,'grain').length"),3);assert.equal(r.eval('K.events.some(e=>e.cause===\"unbacked-title\")'),false);});
