import test from 'node:test';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {realm} from './ownership-fixture.mjs';
const parent=execFileSync('git',['show','40492fc:index.html'],{encoding:'utf8',maxBuffer:20e6});
const oldMatch=parent.slice(parent.indexOf('function storageTitles('),parent.indexOf('\nfunction storageTick('));
function pair(households=4){return[true,false].map(old=>{const r=realm({households,grain:0,fish:0,cash:100,crown:1000});if(old)r.eval(oldMatch);r.eval("storageInit(s);const K=s.storage;K.location('a',{capacity:1000});K.location('b',{capacity:1000});for(let i=0;i<H.length;i++){K.create('grain',3,accountOwner(H[i]),i%2?'a':'b','held');addHeld(s,H[i],'grain',3);}storageTitles(s)");return r;});}
function state(r){return structuredClone(r.eval("({next:K.next,revision:K.revision,sequence:K.sequence,roundoff:[...K.roundoff],lots:[...K.lots.values()].map(l=>K.lotState(l)),locations:[...K.locations.values()].map(l=>K.locationState(l)),events:K.events,byGood:[...K.byGood].map(([k,v])=>[k,[...v]]),byOwner:[...K.byOwner].map(([k,v])=>[storageOwnerId(k),[...v]]),byAvailability:[...K.byAvailability].map(([k,v])=>[k,[...v]]),claims:[...s._owners].map(([k,x])=>[storageOwnerId(k),{...x.held},{...x.sale}])})"));}
function run(P,expr){for(const r of P)r.eval(expr);assert.deepEqual(state(P[1]),state(P[0]));}
test('exact certified groups bypass only mutations already proven no-ops',()=>{const P=pair(50);for(const r of P)r.eval("let annotations=0;const annotate=K.annotate;K.annotate=function(...args){annotations++;return annotate.apply(this,args)};storageTitleDirty(s,'grain');storageTitles(s,'grain')");assert.deepEqual(state(P[1]),state(P[0]));assert.equal(P[0].eval('annotations'),50);assert.equal(P[1].eval('annotations'),0);});
test('changing claims and custody preserves the exact parent event stream and lot identity',()=>{const P=pair();run(P,"pantry(s,H[0]).grain=2.5;pantry(s,H[1]).grain=3.5;storageTitles(s,'grain')");run(P,"K.move([...K.lots.values()].find(l=>l.owner===accountOwner(H[2])),'yard',.7);storageTitleDirty(s,'grain');storageTitles(s,'grain')");run(P,"for(let i=0;i<20;i++){consumeOwned(s,H[i%4],'grain',.01);storageTitleDirty(s,'grain');storageTitles(s,'grain')}");});
test('pending properties, future metadata and location changes invalidate conservatively',()=>{const P=pair();run(P,"const l=[...K.lots.values()][0];K.annotate(l,{condition:{wet:true},optional:undefined,negativeZero:-0,pendingPurchase:false});storageTitleDirty(s,'grain');storageTitles(s,'grain')");run(P,"K.destroy('a');storageTitleDirty(s,'grain');storageTitles(s,'grain')");});
test('tiny positive residuals retain exact splits, transfers and roundoff outcomes',()=>{const P=pair();run(P,"pantry(s,H[0]).grain-=1e-12;pantry(s,H[1]).grain+=1e-12;storageTitles(s,'grain')");run(P,"K.create('grain',1e-13,null,'yard');addHeld(s,H[2],'grain',1e-13);storageTitles(s,'grain')");});
test('claim deletion, definition and replacement retain fallback semantics',()=>{const P=pair();run(P,"delete pantry(s,H[0]).grain;storageTitles(s,'grain');Object.defineProperty(pantry(s,H[0]),'grain',{value:3,writable:true,enumerable:true,configurable:true});storageTitles(s,'grain')");run(P,"stockOf(s,H[0]).held={grain:2};stockOf(s,H[1]).held={grain:4};storageTitles(s,'grain')");});
test('purchase and charity completion retain every genuine mutation in order',()=>{const P=pair();run(P,"pantry(s,H[0]).grain=0;offer(s,'grain',H[0],3);storageTitles(s,'grain');purchase(s,'grain',H[1],1,1);giveFood(s,'grain',purchase.got,H[1]);storageTitles(s,'grain')");});
test('certificates live outside authoritative and snapshot-owned ledger fields',()=>{const P=pair();assert.deepEqual(Object.keys(P[1].eval('K')),Object.keys(P[0].eval('K')));run(P,"storageTitleDirty(s,'grain');storageTitles(s,'grain')");});
