import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {Worker} from 'node:worker_threads';
import {webcrypto} from 'node:crypto';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const core=html.split('// STORAGE OUTCOME JOURNAL BEGIN')[1].split('// STORAGE OUTCOME JOURNAL END')[0];
function fixture(){const c=vm.createContext({setTimeout,clearTimeout});vm.runInContext(core+';globalThis.Raw=RawOutcomeJournal;globalThis.Pipeline=OutcomeWorkerPipeline;globalThis.Client=OutcomeWorkerClient;globalThis.decode=outcomeRecords;globalThis.json=outcomeJSON;globalThis.source=outcomeWorkerSource;globalThis.capture=outcomeTransportCapture;globalThis.restore=outcomeTransportRestore;globalThis.binaryEncode=outcomeBinaryEncode;globalThis.binaryDecode=outcomeBinaryDecode;globalThis.binaryValidate=outcomeBinaryValidate',c);return c;}
const workerAdapter=`
const {parentPort}=require('node:worker_threads');const {webcrypto}=require('node:crypto');globalThis.crypto=webcrypto;globalThis.self=globalThis;
const games=new Map(),chunks=new Map();let failChunk=null;
const db={createObjectStore(){},transaction(names){const pending=[],tx={error:null,objectStore(name){return{put(value,key){pending.push({name,key,value});}}},abort(){tx.error=Error('aborted');setImmediate(()=>tx.onabort?.());}};setImmediate(()=>{const entry=pending.find(x=>x.name==='chunks');if(entry&&entry.key[1]===failChunk){tx.error=Error('injected atomic write failure');tx.onabort?.();return;}for(const p of pending)(p.name==='games'?games:chunks).set(JSON.stringify(p.key),p.value);tx.oncomplete?.();});return tx;}};
globalThis.indexedDB={open(){const request={result:db};setImmediate(()=>request.onsuccess());return request;}};
globalThis.postMessage=message=>parentPort.postMessage({...message,testChunks:[...chunks.values()],testGames:[...games.values()]});
parentPort.on('message',data=>{if(data.testFailChunk!==undefined)failChunk=data.testFailChunk;globalThis.onmessage({data});});
`;
function thread(c,failChunk,ondata){const worker=new Worker(workerAdapter+'\n'+c.source()+(c.codecForbidden?'\nOutcomeCodec.prototype.encode=()=>{throw Error("canonical codec forbidden")};':''),{eval:true});const adapter={postMessage(data,transfer){worker.postMessage(failChunk===undefined?data:{...data,testFailChunk:failChunk},transfer);},terminate(){return worker.terminate();}};worker.on('message',data=>{ondata?.(data);adapter.onmessage?.({data});});worker.on('error',error=>adapter.onerror?.({message:error.message}));return adapter;}
async function workerJournal(c,{failChunk,chunkBytes=7000,mode='native-storage-v3'}={}){const adapter=thread(c,failChunk),client=new c.Client(adapter,{timeout:5000});const meta={id:'test',lastChunk:-1,lastSeq:-1,lastHash:null,storedBytes:0,encodedBytes:0};await client.request({type:'init',meta,mode});const acks=[],j=new c.Raw(async entry=>{const ack=await client.request({type:'chunk',mode,entry});acks.push(ack);return ack;},{chunkBytes});return{adapter,client,acks,j};}
async function durable(c,acks){const rows=[];let previous=null,expected=0;for(const chunk of acks.at(-1)?.testChunks||[]){const buffer=await new Response(chunk.blob.stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();assert.equal(chunk.previous,previous);assert.equal(chunk.first,expected);assert.equal(Buffer.from(await webcrypto.subtle.digest('SHA-256',buffer)).toString('hex'),chunk.hash);const decoded=chunk.encoding==='native-storage-v3'?Array.from(c.binaryDecode(buffer),row=>{row.event=c.restore(row.event);return row;}):[...c.decode(new TextDecoder().decode(buffer))];for(const row of decoded)assert.equal(row.seq,expected++);assert.equal(chunk.last,expected-1);rows.push(...decoded);previous=chunk.hash;}return rows;}
test('raw accepted stream equals atomic worker durable stream, including opaque handles and event-time metadata',async()=>{const c=fixture();const capture=html.slice(html.indexOf('const STORAGE_CAPTURE_DATA='),html.indexOf('class StorageLedger {'));vm.runInContext("const STORAGE_OUTCOMES={journal:{mode:'compact'}};function storageOwnerId(o){return o??'unassigned'};"+capture,c);const t=await workerJournal(c);c.j=t.j;
 try{vm.runInContext(`globalThis.expected=[];const lot={id:'lot:test',owner:'household:1',qty:1e-300,good:'grain',location:'yard',availability:'held'};for(let i=0;i<30;i++){const before=storageLotHandle(lot);lot.qty=i%2?-0:1e-300;lot.meta={missing:undefined,nan:NaN,inf:Infinity,big:123n,array:[,undefined],reserved:{$ref:'literal'}};Object.defineProperty(lot.meta,'__proto__',{value:i,enumerable:false,configurable:true});const e={seq:i,kind:'storage',lot:lot.id,owner:lot.owner,qtyAfter:lot.qty,lotAfter:storageLotHandle(lot),before};expected.push(outcomeJSON({seq:i,event:storageExpandOutcome(e)}));j.append(e);lot.meta.nan=9;}globalThis.accepted=[...j.uncommitted()].map(json);`,c);assert.deepEqual(Array.from(c.accepted),Array.from(c.expected));await t.j.flush();const records=await durable(c,t.acks);assert.deepEqual(records.map(c.json),Array.from(c.expected));assert.equal(t.j.pending.size,0);assert.equal(t.j.committed,29);const ack=t.acks.at(-1);assert.equal(ack.meta.lastSeq,29);assert.equal(ack.testGames[0].lastSeq,29);assert.ok(t.acks.length>1);}finally{t.client.close();}}
);
test('append captures immutable raw data without main-thread codec or JSON encoding',async()=>{const c=fixture(),writes=[];const pipeline=new c.Pipeline(async entry=>{writes.push(entry);return{};});const j=new c.Raw(entry=>pipeline.process(entry),{chunkBytes:1e9});c.j=j;vm.runInContext("globalThis.original=OutcomeCodec.prototype.encode;OutcomeCodec.prototype.encode=()=>{throw Error('synchronous encode')};globalThis.e={nested:{a:1},array:[,undefined]};j.append(e);e.nested.a=2;",c);assert.equal([...j.uncommitted()][0].event.nested.a,1);assert.equal(j.encodedCharacters,0);vm.runInContext('OutcomeCodec.prototype.encode=original',c);await j.flush();assert.equal(writes.length,1);});
test('capture rejects unsupported/accessor data without sequence advance and retains accepted tail',async()=>{const c=fixture(),j=new c.Raw(async()=>{});c.j=j;vm.runInContext("j.append(Object.assign(Object.create(null),{n:1}));globalThis.bad={};Object.defineProperty(bad,'x',{get(){throw Error('getter ran')}})",c);assert.throws(()=>j.append(c.bad),/accessor/);assert.equal(j.seq,1);assert.equal(j.ready,false);assert.deepEqual([...j.uncommitted()].map(x=>x.event.n),[1]);assert.throws(()=>j.append(Object.assign(Object.create(null),{n:2})),/accessor/);});
test('pending backpressure retains all records until an atomic writer acknowledgement',async()=>{const c=fixture(),gates=[];const j=new c.Raw(entry=>new Promise(resolve=>gates.push({entry,resolve})),{chunkBytes:1,maxPendingBytes:1});j.append(Object.assign(Object.create(null),{n:1}));j.append(Object.assign(Object.create(null),{n:2}));assert.equal(j.ready,false);await Promise.resolve();assert.equal(gates.length,1);assert.equal(j.pending.size,2);gates[0].resolve({chunk:0,first:0,last:0});await new Promise(setImmediate);assert.equal(gates.length,2);assert.equal(j.committed,0);assert.equal(j.pending.size,1);gates[1].resolve({chunk:1,first:1,last:1});await j.flush();assert.equal(j.bytes,0);assert.equal(j.ready,true);});
test('injected worker atomic write failure preserves prefix and entire pending tail without duplicates',async()=>{const c=fixture(),t=await workerJournal(c,{failChunk:1,chunkBytes:1});try{t.j.append(Object.assign(Object.create(null),{n:1}));t.j.append(Object.assign(Object.create(null),{n:2}));t.j.append(Object.assign(Object.create(null),{n:3}));await assert.rejects(t.j.flush(),/injected atomic/);assert.equal(t.j.committed,0);assert.equal(t.j.pending.size,2);assert.deepEqual([...t.j.uncommitted()].map(x=>[x.seq,x.event.n]),[[1,2],[2,3]]);const rows=await durable(c,t.acks);assert.deepEqual(rows.map(x=>[x.seq,x.event.n]),[[0,1]]);assert.equal(t.acks[0].testGames[0].lastSeq,0);assert.throws(()=>t.j.append(Object.assign(Object.create(null),{n:4})),/injected atomic/);}finally{t.client.close();}});
test('out-of-order or duplicate worker batches never duplicate durable records',async()=>{const c=fixture(),writes=[];const pipeline=new c.Pipeline(async entry=>{writes.push(entry);return{};});const packet=c.capture(Object.assign(Object.create(null),{n:1})).value,entry={chunk:0,first:0,last:0,records:[{seq:0,event:packet}]};await pipeline.process(entry);await assert.rejects(pipeline.process(entry),/batch gap/);assert.equal(writes.length,1);await assert.rejects(pipeline.process({...entry,chunk:1,first:1,last:1}),/batch gap/);});
test('worker crashes and malformed acknowledgements preserve raw pending tail and sticky faults',async()=>{const c=fixture();let adapter={postMessage(){},terminate(){}};const client=new c.Client(adapter,{timeout:1000}),j=new c.Raw(entry=>client.request({type:'chunk',entry}),{chunkBytes:1});j.append(Object.assign(Object.create(null),{n:1}));await Promise.resolve();adapter.onerror({message:'worker crashed'});await assert.rejects(j.flush(),/worker crashed/);assert.equal(j.committed,-1);assert.deepEqual([...j.uncommitted()].map(x=>x.event.n),[1]);assert.throws(()=>j.append(Object.assign(Object.create(null),{n:2})),/worker crashed/);const mismatch=new c.Raw(async()=>({chunk:99,first:0,last:0}),{chunkBytes:1});mismatch.append(Object.assign(Object.create(null),{n:1}));await assert.rejects(mismatch.flush(),/acknowledgement differs/);assert.equal(mismatch.pending.size,1);});
test('transport preserves null prototype, ordered own fields and holes across structured clone',()=>{const c=fixture();vm.runInContext("globalThis.e=Object.create(null);Object.defineProperty(e,'__proto__',{value:[,undefined],enumerable:false});e.negative=-0;e.optional=undefined;globalThis.packet=capture(e).value",c);const restored=c.restore(structuredClone(c.packet));assert.equal(Object.getPrototypeOf(restored),null);assert.deepEqual(Reflect.ownKeys(restored),['__proto__','negative','optional']);assert.equal(0 in restored.__proto__,false);assert.equal(1 in restored.__proto__,true);assert.ok(Object.is(restored.negative,-0));});
test('malformed worker messages fail immediately and reject every pending request',async()=>{const c=fixture(),adapter={postMessage(){},terminate(){}},client=new c.Client(adapter,{timeout:1000});const promise=client.request({type:'init'});adapter.onmessage({data:null});assert.match(client.fault.message,/Invalid storage worker acknowledgement/);await assert.rejects(promise,/Invalid storage worker acknowledgement/);assert.equal(client.requests.size,0);});
test('worker eager dispatch starts every raw batch during the producing tick while retaining ownership',async()=>{const c=fixture(),gates=[];const j=new c.Raw(entry=>new Promise(resolve=>gates.push({entry,resolve})),{chunkBytes:1,eager:true});j.append(Object.assign(Object.create(null),{n:1}));j.append(Object.assign(Object.create(null),{n:2}));assert.equal(gates.length,2);assert.equal(j.pending.size,2);assert.equal(j.committed,-1);for(const {entry,resolve}of gates)resolve({chunk:entry.chunk,first:entry.first,last:entry.last});await j.flush();assert.equal(j.pending.size,0);});
test('day-boundary backpressure dispatches a short unfinished batch without waiting for timer',async()=>{const c=fixture(),gates=[],j=new c.Raw(entry=>new Promise(resolve=>gates.push({entry,resolve})),{chunkBytes:1e9,maxPendingBytes:1,eager:true});j.append(Object.assign(Object.create(null),{n:1}));assert.equal(gates.length,0);assert.equal(j.ready,false);assert.equal(gates.length,1);assert.equal(j.pending.size,1);gates[0].resolve({chunk:0,first:0,last:0});await j.flush();assert.equal(j.ready,true);});
function browserFixture({foreground=false,failChunk,loseAckChunk}={}){const c=fixture(),games=new Map(),chunks=new Map(),adapters=[];const key=k=>JSON.stringify(k),db={transaction(){const puts=[],tx={objectStore(name){const map=name==='games'?games:chunks;return{put(value,k){puts.push(()=>map.set(key(k),value));},get(k){const request={};setImmediate(()=>{request.result=map.get(key(k));request.onsuccess?.();});return request;},getAll(){const request={};setImmediate(()=>{request.result=[...map.values()];request.onsuccess?.();});return request;}}}};setImmediate(()=>{for(const put of puts)put();tx.oncomplete?.();});return tx;}};
 Object.assign(c,{crypto:webcrypto,TextEncoder,TextDecoder,Blob,Response,CompressionStream,DecompressionStream,ReadableStream,URL:{createObjectURL(){return'test-blob';},revokeObjectURL(){}},indexedDB:{open(){const request={result:db};setImmediate(()=>request.onsuccess?.());return request;}},document:{querySelectorAll(){return[{type:'',src:'',textContent:'source'}];}},console:{warn(){},error(){}},setSpeed(){},storageFaultNotice(){},worldHash(){return's=1001';},day(){return 390;},W:{},FURLONG_STORAGE_FOREGROUND_AUDIT:foreground});c.Worker=function(){const adapter=thread(c,failChunk,data=>{if(data.meta)data.meta=vm.runInContext('('+JSON.stringify(data.meta)+')',c);if(data.type==='committed'&&data.chunk===loseAckChunk){setImmediate(()=>adapter.onmessage({data:null}));data.type='error';data.message='Injected acknowledgement loss after commit';}for(const meta of data.testGames||[])games.set(key(meta.id),meta);const meta=data.testGames?.[0];if(meta)for(let i=0;i<(data.testChunks?.length||0);i++)chunks.set(key([meta.id,i]),data.testChunks[i]);});adapters.push(adapter);return adapter;};const start=html.indexOf('const STORAGE_LEGACY_AUDIT='),end=html.indexOf('\nfunction storageOutcome(',start);vm.runInContext(html.slice(start,end)+';globalThis.log=STORAGE_OUTCOMES',c);return{c,adapters};}
test('browser owner integration defaults to worker and exports exact durable prefix plus failed pending tail',async()=>{const {c,adapters}=browserFixture({failChunk:1});try{await c.log.begin();c.log.journal.chunkBytes=1;await c.log.flush();vm.runInContext("log.journal.append({n:1});log.journal.append({n:2});",c);await assert.rejects(c.log.flush(),/injected atomic/);assert.equal(c.log.status().processingMode,'worker');const rows=[];for await(const record of c.log.records())rows.push(record);assert.deepEqual(rows.map(x=>[x.seq,x.event.kind||x.event.n]),[[0,'begin'],[1,1],[2,2]]);assert.equal(c.log.meta.lastSeq,0);assert.equal(c.log.journal.pending.size,2);}finally{for(const adapter of adapters)adapter.terminate();}});
test('explicit foreground diagnostic reports its mode and preserves the same reader/export contract',async()=>{const {c,adapters}=browserFixture({foreground:true});try{await c.log.begin();vm.runInContext("log.journal.append({n:-0,optional:undefined,array:[,undefined]})",c);await c.log.flush();assert.equal(c.log.status().processingMode,'foreground-fallback');assert.equal(c.log.status().fallbackReason,'Foreground audit requested');const rows=[];for await(const record of c.log.records())rows.push(record);assert.equal(rows.length,2);assert.ok(Object.is(rows[1].event.n,-0));assert.equal(0 in rows[1].event.array,false);assert.equal(1 in rows[1].event.array,true);}finally{for(const adapter of adapters)adapter.terminate();}});
test('uncertain commit acknowledgement exports each accepted event once and independently opens durable prefix',async()=>{const {c,adapters}=browserFixture({loseAckChunk:1});try{await c.log.begin();c.log.journal.chunkBytes=1;await c.log.flush();vm.runInContext("log.journal.append({n:1});log.journal.append({n:2});",c);await assert.rejects(c.log.flush(),/acknowledgement loss/);const exported=[];for await(const row of c.log.records())exported.push([row.seq,row.event.kind||row.event.n]);assert.deepEqual(exported,[[0,'begin'],[1,1],[2,2]]);const saved=await c.log.open(c.log.meta.id),disk=[];for await(const row of saved.records())disk.push([row.seq,row.event.kind||row.event.n]);assert.ok(disk.length>=2);assert.deepEqual(disk,exported.slice(0,disk.length));}finally{for(const adapter of adapters)adapter.terminate();}});
test('ordered transport schemas share batch key vectors without conflating key order',()=>{const c=fixture();vm.runInContext("const first={a:1,b:2},second={a:3,b:4},reordered={b:4,a:3};globalThis.p1=capture(first).value;globalThis.p2=capture(second).value;globalThis.p3=capture(reordered).value",c);assert.equal(c.p1.keys,c.p2.keys);assert.notEqual(c.p1.keys,c.p3.keys);assert.deepEqual(Reflect.ownKeys(c.restore(structuredClone(c.p3))),['b','a']);});
test('private owned-handle transport retains event-time metadata and independent pending exports',()=>{const c=fixture();const captureCore=html.slice(html.indexOf('const STORAGE_CAPTURE_DATA='),html.indexOf('class StorageLedger {'));vm.runInContext("const STORAGE_OUTCOMES={journal:{mode:'compact'}};function storageOwnerId(o){return o??'unassigned'};"+captureCore+';globalThis.j=new RawOutcomeJournal(async()=>{});const lot={id:"lot:owned",owner:"household:1",qty:1,meta:{nested:{n:1},holes:[,undefined]}};j.append({lotAfter:storageLotHandle(lot)});lot.meta.nested.n=2;globalThis.first=[...j.uncommitted()][0];first.event.lotAfter.meta.nested.n=99;globalThis.second=[...j.uncommitted()][0];',c);assert.equal(c.second.event.lotAfter.meta.nested.n,1);assert.equal(0 in c.second.event.lotAfter.meta.holes,false);assert.equal(1 in c.second.event.lotAfter.meta.holes,true);});

test('binary wire preserves UTF16, special values, holes, keys, references and rejects malformed bytes',()=>{const c=fixture();vm.runInContext("const obj=Object.create(null);Object.defineProperty(obj,'__proto__',{value:[,undefined],enumerable:false});obj.s='\\ud800';obj.n=-0;obj.nan=NaN;obj.big=123n;globalThis.rows=[{seq:0,event:capture(obj).value},{seq:1,event:capture(obj).value}];globalThis.binary=binaryEncode(rows);globalThis.roundtrip=binaryDecode(binary);",c);assert.equal(c.json(c.restore(c.roundtrip[0].event)),c.json(c.restore(c.rows[0].event)));assert.throws(()=>c.binaryDecode(c.binary.slice(0,-1)),/Truncated/);});
test('binary worker commits reused engine events and snapshots mutable extras with independent fault tails',async()=>{const c=fixture();const captureCore=html.slice(html.indexOf('const STORAGE_CAPTURE_DATA='),html.indexOf('class StorageLedger {'));vm.runInContext("const STORAGE_OUTCOMES={journal:{mode:'compact'}};function storageOwnerId(o){return o??'unassigned'};"+captureCore,c);const t=await workerJournal(c);c.j=t.j;try{vm.runInContext("const lot={id:'lot:reuse',owner:'household:1',qty:-0};const first=Object.freeze({lotAfter:storageLotHandle(lot),n:undefined,text:'\\ud800'});STORAGE_CAPTURE_DATA.add(first);j.append(first);const nested={n:1,type:'array',keys:['x'],values:[7],extra:'retained'};const second=Object.freeze({lotAfter:storageLotHandle(lot),nested});STORAGE_CAPTURE_DATA.add(second);j.append(second);nested.n=99;globalThis.expected=[...j.uncommitted()].map(json);globalThis.reused=capture(first).value.type;",c);assert.equal(c.reused,'engine-event');await t.j.flush();assert.deepEqual((await durable(c,t.acks)).map(c.json),Array.from(c.expected));}finally{t.client.close();}});
test('sealed batches retain only independent binary bytes and transferable copies detach without losing fault tail',async()=>{const c=fixture();const adapter={postMessage(data,transfer){if(data.type==='chunk')structuredClone(data,{transfer});},terminate(){}},client=new c.Client(adapter,{timeout:1000});const j=new c.Raw(entry=>client.request({type:'chunk',entry}),{chunkBytes:1,eager:true});j.append(Object.assign(Object.create(null),{n:1,array:[,undefined],s:'\ud800'}));const retained=j.pending.get(0);assert.equal(retained.records,undefined);assert.ok(retained.binary.byteLength>0);assert.equal(j.bytes,retained.binary.byteLength+512);adapter.onerror({message:'failed after transfer'});await assert.rejects(j.flush(),/failed after transfer/);assert.deepEqual([...j.uncommitted()].map(r=>[r.seq,r.event.n]),[[0,1]]);assert.equal([...j.uncommitted()][0].event.s,'\ud800');client.close();});
test('binary seal failure retains every accepted unsealed row and stops later appends',()=>{const c=fixture();vm.runInContext("globalThis.j=new RawOutcomeJournal(async()=>{},{chunkBytes:1e9});j.append({n:1});outcomeBinaryEncode=()=>{throw Error('injected binary encode failure')};j.seal();",c);assert.equal(c.j.seq,1);assert.equal(c.j.pending.size,0);assert.equal(c.j.rows.length,1);assert.deepEqual([...c.j.uncommitted()].map(r=>r.event.n),[1]);assert.throws(()=>c.j.append(Object.assign(Object.create(null),{n:2})),/injected binary/);});
test('engine-marked frozen arrays retain their array shape',()=>{const c=fixture(),captureCore=html.slice(html.indexOf('const STORAGE_CAPTURE_DATA='),html.indexOf('class StorageLedger {'));vm.runInContext("const STORAGE_OUTCOMES={journal:{mode:'compact'}};function storageOwnerId(o){return o??'unassigned'};"+captureCore+";globalThis.packet=capture(storageImmutableCapture([1,2])).value;globalThis.restored=restore(binaryDecode(binaryEncode([{seq:0,event:packet}]))[0].event)",c);assert.equal(Array.isArray(c.restored),true);assert.deepEqual(Array.from(c.restored),[1,2]);});

test('native archive commits exact bytes without canonical codec and reports truthful encoding metrics',async()=>{const c=fixture();c.codecForbidden=true;const t=await workerJournal(c,{chunkBytes:1});try{const event=Object.assign(Object.create(null),{n:-0,s:'\ud800',missing:undefined,huge:123n,nan:NaN,inf:Infinity,array:[,undefined]});t.j.append(event);const retained=t.j.pending.get(0).binary,expectedBytes=retained.byteLength;await t.j.flush();const ack=t.acks[0],chunk=ack.testChunks[0];assert.equal(ack.meta.version,3);assert.equal(ack.meta.encoding,'native-storage-v3');assert.equal(chunk.encoding,'native-storage-v3');assert.equal(ack.encodedCharacters,0);assert.equal(t.j.encodedCharacters,0);assert.equal(ack.meta.encodedBytes,expectedBytes);const actual=await new Response(chunk.blob.stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();assert.deepEqual(new Uint8Array(actual),new Uint8Array(retained));c.expectedEvent=event;vm.runInContext('globalThis.expectedNative=json({seq:0,event:expectedEvent})',c);assert.equal((await durable(c,t.acks)).map(c.json)[0],c.expectedNative);}finally{t.client.close();}});
test('binary sequence validation rejects count, sequence, framing and encoder gaps',()=>{const c=fixture();vm.runInContext("globalThis.buffer=binaryEncode([{seq:5,event:capture({n:1}).value}]);",c);assert.equal(c.binaryValidate(c.buffer,5,5),1);assert.throws(()=>c.binaryValidate(c.buffer,5,6),/record count/);const wrong=c.buffer.slice(0);new DataView(wrong).setFloat64(5,6,true);assert.throws(()=>c.binaryValidate(wrong,5,5),/record gap/);assert.throws(()=>c.binaryValidate(c.buffer.slice(0,-1),5,5),/Truncated/);vm.runInContext("globalThis.gaps=[{seq:1,event:{}},{seq:3,event:{}}]",c);assert.throws(()=>c.binaryEncode(c.gaps),/record gap/);});
test('compact v2 diagnostic archive remains readable through unchanged canonical codec',async()=>{const c=fixture(),t=await workerJournal(c,{mode:'compact',chunkBytes:1});try{t.j.append(Object.assign(Object.create(null),{n:1}));await t.j.flush();assert.equal(t.acks[0].testChunks[0].encoding,undefined);assert.deepEqual((await durable(c,t.acks)).map(r=>r.event.n),[1]);assert.ok(t.j.encodedCharacters>0);}finally{t.client.close();}});

test('native browser archive, storageRecords and tagged export preserve canonical ordered analysis records',async()=>{const {c,adapters}=browserFixture();try{await c.log.begin();vm.runInContext("function storageTransactionPrimitives(e){return e.kind==='storage-transaction'?e.primitives:null;}log.journal.append({kind:'storage-transaction',primitives:[{kind:'storage',n:-0,array:[,undefined]},{kind:'storage',n:2}]});",c);await c.log.flush();assert.equal(c.log.meta.version,3);assert.equal(c.log.status().encodedCharacters,0);const opened=await c.log.open(c.log.meta.id),rows=[];for await(const row of opened.storageRecords())rows.push(row);assert.equal(rows.length,3);assert.ok(Object.is(rows[1].event.n,-0));assert.equal(0 in rows[1].event.array,false);assert.equal(rows[2].event.n,2);const text=await new Response(c.log.stream()).text(),lines=text.trimEnd().split('\n');assert.equal(lines.length,3);const exported=lines.map(line=>vm.runInContext('outcomeParse('+JSON.stringify(line)+')',c));assert.equal(exported[0].meta.encoding,'native-storage-v3');assert.ok(Object.is(exported[2].event.primitives[0].n,-0));}finally{for(const adapter of adapters)adapter.terminate();}});
