import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {realm,near} from './ownership-fixture.mjs';
function setup(){const r=realm({grain:0,fish:0});r.eval("storageInit(s);const K=s.storage;K.location('a',{capacity:10,goods:null,protection:0.4});K.location('b',{capacity:5,goods:null});");return r;}
test('mixed goods share finite volume; rejected intake remains exposed',()=>{const r=setup();r.eval("const grain=K.create('grain',12,null,'yard');K.move(grain,'a',8);const wool=K.create('wool',3,null,'yard');K.move(wool,'a',3)");near(r.eval("K.used('a')"),10);near(r.eval("K.total('grain')"),12);near(r.eval("K.total('wool')"),3);near(r.eval("K.used('yard')"),8);assert.ok(r.eval("K.events.some(e=>e.cause==='intake-rejected')"));});
test('title transfer and split preserve custody and physical total',()=>{const r=setup();r.eval("const l=K.create('grain',8,H[0],'a','held');K.transfer(l,'heir',3,'held')");near(r.eval("K.total('grain')"),8);near(r.eval("K.used('a')"),8);assert.equal(r.eval("[...K.lots.values()].find(l=>l.owner==='heir').location"),'a');});
test('destroying storage exposes retained contents without erasure',()=>{const r=setup();r.eval("K.create('grain',8,H[0],'a','held');K.destroy('a')");near(r.eval("K.total('grain')"),8);near(r.eval("K.used('a')"),0);near(r.eval("K.free('a','grain')"),0);assert.equal(r.eval("[...K.lots.values()][0].location"),'exposed:a');});
test('derived settlement quantity mutates physical lots once',()=>{const r=setup();r.eval("s.stores.grain+=10;s.stores.grain-=3");near(r.s.stores.grain,7);near(r.eval("K.total('grain')"),7);});
test('matching legal claims neither creates physical goods nor moves them',()=>{const r=setup();r.eval("K.create('grain',8,null,'a');addHeld(s,H[0],'grain',8);storageTitles(s)");near(r.s.stores.grain,8);near(r.eval("K.used('a')"),8);assert.ok(r.eval("[...K.lots.values()].every(l=>l.owner===accountOwner(H[0]))"));});
test('owner consumption debits the owner custody lot exactly once',()=>{const r=setup();r.eval("K.create('grain',8,null,'a');addHeld(s,H[0],'grain',8);consumeOwned(s,H[0],'grain',3)");near(r.s.stores.grain,5);near(r.eval("pantry(s,H[0]).grain"),5);near(r.eval("K.used('a')"),5);});
test('migration retains old quantities explicitly uncovered',()=>{const r=realm({grain:10000,fish:3});r.eval('storageInit(s)');near(r.s.stores.grain,10000);assert.ok(r.eval("[...s.storage.lots.values()].every(l=>l.location==='yard')"));});
test('storage preserves more than exposure; physical and legal loss agree',()=>{const r=realm({grain:20});r.eval("storageInit(s);const K=s.storage;K.location('a',{capacity:10,protection:0.4});storageTitles(s);K.move([...K.lots.values()].find(l=>l.good==='grain'),'a',10);spoilOwned(s,'grain',0.01)");near(r.s.stores.grain,19.56);near(r.eval("[...s._owners.values()].reduce((q,x)=>q+(x.sale.grain||0)+(x.held.grain||0),0)"),19.56);});
test('purchase changes legal title at seller custody, without teleportation',()=>{const r=realm({grain:20,cash:100});r.eval("storageInit(s);const K=s.storage;K.location('a',{capacity:30});storageTitles(s);K.move([...K.lots.values()].find(l=>l.good==='grain'),'a',20);purchase(s,'grain',H[0],3);addHeld(s,H[0],'grain',purchase.got)");near(r.s.stores.grain,20);assert.equal(r.eval("[...K.lots.values()].find(l=>l.owner===accountOwner(H[0])).location"),'a');});
test('sale consumption removes the matching owner physical stock',()=>{const r=realm({grain:20});r.eval("storageInit(s);consumeOwnStock(s,'crown','grain',4)");near(r.s.stores.grain,16);near(r.eval("mkt(s,'grain').get('crown')"),16);});
test('disconnected and sealed routes do not grant local carriage access',()=>{const r=setup();r.eval("streetGraph=()=>({N:[{x:0,z:0},{x:100,z:0}]});nearestNode=(g,x)=>x===0?0:1;streetPath=()=>null;dist2d=(a,b,c,d)=>Math.hypot(a-c,b-d)");assert.equal(r.eval("storageRoute(s,{x:0,z:0},{x:100,z:0})"),Infinity);r.s.siegeBy={};assert.equal(r.eval("storageRoute(s,{x:0,z:0},{x:0,z:0})"),Infinity);});
test('paid construction activates capacity only at completion and consumes materials once',()=>{const r=realm({grain:0,fish:0,crown:2000});r.s.stores.timber=100;r.s.stores.stone=100;r.s.history=[];r.eval("storageInit(s);offer(s,'timber','crown',100);offer(s,'stone','crown',100);ARCH={grange:[12,10]};LS={TILLED:1};dist2d=(a,b,c,d)=>Math.hypot(a-c,b-d);planLand=()=>({c:0});storageRoute=()=>30;syncLive=()=>{};wages=(s,v)=>{s.testWages=(s.testWages||0)+v};s._lay={live:{storageSite(x,z,arch,dry){if(dry)return {x,z};const b={x,z,arch,tier:0,state:'sound',s};s.buildings.push(b);return b;}}};const Q=storageSiteQuote(0,'grange',20,20,0);const project=storageCommission(Q)");near(r.eval("[...s.storage.locations.values()].filter(n=>n.building).length"),0);r.eval('storageProjectTick(project)');near(r.s.stores.timber,76);near(r.s.stores.stone,100);near(r.eval("[...s.storage.locations.values()].filter(n=>n.building).length"),0);r.eval('for(let i=1;i<90;i++)storageProjectTick(project)');assert.ok(r.eval('project.dead'));near(r.eval("[...s.storage.locations.values()].find(n=>n.building).capacity"),800);near(r.s.stores.timber,76);near(r.s.testWages,360);});
test('cargo is counted only in transit then moves the same lots on arrival',()=>{const r=realm({grain:20,cash:100});r.eval("storageInit(s);const d={name:'destination',owner:0,pos:{x:100,z:0},stores:{grain:0},buildings:[],_owners:new Map()};W.settlements.push(d);purchase(s,'grain',H[0],5);const c={good:'grain',qty:purchase.got,m:H[0],dest:1};storageCargoOut(c,s)");near(r.s.stores.grain,15);near(r.eval('c.qty'),5);r.eval("storageTitles(s)");near(r.eval('c.qty'),5);r.eval("offer(d,'grain',H[0],c.qty);storageCargoArrive(c,d)");near(r.eval('d.stores.grain'),5);near(r.eval('c.qty'),0);near(r.eval("[...s.storage.lots.values()].filter(l=>l.good==='grain').reduce((q,l)=>q+l.qty,0)+[...d.storage.lots.values()].filter(l=>l.good==='grain').reduce((q,l)=>q+l.qty,0)"),20);});
test('ordered outcome reducer independently reconstructs custody, title, metadata, destruction and cross-town cargo',()=>{const r=realm({grain:20,cash:100});r.eval("const journal=[];storageOutcome=e=>journal.push(JSON.parse(JSON.stringify(e)));storageInit(s);const K=s.storage;K.location('a',{capacity:12,protection:0.4,x:10,z:10});K.location('empty',{capacity:5});storageTitles(s);K.move([...K.lots.values()].find(l=>l.good==='grain'),'a',10);K.destroy('empty');purchase(s,'grain',H[0],5);const c={good:'grain',qty:purchase.got,m:H[0],dest:1};storageCargoOut(c,s);const d={name:'destination',owner:0,pos:{x:100,z:0},stores:{grain:0},buildings:[],_owners:new Map()};W.settlements.push(d);storageInit(d);offer(d,'grain',H[0],c.qty);storageCargoArrive(c,d);K.destroy('a')");const journal=JSON.parse(JSON.stringify(r.eval('journal'))),ledgers=new Map();for(const e of journal){if(e.settlement===undefined||e.settlement===null)continue;let k=ledgers.get(e.settlement);if(!k)ledgers.set(e.settlement,k={lots:new Map(),locations:new Map()});if(e.locationAfter)k.locations.set(e.locationAfter.id,e.locationAfter);if(e.sourceLotAfter)k.lots.set(e.sourceLotAfter.id,e.sourceLotAfter);if(e.lot){if(!e.lotAfter||e.lotAfter.qty===0)k.lots.delete(e.lot);else k.lots.set(e.lot,e.lotAfter);}}for(const [i,k]of ledgers){const actual=JSON.parse(r.eval(`JSON.stringify({lots:[...W.settlements[${i}].storage.lots.values()].map(l=>W.settlements[${i}].storage.lotState(l)),locations:[...W.settlements[${i}].storage.locations.values()].map(n=>W.settlements[${i}].storage.locationState(n))})`));assert.deepEqual([...k.lots.values()].sort((a,b)=>a.id.localeCompare(b.id)),actual.lots.sort((a,b)=>a.id.localeCompare(b.id)));assert.deepEqual([...k.locations.values()],actual.locations);}assert.ok(journal.some(e=>e.cause==='location-destroyed'&&e.location==='empty'));assert.ok(journal.some(e=>e.cause==='custody-departure'&&e.settlement===0));});
test('unbacked legal title surfaces a fault without inventing or discarding goods',()=>{const r=setup();r.eval("addHeld(s,H[0],'grain',9)");assert.throws(()=>r.eval("storageTitles(s)"),/Unbacked grain title/);near(r.s.stores.grain,0);near(r.eval("pantry(s,H[0]).grain"),9);});
test('charcoal claims share actual timber custody and consumption once',()=>{const r=realm({grain:0,fish:0});r.s.stores.timber=5;r.eval("storageInit(s);addHeld(s,H[0],'char',5);consumeOwned(s,H[0],'char',2)");near(r.s.stores.timber,3);near(r.eval("pantry(s,H[0]).char"),3);});
test('physical title inheritance retains location while dividing exact quantity',()=>{const r=setup();r.eval("K.create('grain',8,null,'a');addHeld(s,H[0],'grain',8);storageTitles(s);transferOwnership(accountOwner(H[0]),[['widow',0.5],['child',0.5]])");near(r.s.stores.grain,8);near(r.eval("K.used('a')"),8);near(r.eval("[...K.lots.values()].filter(l=>l.owner==='widow').reduce((q,l)=>q+l.qty,0)"),4);near(r.eval("[...K.lots.values()].filter(l=>l.owner==='child').reduce((q,l)=>q+l.qty,0)"),4);});
test('physical losses immediately debit matching legal titles without phantom reconciliation',()=>{const r=realm({grain:20});r.eval("storageInit(s);storageTitles(s);s.stores.grain-=4;storageTitles(s)");near(r.s.stores.grain,16);near(r.eval("mkt(s,'grain').get('crown')"),16);});
test('generic purchased material consumption takes purchased custody before neighbours stock',()=>{const r=realm({grain:20,cash:100});r.eval("storageInit(s);const K=s.storage;K.location('a',{capacity:30});storageTitles(s);K.move([...K.lots.values()].find(l=>l.good==='grain'),'a',20);purchase(s,'grain',H[0],3);s.stores.grain-=purchase.got;storageTitles(s)");near(r.s.stores.grain,17);near(r.eval("mkt(s,'grain').get('crown')"),17);assert.ok(r.eval("[...K.lots.values()].filter(l=>l.good==='grain').every(l=>l.owner==='crown')"));});
test('compatible lot merging is logged and conserves quantities; future semantic fields prevent unsafe merges',()=>{const r=setup();r.eval("const a=K.create('grain',8,null,'yard');const b=K.split(a,3);K.coalesce('grain')");near(r.eval("K.total('grain')"),8);near(r.eval("[...K.lots.values()].filter(l=>l.good==='grain').length"),1);assert.ok(r.eval("K.events.some(e=>e.cause==='lot-merged'&&e.lotAfter===null&&e.sourceLotAfter.qty===8)"));r.eval("const c=K.split([...K.lots.values()].find(l=>l.good==='grain'),2);K.annotate(c,{condition:'wet'});K.coalesce('grain')");near(r.eval("[...K.lots.values()].filter(l=>l.good==='grain').length"),2);near(r.eval("K.total('grain')"),8);});
test('capacity-rejected creation leaves all canonical state unchanged',()=>{const r=setup();const before=r.eval("JSON.stringify({lots:[...K.lots],next:K.next,revision:K.revision,events:K.events})");assert.throws(()=>r.eval("K.create('grain',11,null,'a')"),/capacity/);assert.equal(r.eval("JSON.stringify({lots:[...K.lots],next:K.next,revision:K.revision,events:K.events})"),before);});
test('claim proxy invalidates cached matches for direct set, deletion, defineProperty and table replacement',()=>{const r=setup();r.eval("K.create('grain',10,null,'a');addHeld(s,H[0],'grain',8);storageTitles(s);pantry(s,H[0]).grain=6;storageTitles(s)");near(r.eval("[...K.lots.values()].filter(l=>l.owner===accountOwner(H[0])).reduce((q,l)=>q+l.qty,0)"),6);r.eval("Object.defineProperty(pantry(s,H[0]),'grain',{value:4,writable:true,enumerable:true,configurable:true});storageTitles(s)");near(r.eval("[...K.lots.values()].filter(l=>l.owner===accountOwner(H[0])).reduce((q,l)=>q+l.qty,0)"),4);r.eval("delete pantry(s,H[0]).grain;storageTitles(s)");near(r.eval("[...K.lots.values()].filter(l=>l.owner===accountOwner(H[0])).reduce((q,l)=>q+l.qty,0)"),0);r.eval("stockOf(s,H[0]).held={grain:3};storageTitles(s)");near(r.eval("[...K.lots.values()].filter(l=>l.owner===accountOwner(H[0])).reduce((q,l)=>q+l.qty,0)"),3);});
test('inspecting a building does not initialize or mutate storage economics or IDs',()=>{const r=realm();const keys=Object.keys(r.s),b={arch:'granary',x:0,z:0};r.C.testBuilding=b;assert.equal(r.eval('storageBuildingReport(s,testBuilding)'),null);assert.deepEqual(Object.keys(r.s),keys);assert.equal(r.s.storage,undefined);assert.equal(b.storageId,undefined);});
function multiSellerCargo(){const r=realm({grain:10,fish:0,cash:100});r.eval("s.mkt.grain.clear();offer(s,'grain','one',5);offer(s,'grain','two',5);storageInit(s);purchase(s,'grain',H[0],10);const c={good:'grain',qty:purchase.got,m:H[0],dest:1,origin:0};storageCargoOut(c,s);const d={name:'destination',owner:0,pos:{x:100,z:0},stores:{grain:0},buildings:[],_owners:new Map()};W.settlements.push(d);storageTitles(s)");return r;}
test('multi-seller cargo uses canonical custody after lot merging and arrives without resurrecting retired IDs',()=>{const r=multiSellerCargo();near(r.eval('c.qty'),10);near(r.eval("[...s.storage.lots.values()].filter(l=>l.good==='grain').length"),1);r.eval("offer(d,'grain',H[0],c.qty);storageCargoArrive(c,d)");near(r.eval('c.qty'),0);near(r.eval('d.stores.grain'),10);near(r.s.stores.grain,0);near(r.eval("[...s.storage.lots.values()].filter(l=>l.good==='grain').reduce((q,l)=>q+l.qty,0)+[...d.storage.lots.values()].filter(l=>l.good==='grain').reduce((q,l)=>q+l.qty,0)"),10);});
test('multi-seller merged cargo robbery recovers and loses each canonical unit once',()=>{const r=multiSellerCargo();near(r.eval("storageCargoRaid(c,d)"),6);near(r.eval('c.qty'),0);near(r.eval('d.stores.grain'),6);near(r.eval("s.storage.events.filter(e=>e.cause==='cargo-robbery-loss').reduce((q,e)=>q+e.qty,0)"),4);assert.ok(r.eval("[...d.storage.lots.values()].every(l=>l.owner==='out')"));});
test('generic metadata outcomes preserve actual raw fields, undefined presence, special values and array holes',()=>{const r=setup();r.C.clone=structuredClone;r.eval("const metadataJournal=[];storageOutcome=e=>metadataJournal.push(clone(e));const l=K.create('grain',4,null,'yard');K.annotate(l,{condition:'wet',explicitUndefined:undefined,negativeZero:-0,big:3n,nonfinite:Infinity,samples:[1,,undefined],nested:{a:undefined,b:'x'}});const node=K.location('metadata-location',{capacity:9,condition:'damp',optional:undefined});const project={storageProjectId:'p:0',payer:'crown',custom:{terms:[1,,2]},undone:undefined};const projectProjection=storageProjectState(project)");const events=Array.from(r.eval('metadataJournal'));const event=events.findLast(e=>e.cause==='lot-metadata');const raw=r.eval('l');const oracle={};for(const key of Reflect.ownKeys(raw)){const v=raw[key];oracle[key]=key==='owner'?'unassigned':structuredClone(v);}assert.deepEqual(event.lotAfter,oracle);assert.ok(Object.hasOwn(event.lotAfter,'explicitUndefined'));assert.equal(Object.is(event.lotAfter.negativeZero,-0),true);assert.equal(1 in event.lotAfter.samples,false);assert.equal(2 in event.lotAfter.samples,true);const location=events.find(e=>e.cause==='location-created'&&e.location==='metadata-location').locationAfter;const node=r.eval('node');const locationOracle={};for(const key of Reflect.ownKeys(node))locationOracle[key]=structuredClone(node[key]);assert.deepEqual(location,locationOracle);const project=r.eval('project'),projection=structuredClone(r.eval('projectProjection'));for(const key of Reflect.ownKeys(project)){const expected=key==='payer'?'string:crown':structuredClone(project[key]);assert.deepEqual(projection[key],expected);}assert.ok(Object.hasOwn(projection,'undone'));r.eval("K.annotate(l,{},['explicitUndefined'])");assert.equal(Object.hasOwn(r.eval('l'),'explicitUndefined'),false);});
test('unsupported metadata and indexed-field annotations fail before authoritative mutation',()=>{const r=setup();r.eval("const l=K.create('grain',4,null,'yard')");const before=r.eval("JSON.stringify({lot:l,next:K.next,revision:K.revision,events:K.events.length})");for(const expr of ["K.annotate(l,{condition:()=>1})","K.annotate(l,{nested:new Map()})","K.annotate(l,{qty:9})","K.annotate(l,{location:'a'})","K.annotate(l,{nested:{get a(){return 1}}})","K.location('bad',{capacity:9,unsupported:()=>1})"]){assert.throws(()=>r.eval(expr));assert.equal(r.eval("JSON.stringify({lot:l,next:K.next,revision:K.revision,events:K.events.length})"),before);assert.equal(r.eval("K.locations.has('bad')"),false);}});

test('private commissioned grange follows normal inheritance and admits heir goods',()=>{const r=realm({households:2,grain:0,fish:0,cash:2000});r.s.stores.timber=100;r.s.stores.stone=100;r.s.history=[];r.eval("H[0].sx='m';H[1].sx='m';H[1].pa=H[0];H[0].kids=[H[1]];ownershipTick();storageInit(s);offer(s,'timber','crown',100);offer(s,'stone','crown',100);ARCH={grange:[12,10]};LS={TILLED:1};dist2d=(a,b,c,d)=>Math.hypot(a-c,b-d);planLand=()=>({c:0});storageRoute=()=>30;syncLive=()=>{};wages=()=>{};s._lay={live:{storageSite(x,z,arch,dry){if(dry)return {x,z};const b={x,z,arch,tier:0,state:'sound',s};s.buildings.push(b);return b;}}};const project=storageCommission(storageSiteQuote(0,'grange',20,20,accountOwner(H[0])));for(let i=0;i<90;i++)storageProjectTick(project);const building=s.buildings[0];const oldOwner=building.title.owner;bindPropertyRights(s);inherit(H[0]);H[0].dead=true;storageFacilities(s)");assert.ok(r.eval('project.dead'));assert.equal(r.eval('building.ownerId'),r.H[1].id);assert.equal(r.eval('building.title.owner'),r.eval('accountOwner(H[1])'));assert.equal(r.eval('s.storage.locations.get(building.storageId).owner'),r.eval('accountOwner(H[1])'));r.eval("s.storage.create('grain',2,accountOwner(H[1]),'yard','held');addHeld(s,H[1],'grain',2);storageTick(s)");near(r.eval('s.storage.used(building.storageId)'),2);assert.ok(r.eval("s.storage.events.some(e=>e.cause==='facility-state'&&e.before.owner!==e.locationAfter.owner)"));});

test('subtractive cancellation uses observed input magnitude without deleting tiny claims',()=>{const r=setup();r.eval("K.create('grain',10.1,null,'yard');addHeld(s,H[0],'grain',10.1);storageTitles(s);K.remove([...K.lots.values()][0],10.1,'test-cancellation');stockOf(s,H[0]).held.grain=3.573530360512223e-15;storageTitles(s)");assert.equal(r.eval('pantry(s,H[0]).grain'),3.573530360512223e-15);assert.equal(r.s.stores.grain,0);assert.ok(r.eval("K.events.some(e=>e.cause==='accounting-roundoff'&&e.provenance.last.inputs.some(q=>q===10.1))"));r.eval('stockOf(s,H[0]).held.grain+=1');assert.throws(()=>r.eval('storageTitles(s)'),/Unbacked/);});

test('model invariant faults notify the sticky-pause hook before throwing',()=>{const r=setup();r.eval('const modelFaults=[];storageModelFault=e=>modelFaults.push(e.message)');assert.throws(()=>r.eval("addHeld(s,H[0],'grain',1);storageTitles(s)"),/Unbacked/);assert.equal(r.eval('modelFaults.length'),1);assert.throws(()=>r.eval("storageTitleTake(s,H[1],H[0],'grain',1)"),/Unbacked title transfer/);assert.equal(r.eval('modelFaults.length'),2);assert.throws(()=>r.eval("storageCargoOut({good:'grain',qty:1,m:H[1],dest:0},s)"),/Unbacked cargo/);assert.equal(r.eval('modelFaults.length'),3);assert.throws(()=>r.eval("K.create('grain',11,null,'a')"),/capacity/);assert.equal(r.eval('modelFaults.length'),3);});

test('matching retains earlier arithmetic uncertainty when later balances approach zero',()=>{const r=setup();r.eval("K.create('grain',100,null,'yard');K.remove([...K.lots.values()][0],100,'prior-use');storageTitles(s);const inheritedBudget=K.roundoff.get('grain').budget;K.create('grain',0.003481434183057027,null,'yard');addHeld(s,H[0],'grain',0.0034814341830577728);storageTitles(s)");assert.ok(r.eval("K.roundoff.get('grain').budget>=inheritedBudget"));assert.equal(r.s.stores.grain,0.003481434183057027);assert.equal(r.eval('pantry(s,H[0]).grain'),0.0034814341830577728);r.eval('stockOf(s,H[0]).held.grain+=1');assert.throws(()=>r.eval('storageTitles(s)'),/Unbacked/);});
test('identical whole-lot title transfer is a journal and index no-op',()=>{const r=setup();r.eval("const l=K.create('grain',1,null,'yard');const before=K.events.length;const revision=K.revision;K.transfer(l,null,l.qty,l.availability)");assert.equal(r.eval('K.events.length'),r.eval('before'));assert.equal(r.eval('K.revision'),r.eval('revision'));});
test('construction installs scarce materials incrementally without paying labour while stalled',()=>{const r=realm({grain:0,fish:0,crown:2000});r.s.stores.timber=100;r.s.stores.stone=0;r.s.history=[];r.eval("storageInit(s);offer(s,'timber','crown',100);offer(s,'stone','crown',0);ARCH={granary:[12,10]};LS={TILLED:1};dist2d=(a,b,c,d)=>Math.hypot(a-c,b-d);planLand=()=>({c:0});storageRoute=()=>30;syncLive=()=>{};wages=(s,v)=>{s.testWages=(s.testWages||0)+v};s._lay={live:{storageSite(x,z,arch,dry){if(dry)return {x,z};const b={x,z,arch,tier:0,state:'sound',s};s.buildings.push(b);return b;}}};const Q=storageSiteQuote(0,'granary',20,20,0);const project=storageCommission(Q)");r.eval('storageProjectTick(project)');near(r.eval('project.timberInstalled'),20);near(r.eval('project.stoneInstalled||0'),0);near(r.eval('project.done'),0);near(r.s.testWages||0,0);near(r.s.stores.timber,80);r.eval("const receipts=s.storage.events.filter(e=>e.cause==='construction-material-installed').length;storageProjectTick(project)");assert.equal(r.eval("s.storage.events.filter(e=>e.cause==='construction-material-installed').length"),r.eval('receipts'));r.eval("for(let i=0;i<4;i++){s.stores.stone+=5;offer(s,'stone','crown',5);storageProjectTick(project)}");near(r.eval('project.stoneInstalled'),20);near(r.eval('project.done'),1);near(r.s.stores.stone,0);r.eval('for(let i=1;i<120;i++)storageProjectTick(project)');assert.ok(r.eval('project.dead'));near(r.eval('project.timberInstalled'),20);near(r.eval('project.stoneInstalled'),20);near(r.s.stores.timber,80);near(r.s.testWages,500);});

test('storage demand exposes unfinished stone requirements to existing quarry economy',()=>{const r=setup();r.eval("W.projects=[{type:'storage',si:0,stone:20,stoneInstalled:5,dead:false,materials:false},{type:'storage',si:0,stone:30,stoneInstalled:10,dead:true},{type:'storage',si:0,stone:20,materials:true}]");near(r.eval("storageMaterialDemand(s,'stone')"),15);r.eval('W.projects[0].dead=true');near(r.eval("storageMaterialDemand(s,'stone')"),0);});

test('purchased relief gifts transfer pending title to recipients without moving custody',()=>{const r=realm({households:2,grain:20,cash:100});r.eval("storageInit(s);const K=s.storage;K.location('market',{capacity:30});storageTitles(s);for(const l of [...K.lots.values()])if(l.good==='grain')K.move(l,'market',l.qty);purchase(s,'grain',H[0],5);giveFood(s,'grain',purchase.got,H[0]);storageTitles(s)");near(r.s.stores.grain,20);assert.ok(r.eval("[...K.lots.values()].every(l=>!l.pendingPurchase)"));for(let i=0;i<2;i++){const held=r.eval(`pantry(s,H[${i}]).grain`),physical=r.eval(`[...K.lots.values()].filter(l=>l.owner===accountOwner(H[${i}])&&l.availability==='held').reduce((n,l)=>n+l.qty,0)`);near(held,physical);}assert.ok(r.eval("[...K.lots.values()].filter(l=>l.good==='grain').every(l=>l.location==='market')"));});

test('army purchase consumption selects buyer pending lots and preserves neighbours completed claims',()=>{const r=realm({households:2,grain:20,cash:100,crown:1000});r.eval("storageInit(s);const K=s.storage;purchase(s,'grain',H[0],2);addHeld(s,H[0],'grain',purchase.got);const protectedHeld=pantry(s,H[0]).grain;purchase(s,'grain','crown',3);const purchased=purchase.got;storageConsumePurchased(s,'crown','grain',purchased,'army-provisions');storageTitles(s)");near(r.eval('pantry(s,H[0]).grain'),r.eval('protectedHeld'));near(r.s.stores.grain,20-r.eval('purchased'));assert.ok(r.eval("[...K.lots.values()].filter(l=>l.owner===accountOwner(H[0])).every(l=>!l.pendingPurchase)"));assert.ok(r.eval("[...K.lots.values()].every(l=>!l.pendingPurchase)"));});
test('purchased intertown relief retains canonical lot IDs through transfer and held completion',()=>{const r=realm({households:2,grain:20,cash:100});r.eval("storageInit(s);purchase(s,'grain',H[0],3);const bought=purchase.got;const ids=[...s.storage.lots.values()].filter(l=>l.pendingPurchase).map(l=>l.id);const d={name:'relief destination',owner:0,pos:{x:100,z:0},stores:{grain:0},buildings:[],_owners:new Map()};W.settlements.push(d);storageMovePurchased(s,d,H[0],'grain',bought);addHeld(d,H[1],'grain',0);for(const l of d.storage.lots.values()){d.storage.transfer(l,accountOwner(H[1]),l.qty,'held');}addHeld(d,H[1],'grain',bought);storageTitles(d)");near(r.eval('d.stores.grain'),r.eval('bought'));assert.deepEqual(r.eval('[...d.storage.lots.keys()].sort()'),r.eval('ids.sort()'));assert.ok(r.eval('[...d.storage.lots.values()].every(l=>!l.pendingPurchase)'));near(r.s.stores.grain,20-r.eval('bought'));});

test('foreign dock purchases complete small cancelled loads and retain exact exported manifests',()=>{const source=fs.readFileSync(process.env.FURLONG_TEST_SOURCE||new URL('../index.html',import.meta.url),'utf8'),tickShips=source.slice(source.indexOf('function tickShips()'),source.indexOf('function shipPos('));for(const qty of [.4,1.4]){const r=realm({grain:qty,fish:0,cash:0});r.eval(tickShips);r.eval("storageInit(s);EXPORTS=['grain'];SHIP_MPD=360;spareOf=()=>10;W.ships=[{phase:'dock',port:0,until:0,len:10,load:{}}];tickShips();storageTitles(s)");if(qty<1){near(r.s.stores.grain,qty);near(r.eval("pantry(s,'out').grain"),qty);assert.equal(r.eval('W.ships[0].load.grain'),undefined);}else{near(r.s.stores.grain,0);assert.equal(r.eval('W.ships[0].load.grain'),qty);}assert.ok(r.eval('[...s.storage.lots.values()].every(l=>!l.pendingPurchase)'));}});

test('lord-funded provision gives orphan recipients completed physical title at seller custody',()=>{const r=realm({grain:20,fish:0,households:1,cash:0,crown:1000});r.s.stores.timber=40;r.eval("H[0].age=8;ownershipTick();storageInit(s);offer(s,'timber','crown',40);s._smiths=0;s._dyers=0;trait=()=>0;TRADE_W={};SUNDRY={};SUNDRY_W=1;provision(s,[],new Map());storageTitles(s)");const legal=r.eval("pantry(s,H[0]).timber"),physical=r.eval("[...s.storage.lots.values()].filter(l=>l.good==='timber'&&l.owner===accountOwner(H[0])&&l.availability==='held').reduce((n,l)=>n+l.qty,0)");assert.ok(legal>0);near(legal,physical);assert.ok(r.eval("[...s.storage.lots.values()].filter(l=>l.good==='timber').every(l=>!l.pendingPurchase)"));near(r.s.stores.timber,40);});
