import test from 'node:test';
import assert from 'node:assert/strict';
import {realm} from './ownership-fixture.mjs';
import {StorageEventReducer} from './storage-event-reducer.mjs';
function setup(options={}){const r=realm({grain:0,fish:0,cash:100,crown:100,...options});r.eval("s.stores.hay=0;storageInit(s);const K=s.storage;let paid=0;wages=(s,q)=>{paid+=q};buildWorks=(s,q,payer)=>{paid+=q;acct(payer,-q)};storageRoute=()=>30;s.buildings.push({arch:'grange',state:'sound',x:30,z:0,tier:0,ownerId:'crown'});storageFacilities(s);");return r;}
function replay(r){const R=new StorageEventReducer();for(const event of structuredClone(r.eval('K.events')))R.apply(event);R.compare([structuredClone(r.eval('({settlement:0,lots:[...K.lots.values()].map(l=>K.captureLot(l)),locations:[...K.locations.values()].map(n=>K.locationState(n))})'))]);}
for(const q of [Number.MIN_VALUE,0.0005,0.001])test('hay remnant '+q+' is explicit physical loss before paid carriage',()=>{const r=setup(),money=r.coins();r.eval(`K.create('hay',${q},null,'yard');storageTick(s)`);assert.equal(r.s.stores.hay,0);assert.equal(r.eval("K.byGood.get('hay').size"),0);assert.equal(r.eval("K.used('yard')"),0);assert.equal(r.eval('paid'),0);assert.equal(r.coins(),money);assert.equal(r.eval('s.storageReport.moved'),0);assert.equal(r.eval("K.events.filter(e=>e.cause==='vermin-remnant-loss').length"),1);assert.equal(r.eval("K.events.find(e=>e.cause==='vermin-remnant-loss').qty"),q);assert.equal(r.eval("K.events.some(e=>e.cause==='local-carriage')"),false);assert.ok(r.eval("K.roundoff.get('hay').budget>=0"));replay(r);});
test('strictly above threshold and unrelated goods retain exact physical quantities',()=>{const r=setup();r.eval("K.create('hay',0.0010000000000000002,null,'yard');K.create('grain',0.0005,null,'yard');storageTick(s)");assert.equal(r.s.stores.hay,0.0010000000000000002);assert.equal(r.s.stores.grain,0.0005);assert.equal(r.eval("K.events.some(e=>e.cause==='vermin-remnant-loss')"),false);replay(r);});
for(const kind of ['held','sale'])test('settled '+kind+' hay loss debits only its legal owner and frees custody capacity',()=>{const r=setup();r.eval(`K.location('rack',{capacity:1});K.create('hay',0.001,null,'rack');${kind==='held'?"addHeld(s,H[0],'hay',0.001)":"offer(s,'hay',H[0],0.001)"};storageTick(s);storageTitles(s,'hay')`);assert.equal(r.s.stores.hay,0);assert.equal(r.eval(`stockOf(s,H[0]).${kind}.hay`),0);assert.equal(r.eval("K.used('rack')"),0);assert.equal(r.eval("K.free('rack','hay')"),1/r.eval("K.volume('hay')"));const e=structuredClone(r.eval("K.events.find(e=>e.cause==='vermin-remnant-loss')"));assert.equal(e.titleBefore,0.001);assert.equal(e.titleAfter,0);assert.equal(e.qty,0.001);assert.equal(e.legalQty,0.001);assert.equal(e.before.qty,0.001);assert.equal(e.lotAfter.qty,0);assert.equal(r.eval("K.events.filter(e=>e.cause==='vermin-remnant-loss').length"),1);assert.equal(r.eval("K.events.filter(e=>e.cause==='legal-title-loss').length"),0);assert.equal(r.eval('paid'),0);replay(r);});
test('compatible crumbs combine above the threshold without loss or claim fabrication',()=>{const r=setup();r.eval("const lot=K.create('hay',0.0012,null,'yard');K.split(lot,0.0006);storageTitles(s);K.split([...K.lots.values()].find(l=>l.good==='hay'),0.0006);storageTick(s)");assert.equal(r.s.stores.hay,0.0012);assert.equal(r.eval("K.byGood.get('hay').size"),1);assert.equal(r.eval("K.events.some(e=>e.cause==='vermin-remnant-loss')"),false);replay(r);});
test('compatible structured-metadata fragments preserve their aggregate even when bulk merge declines',()=>{const r=setup();r.eval("const lot=K.create('hay',0.0012,null,'yard');K.annotate(lot,{condition:{note:'future'}});K.split(lot,0.0004);K.split(lot,0.0004);storageTick(s)");assert.equal(r.s.stores.hay,0.0012);assert.equal(r.eval("K.byGood.get('hay').size"),3);assert.equal(r.eval("K.events.some(e=>e.cause==='vermin-remnant-loss')"),false);replay(r);});
test('fresh unoffered production accumulates instead of being purged after each inflow',()=>{const r=setup();r.eval("K.create('hay',0.0004,null,'yard');s._made.hay=0.0004;storageTick(s)");assert.equal(r.s.stores.hay,0.0004);assert.equal(r.eval('paid'),0);r.eval("s.stores.hay+=0.0004;s._made.hay+=0.0004;storageTick(s)");assert.equal(r.s.stores.hay,0.0008);assert.equal(r.eval('paid'),0);r.eval("s.stores.hay+=0.0004;s._made.hay+=0.0004;storageTick(s)");assert.equal(r.s.stores.hay,0.0012000000000000001);assert.equal(r.eval("K.events.some(e=>e.cause==='vermin-remnant-loss')"),false);replay(r);});
test('pending purchases survive until completed ownership, then settled remnants become modeled loss',()=>{const r=setup();r.eval("K.create('hay',0.001,null,'yard');offer(s,'hay','crown',0.001);storageTitles(s,'hay');purchase(s,'hay',H[0],0.001);const got=purchase.got;storageTick(s)");assert.equal(r.s.stores.hay,0.001);assert.equal(r.eval("[...K.lots.values()].find(l=>l.good==='hay').pendingPurchase"),true);assert.equal(r.eval('paid'),0);r.eval("const pendingEvents=K.events.length;storageTick(s);storageTick(s)");assert.equal(r.eval('K.events.length'),r.eval('pendingEvents'));r.eval("addHeld(s,H[0],'hay',got);storageTick(s)");assert.equal(r.s.stores.hay,0);assert.equal(r.eval("pantry(s,H[0]).hay"),0);replay(r);});
test('in-transit manifest quantities and ownership remain untouched',()=>{const r=setup();r.eval("K.create('hay',0.001,null,'yard');addHeld(s,H[0],'hay',0.001);storageTitles(s,'hay');const cargo={good:'hay',qty:0.001,m:H[0],dest:1};storageCargoOut(cargo,s);storageTick(s)");assert.equal(r.eval('cargo.qty'),0.001);assert.equal(r.eval("[...K.lots.values()].find(l=>l.good==='hay').availability"),'transit');assert.equal(r.eval("K.events.some(e=>e.cause==='vermin-remnant-loss')"),false);assert.equal(r.eval('paid'),0);replay(r);});

test('remnant loss follows inherited title without spending heir money or changing food',()=>{const r=setup({households:2,grain:20,fish:10}),money=r.coins();r.eval("H[0].sx='m';H[1].sx='m';H[1].pa=H[0];H[0].kids=[H[1]];K.create('hay',0.0005,null,'yard');addHeld(s,H[0],'hay',0.0005);storageTitles(s,'hay');inherit(H[0]);H[0].dead=true;storageTick(s)");assert.equal(r.s.stores.hay,0);assert.equal(r.eval("stockOf(s,H[1]).held.hay"),0);assert.equal(r.s.stores.grain,20);assert.equal(r.s.stores.fish,10);assert.equal(r.coins()+r.eval('paid'),money);replay(r);});
test('removed sale remnants cannot trigger a later purchase or mutate prior history',()=>{const r=setup(),money=r.coins();r.eval("K.create('hay',0.001,null,'yard');offer(s,'hay','crown',0.001);storageTitles(s,'hay');const oldEvents=K.events.slice(),oldText=JSON.stringify(oldEvents);storageTick(s);const bill=purchase(s,'hay',H[0],0.001)");assert.equal(r.eval('purchase.got'),0);assert.equal(r.eval('bill'),0);assert.equal(r.coins(),money);assert.equal(r.eval('paid'),0);assert.equal(r.eval('JSON.stringify(oldEvents)===oldText'),true);replay(r);});

test('production deferral expires at actual monthly title assignment and retained stock emits no repeated events',()=>{const r=setup();r.eval("K.create('hay',0.0004,null,'yard');s._made.hay=0.0004;storageTick(s);const retainedEvents=K.events.length;shareOutput(s,0,new Map(),H,true);storageTick(s);storageTick(s)");assert.equal(r.s.stores.hay,0.0004);assert.equal(r.eval('s._made.hay'),0.0004);assert.equal(r.eval('K.events.length'),r.eval('retainedEvents'));r.eval("shareOutput(s,0,new Map(),H);storageTick(s)");assert.equal(r.eval('s._made.hay'),undefined);assert.equal(r.s.stores.hay,0);assert.equal(r.eval("K.events.filter(e=>e.cause==='vermin-remnant-loss').length"),1);replay(r);});
test('huge hay without crumbs performs zero additional coalescing and emits no events',()=>{const r=setup();r.eval("K.location('bulk',{capacity:Infinity});for(let i=0;i<250;i++){const l=K.create('hay',1000000,null,'bulk');K.annotate(l,{batch:i});}storageTitles(s);const nativeCoalesce=K.coalesce;let coalesceCalls=0;K.coalesce=function(...args){coalesceCalls++;return nativeCoalesce.apply(this,args)};const beforeEvents=K.events.length;storageTick(s)");assert.equal(r.s.stores.hay,250000000);assert.equal(r.eval('coalesceCalls'),0);assert.equal(r.eval('K.events.length'),r.eval('beforeEvents'));});
test('one crumb cannot coalesce unrelated large hay groups',()=>{const r=setup();r.eval("const bulk=K.create('hay',10,null,'yard');K.annotate(bulk,{batch:'bulk'});K.split(bulk,5);const tiny=K.create('hay',0.001,null,'yard');K.annotate(tiny,{batch:'tiny'});storageHayRemnants(s,K)");assert.equal(r.s.stores.hay,10);assert.equal(r.eval("[...K.lots.values()].filter(l=>l.batch==='bulk').length"),2);assert.equal(r.eval("K.events.some(e=>e.cause==='lot-merged')"),false);});
test('protected production and purchases perform no remnant grouping',()=>{const r=setup();r.eval("K.create('hay',0.0004,null,'yard');s._made.hay=0.0004;const pending=K.create('hay',0.0003,H[0],'yard','held');K.annotate(pending,{pendingPurchase:true});let coalesceCalls=0;const nativeCoalesce=K.coalesce;K.coalesce=function(...args){coalesceCalls++;return nativeCoalesce.apply(this,args)};const beforeEvents=K.events.length;storageHayRemnants(s,K);storageHayRemnants(s,K)");assert.equal(r.eval('coalesceCalls'),0);assert.equal(r.eval('K.events.length'),r.eval('beforeEvents'));});

test('a thousand distinct small native batches use linear compatibility checks and exactly one loss per object',()=>{const r=setup();r.eval("for(let i=0;i<1000;i++){const l=K.create('hay',0.0005,null,'yard');K.annotate(l,{batch:i});}let comparisons=0;const nativeCompatible=K.compatible;K.compatible=function(...args){comparisons++;return nativeCompatible.apply(this,args)};const beforeEvents=K.events.length;storageHayRemnants(s,K)");assert.ok(r.eval('comparisons')<=2000);assert.equal(r.s.stores.hay,0);assert.equal(r.eval("K.events.slice(beforeEvents).length"),1000);assert.equal(r.eval("K.events.slice(beforeEvents).every(e=>e.cause==='vermin-remnant-loss'&&e.before.qty===0.0005&&e.lotAfter.qty===0)"),true);replay(r);});
test('removal detail cannot override core physical outcome fields',()=>{const r=setup();r.eval("const l=K.create('grain',1,null,'yard');K.remove(l,0.5,'test-removal',{qty:999,cause:'fake',before:{qty:999},lotAfter:null,good:'hay',claimGood:'grain',titleBefore:1,titleAfter:0.5,legalQty:0.5})");const e=structuredClone(r.eval('K.events.at(-1)'));assert.equal(e.cause,'test-removal');assert.equal(e.good,'grain');assert.equal(e.qty,0.5);assert.equal(e.before.qty,1);assert.equal(e.lotAfter.qty,0.5);assert.equal(e.legalQty,0.5);replay(r);});
