import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
import {realm} from './ownership-fixture.mjs';
import * as acorn from './vendor/acorn/acorn.mjs';
const source=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8'),baseline=execFileSync('git',['show','24be535:index.html'],{encoding:'utf8',maxBuffer:20e6});
function fn(s,n){return s.match(new RegExp('^function '+n+'\\b[\\s\\S]*?(?=^function |^const |$(?![\\s\\S]))','m'))[0];}
function pair(cargo=30,facilities=3,lots=6){return[true,false].map(old=>{const r=realm({grain:0,fish:0,cash:1000,crown:1000,households:lots,transformSource:p=>"'use strict';\n"+p});if(old)r.eval(fn(baseline,'storageFacilities')+fn(baseline,'storageTick'));r.eval(`storageInit(s);const K=s.storage;for(let i=0;i<${cargo};i++)K.location('cargo:'+i,{transit:true,capacity:Infinity});s.buildings=Array.from({length:${facilities}},(_,i)=>({arch:'grange',storageId:'f'+i,state:'sound',x:i+1,z:0}));storageFacilities(s);for(let i=0;i<${lots};i++){K.create('grain',i+.125,accountOwner(H[i]),'yard','held');addHeld(s,H[i],'grain',i+.125);}storageTitles(s);let routes=[],wagePayments=[];storageRoute=(s,a,b)=>{routes.push(b.id);return b.x*10};wages=(s,q,why)=>{wagePayments.push([q,why]);W.treasury+=q};`);return r;});}
function state(r){return structuredClone(r.eval('({next:K.next,revision:K.revision,sequence:K.sequence,events:K.events,roundoff:[...K.roundoff],locations:[...K.locations.values()].map(n=>K.locationState(n)),lots:[...K.lots.values()].map(l=>K.lotState(l)),byLocation:[...K.byLocation].map(([k,v])=>[k,[...v]]),report:s.storageReport,treasury:W.treasury,purses:H.map(h=>h.w),routes,wagePayments})'));}
function run(P,expression='storageTick(s)'){for(const r of P)r.eval(expression);assert.deepEqual(state(P[1]),state(P[0]));}
test('actual carriage preserves complete ordered state, capacity, purse, events and precision',()=>{const P=pair();run(P);run(P,"K.create('grain',1e-12,accountOwner(H[0]),'yard','held');addHeld(s,H[0],'grain',1e-12);storageTick(s)");assert.ok(P[1].s.storageReport.moved>0);});
test('fixed facilities candidate visits are independent of1000/10000 archived cargo',()=>{for(const cargo of [1000,10000]){const P=pair(cargo,30);for(let i=0;i<P.length;i++){const s=i?source:baseline;P[i].eval('let visits=0;'+fn(s,'storageTick').replace('if(!n.building','visits++;if(!n.building')+fn(s,'storageFacilities').replace('if(n.building&&!seen.has(n.id))','if((visits++,n.building)&&!seen.has(n.id))'));}run(P);assert.equal(P[0].eval('visits'),(cargo+31)*7);assert.equal(P[1].eval('visits'),30*7);assert.equal(P[1].eval('K.locations.size'),cargo+31);}});
test('iterator observes explicit toggle, append, delete/reinsert and last-node append in Map order',()=>{const P=pair(4,0,0),results=[];for(let i=0;i<P.length;i++){const r=P[i];results.push([...r.eval(`(()=>{storageFacilityBuilding(K,'cargo:1',{});storageFacilityBuilding(K,'cargo:3',{});let seen=[];for(const n of ${i?'storageFacilityLocations(K)':'K.locations.values()'}){if(!n.building)continue;seen.push(n.id);if(n.id==='cargo:1'){storageFacilityLocationDelete(K,n.id);storageFacilityBuilding(K,'cargo:0',{});storageFacilityBuilding(K,'cargo:2',{});storageFacilityLocationDelete(K,'cargo:3');storageFacilityLocationSet(K,'cargo:3',{id:'cargo:3',building:{}});}if(n.id==='cargo:3')storageFacilityLocationSet(K,'last',{id:'last',building:{}});}return seen})()`)]);}assert.deepEqual(results[1],results[0]);assert.deepEqual(results[1],['cargo:1','cargo:2','cargo:3','last']);});
test('route callback toggles future custody and appends facilities without snapshotting candidates',()=>{const P=pair();for(const r of P)r.eval("storageRoute=(s,a,b)=>{routes.push(b.id);if(b.id==='f0'&&!K.locations.has('added')){storageFacilityBuilding(K,'cargo:2',{storageId:'cargo:2'});Object.assign(K.locations.get('cargo:2'),{active:true,public:true,x:4,z:0,capacity:100});K.location('added',{building:{storageId:'added'},active:true,public:true,x:5,z:0,capacity:100});}return b.x*10}");run(P);assert.deepEqual([...P[1].eval('routes')].slice(0,5),['f0','f1','f2','added','cargo:2']);});
test('orphan destruction retains inactive nodes, full cargo archive and exact exposure outcomes',()=>{const P=pair();run(P,'s.buildings.splice(1,1);storageFacilities(s)');assert.equal(P[1].eval("K.locations.get('f1').active"),false);assert.equal(P[1].eval("[...storageFacilityLocations(K)].some(n=>n.id==='f1')"),true);run(P);});
test('unknown, custom Maps and explicit unmanaged hooks use original complete scans',()=>{for(const expression of ["STORAGE_FACILITY_INDEXES.delete(K)","K.locations=new(class extends Map{values(){return super.values()}})(K.locations)","storageFacilityInvalidate(K)"]){const P=pair();for(const r of P)r.eval(expression);run(P);assert.equal(P[1].eval('storageFacilityIndex(K)'),null);}});
test('explicit adoption of getter metadata declines indexing before pass',()=>{const P=pair();for(const r of P)r.eval("let reads=0;Object.defineProperty(K.locations.get('cargo:0'),'building',{get(){reads++;return null},configurable:true});storageFacilityAdopt(K)");for(const r of P)r.eval('storageTick(s)');assert.equal(P[1].eval('reads'),P[0].eval('reads'));assert.equal(P[1].eval('storageFacilityIndex(K)'),null);});
test('midpass invalidation fails closed before following iteration effects',()=>{const r=pair()[1];r.eval("let effects=0;const iterator=storageFacilityLocations(K);iterator.next();try{storageFacilityInvalidate(K);effects++;}catch(e){};try{iterator.next();effects++;}catch(e){}");assert.equal(r.eval('effects'),0);assert.equal(r.eval('STORAGE_FACILITY_INDEXES.get(K).iterating'),0);});
test('future fields and unusual primitive metadata remain complete through managed changes',()=>{const P=pair();run(P,"const n=K.locations.get('f0');n.optional=undefined;n.negativeZero=-0;n.number=NaN;n.future={nested:[1,undefined]};storageFacilityBuilding(K,'f0',n.building);storageTick(s)");assert.ok(Number.isNaN(P[1].eval("K.locations.get('f0').number")));});
test('NaN/infinite routes retain exclusion and exact no-carriage arithmetic',()=>{const P=pair();for(const r of P)r.eval("storageRoute=(s,a,b)=>{routes.push(b.id);return b.id==='f0'?NaN:Infinity}");run(P);assert.equal(P[1].s.storageReport.moved,0);});
test('membership index is current before change event callbacks run',()=>{const r=pair()[1];r.eval("let inEvent;storageOutcome=e=>{K.events.push(e);if(e.cause==='facility-membership')inEvent=[...storageFacilityLocations(K)].some(n=>n.id==='cargo:0')};storageFacilityBuilding(K,'cargo:0',{storageId:'cargo:0'})");assert.equal(r.eval('inEvent'),true);});
test('source architecture gate pins legacy/v3 facility mutation sites and metadata boundaries',()=>{const start=source.indexOf("'use strict';"),p=source.slice(start,source.indexOf('</script>',start)),ast=acorn.parse(p,{ecmaVersion:'latest'}),writes=[],initializers=[],options=[],definitions=[];
function key(n){return n?.type==='MemberExpression'?(n.computed?n.property.type==='Literal'?n.property.value:null:n.property.name):null;}
function walk(n){if(!n?.type)return;const target=n.left||n.argument;if(['AssignmentExpression','UpdateExpression'].includes(n.type)){if(target?.object?.name==='n'&&['building','exposed'].includes(key(target)))writes.push(p.slice(n.start,n.end));if(target?.object?.type==='ThisExpression'&&['locations','facilities'].includes(key(target)))initializers.push(p.slice(n.start,n.end));}if(n.type==='CallExpression'){if(n.callee?.object?.name==='Object'&&((key(n.callee)==='defineProperty'&&['building','exposed'].includes(n.arguments[1]?.value))||(key(n.callee)==='defineProperties'&&n.arguments[1]?.type==='ObjectExpression'&&n.arguments[1].properties.some(v=>['building','exposed'].includes(v.key?.name||v.key?.value)))))definitions.push(p.slice(n.start,n.end));const receiver=n.callee?.object?.object;if((receiver?.name==='K'||receiver?.type==='ThisExpression')&&['locations','facilities'].includes(key(n.callee?.object))&&['set','delete','clear'].includes(key(n.callee)))writes.push(p.slice(n.start,n.end));if(n.callee.type==='MemberExpression'&&n.callee.object.name==='Object'&&key(n.callee)==='assign'&&(n.arguments[0]?.name==='n'||n.arguments.slice(1).some(a=>a.type==='ObjectExpression'&&a.properties.some(v=>['building','exposed'].includes(v.key?.name||v.key?.value)))))options.push(p.slice(n.start,n.end));}for(const v of Object.values(n))if(Array.isArray(v))v.forEach(walk);else if(v?.type)walk(v);}
walk(ast);assert.deepEqual(definitions,[]);assert.deepEqual(writes,['K.locations.set(id,n)','K.locations.delete(id)','K.locations.clear()','n.building=building','this.facilities.set(id, facility = next)']);assert.deepEqual(initializers,['this.facilities = new Map()','this.locations = this.facilities','this.locations=new Map()']);assert.deepEqual(options,['Object.assign(n,{active:true,capacity,x:b.x,z:b.z,owner,public:b.storagePublic!==false,protection:t.protection})']);assert.match(source,/storageFacilityLocationSet\(this,id,n\);this.revision\+\+/);assert.match(source,/meta\.storageId = value\.storageId/);assert.match(source,/else if \(value == null \|\| \['string', 'number', 'boolean'\]\.includes\(typeof value\)\) meta\.building = value/);
});
test('custom Map live iteration additions/deletions preserve native fallback timing',()=>{const P=pair();for(const r of P)r.eval("K.locations=new(class extends Map{values(){const self=this;return(function*(){let once=false;for(const n of Map.prototype.values.call(self)){if(!once){once=true;self.delete('cargo:1');self.set('live-custom',{id:'live-custom',building:{},active:false});}yield n;}})();}})(K.locations)");run(P);assert.equal(P[1].eval('storageFacilityIndex(K)'),null);});
test('clear and reappend preserve original live Map cursor without ordinal reuse',()=>{const P=pair(0,2,0),seen=[];for(let i=0;i<P.length;i++)seen.push([...P[i].eval(`(()=>{const out=[];for(const n of ${i?'storageFacilityLocations(K)':'K.locations.values()'}){if(!n.building)continue;out.push(n.id);if(n.id==='f0'){storageFacilityLocationClear(K);storageFacilityLocationSet(K,NaN,{id:NaN,building:{}});storageFacilityLocationSet(K,'end',{id:'end',building:{}})}}return out})()`)]);assert.deepEqual(seen[1],seen[0]);assert.deepEqual(seen[1],['f0',NaN,'end']);});
